"""Expected concept ids for Java Course v1 tasks."""

from __future__ import annotations

from application.curriculum.cpp.catalog.cpp_v311_expected_concepts import CHAPTER_DEFAULTS

SLOT_OVERRIDES: dict[str, list[str]] = {
    "java_001": ["program_entry", "stdout_write"],
    "java_002": ["typed_declaration", "stdout_write", "assignment"],
    "java_003": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops"],
    "java_004": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops"],
    "java_005": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops"],
    "java_006": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops"],
    "java_007": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops"],
    "java_008": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops"],
    "java_009": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops"],
    "java_010": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops"],
    "java_011": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops"],
    "java_012": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops"],
    "java_013": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "object_instance"],
    "java_014": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "string_sequence", "linked_node", "object_instance"],
    "java_015": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "object_instance"],
    "java_016": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "object_instance"],
    "java_017": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "object_instance"],
    "java_018": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "object_instance"],
    "java_019": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "object_instance"],
    "java_020": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "object_instance"],
    "java_021": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "object_instance"],
    "java_022": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "string_sequence", "linked_node", "object_instance"],
    "java_023": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "object_instance"],
    "java_024": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "object_instance"],
    "java_025": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "conditional_expression", "object_instance"],
    "java_026": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "conditional_expression", "object_instance"],
    "java_027": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "conditional_expression", "object_instance"],
    "java_028": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "conditional_expression", "object_instance"],
    "java_029": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "conditional_expression", "object_instance"],
    "java_030": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "conditional_expression", "object_instance"],
    "java_031": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "conditional_expression", "string_sequence", "linked_node", "object_instance"],
    "java_032": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "conditional_expression", "object_instance"],
    "java_033": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "conditional_expression", "object_instance"],
    "java_034": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "conditional_expression", "object_instance"],
    "java_035": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "conditional_expression", "object_instance"],
    "java_036": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "conditional_expression", "object_instance"],
    "java_037": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "conditional_expression", "object_instance"],
    "java_038": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "conditional_expression", "object_instance"],
    "java_039": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "simple_branch", "conditional_expression", "object_instance"],
    "java_040": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "multi_branch", "switch_selection", "string_sequence", "lambda", "object_instance"],
    "java_041": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "multi_branch", "switch_selection", "string_sequence", "lambda", "object_instance"],
    "java_042": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "multi_branch", "switch_selection", "string_sequence", "lambda", "object_instance"],
    "java_043": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "simple_branch", "conditional_expression", "object_instance"],
    "java_044": ["switch", "break", "break", "break"],
    "java_045": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "multi_branch", "switch_selection", "string_sequence", "lambda", "object_instance"],
    "java_046": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "simple_branch", "conditional_expression", "object_instance"],
    "java_047": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "simple_branch", "conditional_expression", "object_instance"],
    "java_048": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "simple_branch", "conditional_expression", "object_instance"],
    "java_049": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "multi_branch", "switch_selection", "string_sequence", "lambda", "object_instance"],
    "java_050": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "multi_branch", "switch_selection", "string_sequence", "lambda", "object_instance"],
    "java_051": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "object_instance"],
    "java_052": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "object_instance"],
    "java_053": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "object_instance"],
    "java_054": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "object_instance"],
    "java_055": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "object_instance"],
    "java_056": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "object_instance"],
    "java_057": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "object_instance"],
    "java_058": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "object_instance"],
    "java_059": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "object_instance"],
    "java_060": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "object_instance"],
    "java_061": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "object_instance"],
    "java_062": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "object_instance"],
    "java_063": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "pre_condition_loop", "object_instance"],
    "java_064": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "pre_condition_loop", "object_instance"],
    "java_065": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "object_instance"],
    "java_066": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "object_instance"],
    "java_067": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "object_instance"],
    "java_068": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "object_instance"],
    "java_069": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "object_instance"],
    "java_070": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "object_instance"],
    "java_071": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "object_instance"],
    "java_072": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "object_instance"],
    "java_073": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "object_instance"],
    "java_074": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "object_instance"],
    "java_075": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "object_instance"],
    "java_076": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "object_instance"],
    "java_077": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "object_instance"],
    "java_078": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "object_instance"],
    "java_079": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "key_value_map", "object_instance"],
    "java_080": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "key_value_map", "object_instance"],
    "java_081": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "key_value_map", "object_instance"],
    "java_082": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "key_value_map", "object_instance"],
    "java_083": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "key_value_map", "object_instance"],
    "java_084": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "key_value_map", "object_instance"],
    "java_085": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "key_value_map", "object_instance"],
    "java_086": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "key_value_map", "object_instance"],
    "java_087": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "key_value_map", "object_instance"],
    "java_088": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "key_value_map", "object_instance"],
    "java_089": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "key_value_map", "object_instance"],
    "java_090": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "key_value_map", "object_instance"],
    "java_091": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "key_value_map", "object_instance"],
    "java_092": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "key_value_map", "object_instance"],
    "java_093": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "key_value_map", "object_instance"],
    "java_094": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "key_value_map", "object_instance"],
    "java_095": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "dynamic_array", "object_instance"],
    "java_096": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "dynamic_array", "object_instance"],
    "java_097": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "dynamic_array", "object_instance"],
    "java_098": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "dynamic_array", "object_instance"],
    "java_099": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "dynamic_array", "object_instance"],
    "java_100": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "dynamic_array", "object_instance"],
    "java_101": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "dynamic_array", "object_instance"],
    "java_102": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "dynamic_array", "object_instance"],
    "java_103": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "dynamic_array", "object_instance"],
    "java_104": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "dynamic_array", "object_instance"],
    "java_105": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "dynamic_array", "object_instance"],
    "java_106": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "dynamic_array", "object_instance"],
    "java_107": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "dynamic_array", "object_instance"],
    "java_108": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "dynamic_array", "object_instance"],
    "java_109": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "string_sequence", "linked_node", "object_instance"],
    "java_110": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "string_sequence", "linked_node", "object_instance"],
    "java_111": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "string_sequence", "linked_node", "object_instance"],
    "java_112": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "string_sequence", "linked_node", "object_instance"],
    "java_113": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "string_sequence", "linked_node", "object_instance"],
    "java_114": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "string_sequence", "linked_node", "object_instance"],
    "java_115": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "string_sequence", "linked_node", "object_instance"],
    "java_116": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "string_sequence", "linked_node", "object_instance"],
    "java_117": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "string_sequence", "linked_node", "object_instance"],
    "java_118": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "string_sequence", "linked_node", "object_instance"],
    "java_119": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "string_sequence", "linked_node", "object_instance"],
    "java_120": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "string_sequence", "linked_node", "object_instance"],
    "java_121": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "string_sequence", "linked_node", "object_instance"],
    "java_122": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "string_sequence", "linked_node", "object_instance"],
    "java_123": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "return_flow", "object_instance"],
    "java_124": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "return_flow", "object_instance"],
    "java_125": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "return_flow", "object_instance"],
    "java_126": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "return_flow", "object_instance"],
    "java_127": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "return_flow", "object_instance"],
    "java_128": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "return_flow", "object_instance"],
    "java_129": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "return_flow", "object_instance"],
    "java_130": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "return_flow", "object_instance"],
    "java_131": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "return_flow", "object_instance"],
    "java_132": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "return_flow", "object_instance"],
    "java_133": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "return_flow", "object_instance"],
    "java_134": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "return_flow", "object_instance"],
    "java_135": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "return_flow", "object_instance"],
    "java_136": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "return_flow", "object_instance"],
    "java_137": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "return_flow", "object_instance"],
    "java_138": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "return_flow", "object_instance"],
    "java_139": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "return_flow", "object_instance"],
    "java_140": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "return_flow", "object_instance"],
    "java_141": ["typed_declaration", "stdout_write", "arithmetic_ops", "conditional_expression", "function_definition", "return_flow", "parameter_passing", "recursion"],
    "java_142": ["typed_declaration", "stdout_write", "arithmetic_ops", "conditional_expression", "function_definition", "return_flow", "parameter_passing", "recursion"],
    "java_143": ["typed_declaration", "stdout_write", "arithmetic_ops", "conditional_expression", "function_definition", "return_flow", "parameter_passing", "recursion"],
    "java_144": ["typed_declaration", "stdout_write", "arithmetic_ops", "conditional_expression", "function_definition", "return_flow", "parameter_passing", "recursion"],
    "java_145": ["typed_declaration", "stdout_write", "arithmetic_ops", "conditional_expression", "function_definition", "return_flow", "parameter_passing", "recursion"],
    "java_146": ["typed_declaration", "stdout_write", "arithmetic_ops", "conditional_expression", "function_definition", "return_flow", "parameter_passing", "recursion"],
    "java_147": ["typed_declaration", "stdout_write", "arithmetic_ops", "conditional_expression", "function_definition", "return_flow", "parameter_passing", "recursion"],
    "java_148": ["typed_declaration", "stdout_write", "arithmetic_ops", "conditional_expression", "function_definition", "return_flow", "parameter_passing", "recursion"],
    "java_149": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "filter_select", "fold_aggregate", "lambda"],
    "java_150": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "filter_select", "fold_aggregate", "lambda"],
    "java_151": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "filter_select", "fold_aggregate", "lambda"],
    "java_152": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "filter_select", "fold_aggregate", "lambda"],
    "java_153": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "filter_select", "fold_aggregate", "lambda"],
    "java_154": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "filter_select", "fold_aggregate", "lambda"],
    "java_155": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "filter_select", "fold_aggregate", "lambda"],
    "java_156": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "filter_select", "fold_aggregate", "lambda"],
    "java_157": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "filter_select", "fold_aggregate", "lambda"],
    "java_158": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "filter_select", "fold_aggregate", "lambda"],
    "java_159": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "filter_select", "fold_aggregate", "lambda"],
    "java_160": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "filter_select", "fold_aggregate", "lambda"],
    "java_161": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "filter_select", "fold_aggregate", "lambda"],
    "java_162": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "filter_select", "fold_aggregate", "lambda"],
    "java_163": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "filter_select", "fold_aggregate", "lambda"],
    "java_164": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "filter_select", "fold_aggregate", "lambda"],
    "java_165": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "filter_select", "fold_aggregate", "lambda"],
    "java_166": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "filter_select", "fold_aggregate", "lambda"],
    "java_167": ["typed_declaration", "stdout_write", "assignment", "indexed_sequence", "dynamic_array", "sort_order"],
    "java_168": ["typed_declaration", "stdout_write", "assignment", "indexed_sequence", "dynamic_array", "sort_order"],
    "java_169": ["typed_declaration", "stdout_write", "assignment", "indexed_sequence", "dynamic_array", "sort_order"],
    "java_170": ["typed_declaration", "stdout_write", "assignment", "indexed_sequence", "dynamic_array", "sort_order"],
    "java_171": ["typed_declaration", "stdout_write", "assignment", "indexed_sequence", "dynamic_array", "sort_order"],
    "java_172": ["typed_declaration", "stdout_write", "assignment", "indexed_sequence", "dynamic_array", "sort_order"],
    "java_173": ["typed_declaration", "stdout_write", "assignment", "indexed_sequence", "dynamic_array", "sort_order"],
    "java_174": ["typed_declaration", "stdout_write", "assignment", "indexed_sequence", "dynamic_array", "sort_order"],
    "java_175": ["typed_declaration", "stdout_write", "assignment", "indexed_sequence", "dynamic_array", "sort_order"],
    "java_176": ["typed_declaration", "stdout_write", "assignment", "indexed_sequence", "dynamic_array", "sort_order"],
    "java_177": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "filter_select", "fold_aggregate", "lambda"],
    "java_178": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "filter_select", "fold_aggregate", "lambda"],
    "java_179": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "filter_select", "fold_aggregate", "lambda"],
    "java_180": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "filter_select", "fold_aggregate", "lambda"],
    "java_181": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "key_value_map", "object_instance"],
    "java_182": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "key_value_map", "object_instance"],
    "java_183": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "key_value_map", "object_instance"],
    "java_184": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "key_value_map", "object_instance"],
    "java_185": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "filter_select", "fold_aggregate", "lambda"],
    "java_186": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "filter_select", "fold_aggregate", "lambda"],
    "java_187": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "filter_select", "fold_aggregate", "lambda"],
    "java_188": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "key_value_map", "object_instance"],
    "java_189": ["typed_declaration", "stdout_write", "assignment", "file_read"],
    "java_190": ["typed_declaration", "stdout_write", "assignment", "file_read"],
    "java_191": ["typed_declaration", "stdout_write", "assignment", "file_read"],
    "java_192": ["typed_declaration", "stdout_write", "assignment", "file_read"],
    "java_193": ["typed_declaration", "stdout_write", "assignment", "file_read"],
    "java_194": ["typed_declaration", "stdout_write", "assignment", "file_read"],
    "java_195": ["typed_declaration", "stdout_write", "assignment", "file_read"],
    "java_196": ["typed_declaration", "stdout_write", "assignment", "file_read"],
    "java_197": ["typed_declaration", "stdout_write", "assignment", "file_read"],
    "java_198": ["typed_declaration", "stdout_write", "assignment", "file_read"],
    "java_199": ["import_dependency", "module_namespace", "typed_declaration", "stdout_write", "arithmetic_ops", "function_definition", "return_flow", "parameter_passing", "recursion", "class_type"],
    "java_200": ["import_dependency", "module_namespace", "typed_declaration", "stdout_write", "arithmetic_ops", "function_definition", "return_flow", "parameter_passing", "recursion", "class_type"],
    "java_201": ["import_dependency", "module_namespace", "typed_declaration", "stdout_write", "arithmetic_ops", "function_definition", "return_flow", "parameter_passing", "recursion", "class_type"],
    "java_202": ["import_dependency", "module_namespace", "typed_declaration", "stdout_write", "arithmetic_ops", "function_definition", "return_flow", "parameter_passing", "recursion", "class_type"],
    "java_203": ["import_dependency", "module_namespace", "typed_declaration", "stdout_write", "arithmetic_ops", "function_definition", "return_flow", "parameter_passing", "recursion", "class_type"],
    "java_204": ["import_dependency", "module_namespace", "typed_declaration", "stdout_write", "arithmetic_ops", "function_definition", "return_flow", "parameter_passing", "recursion", "class_type"],
    "java_205": ["import_dependency", "module_namespace", "typed_declaration", "stdout_write", "arithmetic_ops", "function_definition", "return_flow", "parameter_passing", "recursion", "class_type"],
    "java_206": ["import_dependency", "module_namespace", "typed_declaration", "stdout_write", "arithmetic_ops", "function_definition", "return_flow", "parameter_passing", "recursion", "class_type"],
    "java_207": ["typed_declaration", "stdout_write", "assignment", "stack_queue"],
    "java_208": ["typed_declaration", "stdout_write", "assignment", "stack_queue"],
    "java_209": ["typed_declaration", "stdout_write", "assignment", "stack_queue"],
    "java_210": ["typed_declaration", "stdout_write", "assignment", "stack_queue"],
    "java_211": ["typed_declaration", "stdout_write", "assignment", "linked_node", "class_type"],
    "java_212": ["typed_declaration", "stdout_write", "assignment", "linked_node", "class_type"],
    "java_213": ["typed_declaration", "stdout_write", "assignment", "linked_node", "class_type"],
    "java_214": ["typed_declaration", "stdout_write", "assignment", "linked_node", "class_type"],
    "java_215": ["typed_declaration", "stdout_write", "assignment", "linked_node", "class_type"],
    "java_216": ["typed_declaration", "stdout_write", "assignment", "linked_node", "class_type"],
    "java_217": ["typed_declaration", "stdout_write", "assignment", "indexed_sequence", "graph_edges"],
    "java_218": ["typed_declaration", "stdout_write", "assignment", "indexed_sequence", "graph_edges"],
    "java_219": ["typed_declaration", "stdout_write", "assignment", "indexed_sequence", "graph_edges"],
    "java_220": ["typed_declaration", "stdout_write", "assignment", "indexed_sequence", "graph_edges"],
    "java_221": ["typed_declaration", "stdout_write", "assignment", "indexed_sequence", "graph_edges"],
    "java_222": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "filter_select", "fold_aggregate", "lambda"],
    "java_223": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "filter_select", "fold_aggregate", "lambda"],
    "java_224": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "filter_select", "fold_aggregate", "lambda"],
    "java_225": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "filter_select", "fold_aggregate", "lambda"],
    "java_226": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "filter_select", "fold_aggregate", "lambda"],
    "java_227": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "filter_select", "fold_aggregate", "lambda"],
    "java_228": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "filter_select", "fold_aggregate", "lambda"],
    "java_229": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "filter_select", "fold_aggregate", "lambda"],
    "java_230": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "filter_select", "fold_aggregate", "lambda"],
    "java_231": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "filter_select", "fold_aggregate", "lambda"],
    "java_232": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "filter_select", "fold_aggregate", "lambda"],
    "java_233": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "filter_select", "fold_aggregate", "lambda"],
    "java_234": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "filter_select", "fold_aggregate", "lambda"],
    "java_235": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "filter_select", "fold_aggregate", "lambda"],
    "java_236": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "filter_select", "fold_aggregate", "lambda"],
    "java_237": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "string_sequence", "function_definition", "return_flow", "parameter_passing", "recursion", "class_type"],
    "java_238": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "string_sequence", "function_definition", "return_flow", "parameter_passing", "recursion", "class_type"],
    "java_239": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "string_sequence", "function_definition", "return_flow", "parameter_passing", "recursion", "class_type"],
    "java_240": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "string_sequence", "function_definition", "return_flow", "parameter_passing", "recursion", "class_type"],
    "java_241": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "string_sequence", "function_definition", "return_flow", "parameter_passing", "recursion", "class_type"],
    "java_242": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "string_sequence", "function_definition", "return_flow", "parameter_passing", "recursion", "class_type"],
    "java_243": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "string_sequence", "function_definition", "return_flow", "parameter_passing", "recursion", "class_type"],
    "java_244": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "string_sequence", "function_definition", "return_flow", "parameter_passing", "recursion", "class_type"],
    "java_245": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "string_sequence", "function_definition", "return_flow", "parameter_passing", "recursion", "class_type"],
    "java_246": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "string_sequence", "function_definition", "return_flow", "parameter_passing", "recursion", "class_type"],
    "java_247": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "string_sequence", "function_definition", "return_flow", "parameter_passing", "recursion", "class_type"],
    "java_248": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "string_sequence", "function_definition", "return_flow", "parameter_passing", "recursion", "class_type"],
    "java_249": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "string_sequence", "function_definition", "return_flow", "parameter_passing", "recursion", "class_type"],
    "java_250": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "string_sequence", "function_definition", "return_flow", "parameter_passing", "recursion", "class_type"],
    "java_251": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "string_sequence", "function_definition", "return_flow", "parameter_passing", "recursion", "class_type"],
    "java_252": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "string_sequence", "function_definition", "return_flow", "parameter_passing", "recursion", "class_type"],
    "java_253": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "string_sequence", "function_definition", "return_flow", "parameter_passing", "recursion", "class_type"],
    "java_254": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "string_sequence", "function_definition", "return_flow", "parameter_passing", "recursion", "class_type"],
    "java_255": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "string_sequence", "function_definition", "return_flow", "parameter_passing", "recursion", "class_type"],
    "java_256": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "string_sequence", "function_definition", "return_flow", "parameter_passing", "recursion", "class_type"],
    "java_257": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "string_sequence", "function_definition", "return_flow", "parameter_passing", "recursion", "class_type"],
    "java_258": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "string_sequence", "function_definition", "return_flow", "parameter_passing", "recursion", "class_type"],
    "java_259": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "string_sequence", "function_definition", "return_flow", "parameter_passing", "recursion", "class_type"],
    "java_260": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "string_sequence", "function_definition", "return_flow", "parameter_passing", "recursion", "class_type"],
    "java_261": ["typed_declaration", "stdout_write", "assignment", "function_definition", "return_flow", "parameter_passing", "recursion", "class_type", "inheritance_hierarchy"],
    "java_262": ["typed_declaration", "stdout_write", "assignment", "function_definition", "return_flow", "parameter_passing", "recursion", "class_type", "inheritance_hierarchy"],
    "java_263": ["typed_declaration", "stdout_write", "assignment", "function_definition", "return_flow", "parameter_passing", "recursion", "class_type", "inheritance_hierarchy"],
    "java_264": ["typed_declaration", "stdout_write", "assignment", "function_definition", "return_flow", "parameter_passing", "recursion", "class_type", "inheritance_hierarchy"],
    "java_265": ["typed_declaration", "stdout_write", "assignment", "function_definition", "return_flow", "parameter_passing", "recursion", "class_type", "inheritance_hierarchy"],
    "java_266": ["typed_declaration", "stdout_write", "assignment", "function_definition", "return_flow", "parameter_passing", "recursion", "class_type", "inheritance_hierarchy"],
    "java_267": ["typed_declaration", "stdout_write", "assignment", "function_definition", "return_flow", "parameter_passing", "recursion", "class_type", "inheritance_hierarchy"],
    "java_268": ["typed_declaration", "stdout_write", "assignment", "function_definition", "return_flow", "parameter_passing", "recursion", "class_type", "inheritance_hierarchy"],
    "java_269": ["typed_declaration", "stdout_write", "assignment", "function_definition", "return_flow", "parameter_passing", "recursion", "class_type", "inheritance_hierarchy"],
    "java_270": ["typed_declaration", "stdout_write", "assignment", "function_definition", "return_flow", "parameter_passing", "recursion", "class_type", "inheritance_hierarchy"],
}


def expected_concept_ids_for_row(
    slot_id: str,
    chapter_key: str,
    *,
    _features: str = "",
) -> list[str]:
    override = SLOT_OVERRIDES.get(slot_id)
    if override:
        return list(override)
    return list(CHAPTER_DEFAULTS.get(chapter_key, ["program_entry"]))


__all__ = ["expected_concept_ids_for_row", "CHAPTER_DEFAULTS", "SLOT_OVERRIDES"]
