"""Pascal and C++ reference solutions for expansion tasks 129–144."""

from __future__ import annotations

PASCAL_REF_129_144: dict[int, str] = {
    129: (
        "var n, s, i, d: integer;\n"
        "begin\n"
        "  readln(n);\n"
        "  if n < 0 then n := -n;\n"
        "  s := 0;\n"
        "  while n > 0 do\n"
        "  begin\n"
        "    d := n mod 10;\n"
        "    s := s + d;\n"
        "    n := n div 10;\n"
        "  end;\n"
        "  writeln(s);\n"
        "end."
    ),
    130: (
        "var n, i, x, c: integer;\n"
        "begin\n"
        "  readln(n);\n"
        "  c := 0;\n"
        "  for i := 1 to n do\n"
        "  begin\n"
        "    readln(x);\n"
        "    if x mod 2 = 0 then c := c + 1;\n"
        "  end;\n"
        "  writeln(c);\n"
        "end."
    ),
    131: (
        "var n, i, x, total: integer;\n"
        "begin\n"
        "  readln(n);\n"
        "  total := 0;\n"
        "  for i := 1 to n do\n"
        "  begin\n"
        "    readln(x);\n"
        "    total := total + x;\n"
        "  end;\n"
        "  writeln(total div n);\n"
        "end."
    ),
    132: (
        "var n, i, x, best: integer;\n"
        "begin\n"
        "  readln(n);\n"
        "  readln(best);\n"
        "  for i := 2 to n do\n"
        "  begin\n"
        "    readln(x);\n"
        "    if x < best then best := x;\n"
        "  end;\n"
        "  writeln(best);\n"
        "end."
    ),
    133: (
        "var y: integer;\n"
        "    leap: boolean;\n"
        "begin\n"
        "  readln(y);\n"
        "  leap := (y mod 400 = 0) or ((y mod 4 = 0) and (y mod 100 <> 0));\n"
        "  if leap then writeln('yes') else writeln('no');\n"
        "end."
    ),
    134: (
        "var w, h, b: integer;\n"
        "    cat: string;\n"
        "begin\n"
        "  readln(w, h);\n"
        "  b := w * 10000 div (h * h);\n"
        "  if b < 1850 then cat := 'under'\n"
        "  else if b < 2500 then cat := 'normal'\n"
        "  else if b < 3000 then cat := 'over'\n"
        "  else cat := 'obese';\n"
        "  writeln(cat);\n"
        "end."
    ),
    135: (
        "var a, b, x: integer;\n"
        "begin\n"
        "  readln(a, b, x);\n"
        "  if (x >= a) and (x <= b) then writeln('yes') else writeln('no');\n"
        "end."
    ),
    136: (
        "var a, b, c, d: integer;\n"
        "    roots: integer;\n"
        "begin\n"
        "  readln(a, b, c);\n"
        "  d := b * b - 4 * a * c;\n"
        "  if d < 0 then roots := 0\n"
        "  else if d = 0 then roots := 1\n"
        "  else roots := 2;\n"
        "  writeln(roots);\n"
        "end."
    ),
    137: (
        "var n, s: integer;\n"
        "begin\n"
        "  readln(n);\n"
        "  s := n * (n + 1) div 2;\n"
        "  writeln(s);\n"
        "end."
    ),
    138: (
        "var a, b, t: integer;\n"
        "begin\n"
        "  readln(a, b);\n"
        "  while b <> 0 do\n"
        "  begin\n"
        "    t := a mod b;\n"
        "    a := b;\n"
        "    b := t;\n"
        "  end;\n"
        "  writeln(a);\n"
        "end."
    ),
    139: (
        "var x, total: integer;\n"
        "begin\n"
        "  total := 0;\n"
        "  readln(x);\n"
        "  while x <> 0 do\n"
        "  begin\n"
        "    if x > 0 then total := total + x;\n"
        "    readln(x);\n"
        "  end;\n"
        "  writeln(total);\n"
        "end."
    ),
    140: (
        "var n, steps: integer;\n"
        "begin\n"
        "  readln(n);\n"
        "  steps := 1;\n"
        "  while n <> 1 do\n"
        "  begin\n"
        "    if n mod 2 = 0 then n := n div 2 else n := 3 * n + 1;\n"
        "    steps := steps + 1;\n"
        "  end;\n"
        "  writeln(steps);\n"
        "end."
    ),
    141: (
        "var n, i, x, best, second: integer;\n"
        "begin\n"
        "  readln(n);\n"
        "  readln(best);\n"
        "  second := -1000000000;\n"
        "  for i := 2 to n do\n"
        "  begin\n"
        "    readln(x);\n"
        "    if x > best then\n"
        "    begin\n"
        "      second := best;\n"
        "      best := x;\n"
        "    end\n"
        "    else if (x > second) and (x <> best) then second := x;\n"
        "  end;\n"
        "  writeln(second);\n"
        "end."
    ),
    142: (
        "var n, i, j, x: integer;\n"
        "    a: array[1..100] of integer;\n"
        "begin\n"
        "  readln(n);\n"
        "  for i := 1 to n do readln(a[i]);\n"
        "  j := 0;\n"
        "  for i := 1 to n do\n"
        "    if a[i] <> 0 then\n"
        "    begin\n"
        "      j := j + 1;\n"
        "      a[j] := a[i];\n"
        "    end;\n"
        "  for i := j + 1 to n do a[i] := 0;\n"
        "  for i := 1 to n do\n"
        "  begin\n"
        "    write(a[i]);\n"
        "    if i < n then write(' ');\n"
        "  end;\n"
        "end."
    ),
    143: (
        "var n, i: integer;\n"
        "    a: array[1..100] of integer;\n"
        "begin\n"
        "  readln(n);\n"
        "  for i := 1 to n do readln(a[i]);\n"
        "  for i := n downto 1 do\n"
        "  begin\n"
        "    write(a[i]);\n"
        "    if i > 1 then write(' ');\n"
        "  end;\n"
        "end."
    ),
    144: (
        "var n, i, x, s: integer;\n"
        "begin\n"
        "  readln(n);\n"
        "  s := 0;\n"
        "  write('0');\n"
        "  for i := 1 to n do\n"
        "  begin\n"
        "    readln(x);\n"
        "    s := s + x;\n"
        "    write(' ', s);\n"
        "  end;\n"
        "end."
    ),
}

CPP_REF_129_144: dict[int, str] = {
    129: (
        "#include <iostream>\n"
        "int main() {\n"
        "    int n, s = 0;\n"
        "    std::cin >> n;\n"
        "    if (n < 0) n = -n;\n"
        "    while (n > 0) { s += n % 10; n /= 10; }\n"
        "    std::cout << s;\n"
        "    return 0;\n"
        "}"
    ),
    130: (
        "#include <iostream>\n"
        "int main() {\n"
        "    int n, c = 0;\n"
        "    std::cin >> n;\n"
        "    for (int i = 0; i < n; i++) {\n"
        "        int x; std::cin >> x;\n"
        "        if (x % 2 == 0) c++;\n"
        "    }\n"
        "    std::cout << c;\n"
        "    return 0;\n"
        "}"
    ),
    131: (
        "#include <iostream>\n"
        "int main() {\n"
        "    int n, total = 0, x;\n"
        "    std::cin >> n;\n"
        "    for (int i = 0; i < n; i++) { std::cin >> x; total += x; }\n"
        "    std::cout << total / n;\n"
        "    return 0;\n"
        "}"
    ),
    132: (
        "#include <iostream>\n"
        "int main() {\n"
        "    int n, best, x;\n"
        "    std::cin >> n >> best;\n"
        "    for (int i = 1; i < n; i++) {\n"
        "        std::cin >> x;\n"
        "        if (x < best) best = x;\n"
        "    }\n"
        "    std::cout << best;\n"
        "    return 0;\n"
        "}"
    ),
    133: (
        "#include <iostream>\n"
        "int main() {\n"
        "    int y; std::cin >> y;\n"
        "    bool leap = (y % 400 == 0) || (y % 4 == 0 && y % 100 != 0);\n"
        "    std::cout << (leap ? \"yes\" : \"no\");\n"
        "    return 0;\n"
        "}"
    ),
    134: (
        "#include <iostream>\n"
        "#include <string>\n"
        "int main() {\n"
        "    int w, h; std::cin >> w >> h;\n"
        "    int b = w * 10000 / (h * h);\n"
        "    std::string cat;\n"
        "    if (b < 1850) cat = \"under\";\n"
        "    else if (b < 2500) cat = \"normal\";\n"
        "    else if (b < 3000) cat = \"over\";\n"
        "    else cat = \"obese\";\n"
        "    std::cout << cat;\n"
        "    return 0;\n"
        "}"
    ),
    135: (
        "#include <iostream>\n"
        "int main() {\n"
        "    int a, b, x; std::cin >> a >> b >> x;\n"
        "    std::cout << (a <= x && x <= b ? \"yes\" : \"no\");\n"
        "    return 0;\n"
        "}"
    ),
    136: (
        "#include <iostream>\n"
        "int main() {\n"
        "    int a, b, c; std::cin >> a >> b >> c;\n"
        "    int d = b * b - 4 * a * c;\n"
        "    int roots = (d < 0 ? 0 : (d == 0 ? 1 : 2));\n"
        "    std::cout << roots;\n"
        "    return 0;\n"
        "}"
    ),
    137: (
        "#include <iostream>\n"
        "int main() {\n"
        "    int n; std::cin >> n;\n"
        "    std::cout << n * (n + 1) / 2;\n"
        "    return 0;\n"
        "}"
    ),
    138: (
        "#include <iostream>\n"
        "int main() {\n"
        "    int a, b; std::cin >> a >> b;\n"
        "    while (b) { int t = a % b; a = b; b = t; }\n"
        "    std::cout << a;\n"
        "    return 0;\n"
        "}"
    ),
    139: (
        "#include <iostream>\n"
        "int main() {\n"
        "    int total = 0, x;\n"
        "    std::cin >> x;\n"
        "    while (x != 0) {\n"
        "        if (x > 0) total += x;\n"
        "        std::cin >> x;\n"
        "    }\n"
        "    std::cout << total;\n"
        "    return 0;\n"
        "}"
    ),
    140: (
        "#include <iostream>\n"
        "int main() {\n"
        "    int n, steps = 1; std::cin >> n;\n"
        "    while (n != 1) {\n"
        "        if (n % 2 == 0) n /= 2; else n = 3 * n + 1;\n"
        "        steps++;\n"
        "    }\n"
        "    std::cout << steps;\n"
        "    return 0;\n"
        "}"
    ),
    141: (
        "#include <iostream>\n"
        "int main() {\n"
        "    int n, best, second = -1000000000, x;\n"
        "    std::cin >> n >> best;\n"
        "    for (int i = 1; i < n; i++) {\n"
        "        std::cin >> x;\n"
        "        if (x > best) { second = best; best = x; }\n"
        "        else if (x > second && x != best) second = x;\n"
        "    }\n"
        "    std::cout << second;\n"
        "    return 0;\n"
        "}"
    ),
    142: (
        "#include <iostream>\n"
        "int main() {\n"
        "    int n; std::cin >> n;\n"
        "    int a[100], j = 0;\n"
        "    for (int i = 0; i < n; i++) {\n"
        "        int x; std::cin >> x;\n"
        "        if (x != 0) a[j++] = x;\n"
        "    }\n"
        "    for (int i = j; i < n; i++) a[i] = 0;\n"
        "    for (int i = 0; i < n; i++) {\n"
        "        if (i) std::cout << ' ';\n"
        "        std::cout << a[i];\n"
        "    }\n"
        "    return 0;\n"
        "}"
    ),
    143: (
        "#include <iostream>\n"
        "int main() {\n"
        "    int n; std::cin >> n;\n"
        "    int a[100];\n"
        "    for (int i = 0; i < n; i++) std::cin >> a[i];\n"
        "    for (int i = n - 1; i >= 0; i--) {\n"
        "        if (i != n - 1) std::cout << ' ';\n"
        "        std::cout << a[i];\n"
        "    }\n"
        "    return 0;\n"
        "}"
    ),
    144: (
        "#include <iostream>\n"
        "int main() {\n"
        "    int n, s = 0; std::cin >> n;\n"
        "    std::cout << 0;\n"
        "    for (int i = 0; i < n; i++) {\n"
        "        int x; std::cin >> x;\n"
        "        s += x;\n"
        "        std::cout << ' ' << s;\n"
        "    }\n"
        "    return 0;\n"
        "}"
    ),
}
