"""Curated C++ debug buggy/fixed pairs for v192 expansion debug slots."""

from __future__ import annotations

from typing import Dict, Tuple

CPP_DEBUG_PAIRS_129_192: Dict[int, Tuple[str, str]] = {
    131: (
        # BUG: floating-point average (Python / transfer)
        "#include <iostream>\n"
        "int main() {\n"
        "    int n, total = 0, x;\n"
        "    std::cin >> n;\n"
        "    for (int i = 0; i < n; i++) {\n"
        "        std::cin >> x;\n"
        "        total += x;\n"
        "    }\n"
        "    double avg = static_cast<double>(total) / n;\n"
        "    std::cout << avg;\n"
        "    return 0;\n"
        "}",
        # FIX: integer division
        "#include <iostream>\n"
        "int main() {\n"
        "    int n, total = 0, x;\n"
        "    std::cin >> n;\n"
        "    for (int i = 0; i < n; i++) {\n"
        "        std::cin >> x;\n"
        "        total += x;\n"
        "    }\n"
        "    std::cout << total / n;\n"
        "    return 0;\n"
        "}",
    ),
    135: (
        # BUG: C++ chain comparison (a < x) < b — not the same as Python chain
        "#include <iostream>\n"
        "int main() {\n"
        "    int a, b, x;\n"
        "    std::cin >> a >> b >> x;\n"
        "    if (a < x < b) std::cout << \"yes\";\n"
        "    else std::cout << \"no\";\n"
        "    return 0;\n"
        "}",
        # FIX: explicit inclusive bounds
        "#include <iostream>\n"
        "int main() {\n"
        "    int a, b, x;\n"
        "    std::cin >> a >> b >> x;\n"
        "    std::cout << (a <= x && x <= b ? \"yes\" : \"no\");\n"
        "    return 0;\n"
        "}",
    ),
    139: (
        # BUG: bounded loop + counts zeros
        "#include <iostream>\n"
        "int main() {\n"
        "    int n, total = 0, x;\n"
        "    std::cin >> n;\n"
        "    for (int i = 0; i <= n; i++) {\n"
        "        std::cin >> x;\n"
        "        if (x >= 0) total += x;\n"
        "    }\n"
        "    std::cout << total;\n"
        "    return 0;\n"
        "}",
        # FIX: read until 0, sum only positive
        "#include <iostream>\n"
        "int main() {\n"
        "    int total = 0, x;\n"
        "    std::cin >> x;\n"
        "    while (x != 0) {\n"
        "        if (x > 0) total += x;\n"
        "        std::cin >> x;\n"
        "    }\n"
        "    std::cout << total;\n"
        "    return 0;\n"
        "}",
    ),
    143: (
        # BUG: prints in input order
        "#include <iostream>\n"
        "int main() {\n"
        "    int n, x;\n"
        "    std::cin >> n;\n"
        "    for (int i = 0; i < n; i++) {\n"
        "        std::cin >> x;\n"
        "        if (i) std::cout << ' ';\n"
        "        std::cout << x;\n"
        "    }\n"
        "    return 0;\n"
        "}",
        # FIX: reverse order
        "#include <iostream>\n"
        "int main() {\n"
        "    int n;\n"
        "    std::cin >> n;\n"
        "    int a[1000];\n"
        "    for (int i = 0; i < n; i++) std::cin >> a[i];\n"
        "    for (int i = n - 1; i >= 0; i--) {\n"
        "        if (i != n - 1) std::cout << ' ';\n"
        "        std::cout << a[i];\n"
        "    }\n"
        "    return 0;\n"
        "}",
    ),
    147: (
        # BUG: 1-based index / 0 for not found
        "#include <iostream>\n"
        "#include <string>\n"
        "int main() {\n"
        "    std::string s, c;\n"
        "    std::getline(std::cin, s);\n"
        "    std::getline(std::cin, c);\n"
        "    size_t p = s.find(c);\n"
        "    if (p == std::string::npos) std::cout << 0;\n"
        "    else std::cout << static_cast<int>(p) + 1;\n"
        "    return 0;\n"
        "}",
        # FIX: 0-based, -1 if missing
        "#include <iostream>\n"
        "#include <string>\n"
        "int main() {\n"
        "    std::string s, c;\n"
        "    std::getline(std::cin, s);\n"
        "    std::getline(std::cin, c);\n"
        "    size_t p = s.find(c);\n"
        "    if (p == std::string::npos) std::cout << -1;\n"
        "    else std::cout << static_cast<int>(p);\n"
        "    return 0;\n"
        "}",
    ),
    151: (
        # BUG: result trapped in block scope (scope_block)
        "#include <iostream>\n"
        "long long fact(int n) {\n"
        "    if (n <= 1) {\n"
        "        long long result = 1;\n"
        "    } else {\n"
        "        long long result = n * fact(n - 1);\n"
        "    }\n"
        "    return 0;\n"
        "}\n"
        "int main() {\n"
        "    int n;\n"
        "    std::cin >> n;\n"
        "    std::cout << fact(n);\n"
        "    return 0;\n"
        "}",
        # FIX: proper return
        "#include <iostream>\n"
        "long long fact(int n) {\n"
        "    if (n <= 1) return 1;\n"
        "    return n * fact(n - 1);\n"
        "}\n"
        "int main() {\n"
        "    int n;\n"
        "    std::cin >> n;\n"
        "    std::cout << fact(n);\n"
        "    return 0;\n"
        "}",
    ),
    155: (
        # BUG: base case n == 1 only
        "#include <iostream>\n"
        "long long fact(int n) {\n"
        "    if (n == 1) return 1;\n"
        "    return n * fact(n - 1);\n"
        "}\n"
        "int main() {\n"
        "    int n;\n"
        "    std::cin >> n;\n"
        "    std::cout << fact(n);\n"
        "    return 0;\n"
        "}",
        # FIX: base case n <= 1
        "#include <iostream>\n"
        "long long fact(int n) {\n"
        "    if (n <= 1) return 1;\n"
        "    return n * fact(n - 1);\n"
        "}\n"
        "int main() {\n"
        "    int n;\n"
        "    std::cin >> n;\n"
        "    std::cout << fact(n);\n"
        "    return 0;\n"
        "}",
    ),
    159: (
        # BUG: 1-based array layout (Pascal-style transfer)
        "#include <iostream>\n"
        "#include <vector>\n"
        "int main() {\n"
        "    int n;\n"
        "    std::cin >> n;\n"
        "    std::vector<int> a(n + 1);\n"
        "    for (int i = 1; i <= n; i++) std::cin >> a[i];\n"
        "    for (int i = 1; i < n; i++)\n"
        "        for (int j = 1; j <= n - i; j++)\n"
        "            if (a[j] > a[j + 1]) std::swap(a[j], a[j + 1]);\n"
        "    for (int i = 1; i <= n; i++) {\n"
        "        if (i > 1) std::cout << ' ';\n"
        "        std::cout << a[i];\n"
        "    }\n"
        "    return 0;\n"
        "}",
        # FIX: standard 0-based bubble sort
        "#include <iostream>\n"
        "#include <vector>\n"
        "int main() {\n"
        "    int n;\n"
        "    std::cin >> n;\n"
        "    std::vector<int> a(n);\n"
        "    for (int i = 0; i < n; i++) std::cin >> a[i];\n"
        "    for (int i = 0; i < n; i++)\n"
        "        for (int j = 0; j < n - 1 - i; j++)\n"
        "            if (a[j] > a[j + 1]) std::swap(a[j], a[j + 1]);\n"
        "    for (int i = 0; i < n; i++) {\n"
        "        if (i) std::cout << ' ';\n"
        "        std::cout << a[i];\n"
        "    }\n"
        "    return 0;\n"
        "}",
    ),
    163: (
        # BUG: truncate average (round_semantics / AFCC)
        "#include <iostream>\n"
        "#include <vector>\n"
        "int main() {\n"
        "    int n;\n"
        "    std::cin >> n;\n"
        "    std::vector<int> a(n);\n"
        "    long long total = 0;\n"
        "    for (int i = 0; i < n; i++) {\n"
        "        std::cin >> a[i];\n"
        "        total += a[i];\n"
        "    }\n"
        "    std::cout << static_cast<int>(total / static_cast<double>(n));\n"
        "    return 0;\n"
        "}",
        # FIX: std::round
        "#include <iostream>\n"
        "#include <cmath>\n"
        "#include <vector>\n"
        "int main() {\n"
        "    int n;\n"
        "    std::cin >> n;\n"
        "    std::vector<int> a(n);\n"
        "    long long total = 0;\n"
        "    for (int i = 0; i < n; i++) {\n"
        "        std::cin >> a[i];\n"
        "        total += a[i];\n"
        "    }\n"
        "    std::cout << static_cast<int>(std::round(total / static_cast<double>(n)));\n"
        "    return 0;\n"
        "}",
    ),
    167: (
        # BUG: -1 when key missing
        "#include <iostream>\n"
        "#include <string>\n"
        "#include <unordered_map>\n"
        "int main() {\n"
        "    int n;\n"
        "    std::cin >> n;\n"
        "    std::unordered_map<std::string, int> freq;\n"
        "    for (int i = 0; i < n; i++) {\n"
        "        std::string key;\n"
        "        std::cin >> key;\n"
        "        freq[key]++;\n"
        "    }\n"
        "    std::string q;\n"
        "    std::cin >> q;\n"
        "    auto it = freq.find(q);\n"
        "    std::cout << (it == freq.end() ? -1 : it->second);\n"
        "    return 0;\n"
        "}",
        # FIX: 0 when missing
        "#include <iostream>\n"
        "#include <string>\n"
        "#include <unordered_map>\n"
        "int main() {\n"
        "    int n;\n"
        "    std::cin >> n;\n"
        "    std::unordered_map<std::string, int> freq;\n"
        "    for (int i = 0; i < n; i++) {\n"
        "        std::string key;\n"
        "        std::cin >> key;\n"
        "        freq[key]++;\n"
        "    }\n"
        "    std::string q;\n"
        "    std::cin >> q;\n"
        "    auto it = freq.find(q);\n"
        "    std::cout << (it == freq.end() ? 0 : it->second);\n"
        "    return 0;\n"
        "}",
    ),
    171: (
        # BUG: binary-ish read / no empty-line skip
        "#include <iostream>\n"
        "#include <string>\n"
        "int main() {\n"
        "    std::string line;\n"
        "    int total = 0;\n"
        "    while (std::getline(std::cin, line)) {\n"
        "        const auto comma = line.find(',');\n"
        "        total += std::stoi(line.substr(comma + 1));\n"
        "    }\n"
        "    std::cout << total;\n"
        "    return 0;\n"
        "}",
        # FIX: skip blank lines (text mode)
        "#include <iostream>\n"
        "#include <string>\n"
        "int main() {\n"
        "    std::string line;\n"
        "    int total = 0;\n"
        "    while (std::getline(std::cin, line)) {\n"
        "        if (line.empty()) continue;\n"
        "        const auto comma = line.find(',');\n"
        "        total += std::stoi(line.substr(comma + 1));\n"
        "    }\n"
        "    std::cout << total;\n"
        "    return 0;\n"
        "}",
    ),
    175: (
        # BUG: pop from empty stack
        "#include <iostream>\n"
        "#include <string>\n"
        "#include <stack>\n"
        "int main() {\n"
        "    std::string s;\n"
        "    std::getline(std::cin, s);\n"
        "    std::stack<char> st;\n"
        "    for (char ch : s) {\n"
        "        if (ch == '(' || ch == '[' || ch == '{') st.push(ch);\n"
        "        else {\n"
        "            char open = st.top();\n"
        "            st.pop();\n"
        "            if ((ch == ')' && open != '(') || (ch == ']' && open != '[') ||\n"
        "                (ch == '}' && open != '{')) {\n"
        "                std::cout << \"no\";\n"
        "                return 0;\n"
        "            }\n"
        "        }\n"
        "    }\n"
        "    std::cout << (st.empty() ? \"yes\" : \"no\");\n"
        "    return 0;\n"
        "}",
        # FIX: guard empty stack
        "#include <iostream>\n"
        "#include <string>\n"
        "#include <stack>\n"
        "int main() {\n"
        "    std::string s;\n"
        "    std::getline(std::cin, s);\n"
        "    std::stack<char> st;\n"
        "    for (char ch : s) {\n"
        "        if (ch == '(' || ch == '[' || ch == '{') st.push(ch);\n"
        "        else {\n"
        "            if (st.empty()) {\n"
        "                std::cout << \"no\";\n"
        "                return 0;\n"
        "            }\n"
        "            char open = st.top();\n"
        "            st.pop();\n"
        "            if ((ch == ')' && open != '(') || (ch == ']' && open != '[') ||\n"
        "                (ch == '}' && open != '{')) {\n"
        "                std::cout << \"no\";\n"
        "                return 0;\n"
        "            }\n"
        "        }\n"
        "    }\n"
        "    std::cout << (st.empty() ? \"yes\" : \"no\");\n"
        "    return 0;\n"
        "}",
    ),
    179: (
        # BUG: skips index 0 when searching
        "#include <iostream>\n"
        "#include <vector>\n"
        "int main() {\n"
        "    int n, v;\n"
        "    std::cin >> n;\n"
        "    std::vector<int> a(n);\n"
        "    for (int i = 0; i < n; i++) std::cin >> a[i];\n"
        "    std::cin >> v;\n"
        "    for (int i = 1; i < n; i++) {\n"
        "        if (a[i] == v) {\n"
        "            a.erase(a.begin() + i);\n"
        "            break;\n"
        "        }\n"
        "    }\n"
        "    for (int i = 0; i < static_cast<int>(a.size()); i++) {\n"
        "        if (i) std::cout << ' ';\n"
        "        std::cout << a[i];\n"
        "    }\n"
        "    return 0;\n"
        "}",
        # FIX: remove first occurrence from index 0
        "#include <iostream>\n"
        "#include <vector>\n"
        "int main() {\n"
        "    int n, v;\n"
        "    std::cin >> n;\n"
        "    std::vector<int> a(n);\n"
        "    for (int i = 0; i < n; i++) std::cin >> a[i];\n"
        "    std::cin >> v;\n"
        "    for (int i = 0; i < n; i++) {\n"
        "        if (a[i] == v) {\n"
        "            a.erase(a.begin() + i);\n"
        "            break;\n"
        "        }\n"
        "    }\n"
        "    for (int i = 0; i < static_cast<int>(a.size()); i++) {\n"
        "        if (i) std::cout << ' ';\n"
        "        std::cout << a[i];\n"
        "    }\n"
        "    return 0;\n"
        "}",
    ),
    183: (
        # BUG: 1-based graph (Pascal-style)
        "#include <iostream>\n"
        "#include <vector>\n"
        "using namespace std;\n"
        "vector<vector<int>> g;\n"
        "vector<bool> used;\n"
        "void dfs(int u) {\n"
        "    used[u] = true;\n"
        "    cout << u << ' ';\n"
        "    for (int v : g[u]) if (!used[v]) dfs(v);\n"
        "}\n"
        "int main() {\n"
        "    int n, m;\n"
        "    cin >> n >> m;\n"
        "    g.assign(n + 1, {});\n"
        "    used.assign(n + 1, false);\n"
        "    for (int i = 0; i < m; i++) {\n"
        "        int u, v;\n"
        "        cin >> u >> v;\n"
        "        g[u + 1].push_back(v + 1);\n"
        "        g[v + 1].push_back(u + 1);\n"
        "    }\n"
        "    dfs(1);\n"
        "    return 0;\n"
        "}",
        # FIX: 0-based vertices, start from 0
        "#include <iostream>\n"
        "#include <vector>\n"
        "using namespace std;\n"
        "vector<vector<int>> g;\n"
        "vector<bool> used;\n"
        "void dfs(int u) {\n"
        "    used[u] = true;\n"
        "    cout << u << ' ';\n"
        "    for (int v : g[u]) if (!used[v]) dfs(v);\n"
        "}\n"
        "int main() {\n"
        "    int n, m;\n"
        "    cin >> n >> m;\n"
        "    g.assign(n, {});\n"
        "    used.assign(n, false);\n"
        "    for (int i = 0; i < m; i++) {\n"
        "        int u, v;\n"
        "        cin >> u >> v;\n"
        "        g[u].push_back(v);\n"
        "        g[v].push_back(u);\n"
        "    }\n"
        "    dfs(0);\n"
        "    return 0;\n"
        "}",
    ),
    187: (
        # BUG: balance may go negative
        "#include <iostream>\n"
        "#include <sstream>\n"
        "#include <string>\n"
        "#include <vector>\n"
        "class BankAccount {\n"
        "public:\n"
        "    int balance = 0;\n"
        "    explicit BankAccount(int b) : balance(b) {}\n"
        "    void withdraw(int x) { balance -= x; }\n"
        "};\n"
        "int main() {\n"
        "    std::string line;\n"
        "    std::getline(std::cin, line);\n"
        "    std::istringstream ss(line);\n"
        "    std::vector<int> parts;\n"
        "    int x;\n"
        "    while (ss >> x) parts.push_back(x);\n"
        "    BankAccount acc(parts[0]);\n"
        "    for (size_t i = 1; i < parts.size(); i++) acc.withdraw(parts[i]);\n"
        "    std::cout << acc.balance;\n"
        "    return 0;\n"
        "}",
        # FIX: clamp at zero
        "#include <iostream>\n"
        "#include <sstream>\n"
        "#include <string>\n"
        "#include <vector>\n"
        "class BankAccount {\n"
        "public:\n"
        "    int balance = 0;\n"
        "    explicit BankAccount(int b) : balance(b) {}\n"
        "    void withdraw(int x) {\n"
        "        balance -= x;\n"
        "        if (balance < 0) balance = 0;\n"
        "    }\n"
        "};\n"
        "int main() {\n"
        "    std::string line;\n"
        "    std::getline(std::cin, line);\n"
        "    std::istringstream ss(line);\n"
        "    std::vector<int> parts;\n"
        "    int x;\n"
        "    while (ss >> x) parts.push_back(x);\n"
        "    BankAccount acc(parts[0]);\n"
        "    for (size_t i = 1; i < parts.size(); i++) acc.withdraw(parts[i]);\n"
        "    std::cout << acc.balance;\n"
        "    return 0;\n"
        "}",
    ),
    191: (
        # BUG: no virtual — base speak() always called via pointer
        "#include <iostream>\n"
        "#include <string>\n"
        "struct Animal {\n"
        "    std::string speak() { return \"?\"; }\n"
        "};\n"
        "struct Dog : Animal {\n"
        "    std::string speak() { return \"woof\"; }\n"
        "};\n"
        "struct Cat : Animal {\n"
        "    std::string speak() { return \"meow\"; }\n"
        "};\n"
        "int main() {\n"
        "    int n;\n"
        "    std::cin >> n;\n"
        "    for (int i = 0; i < n; i++) {\n"
        "        std::string kind;\n"
        "        std::cin >> kind;\n"
        "        Animal* a = (kind == \"Dog\") ? new Dog() : new Cat();\n"
        "        std::cout << a->speak();\n"
        "        if (i + 1 < n) std::cout << ' ';\n"
        "        delete a;\n"
        "    }\n"
        "    return 0;\n"
        "}",
        # FIX: virtual dispatch
        "#include <iostream>\n"
        "#include <string>\n"
        "struct Animal {\n"
        "    virtual std::string speak() { return \"\"; }\n"
        "    virtual ~Animal() = default;\n"
        "};\n"
        "struct Dog : Animal {\n"
        "    std::string speak() override { return \"woof\"; }\n"
        "};\n"
        "struct Cat : Animal {\n"
        "    std::string speak() override { return \"meow\"; }\n"
        "};\n"
        "int main() {\n"
        "    int n;\n"
        "    std::cin >> n;\n"
        "    for (int i = 0; i < n; i++) {\n"
        "        std::string kind;\n"
        "        std::cin >> kind;\n"
        "        Animal* a = (kind == \"Dog\") ? new Dog() : new Cat();\n"
        "        std::cout << a->speak();\n"
        "        if (i + 1 < n) std::cout << ' ';\n"
        "        delete a;\n"
        "    }\n"
        "    return 0;\n"
        "}",
    ),
}
