"""Expected concept ids for C# Course v1 tasks."""

from __future__ import annotations

from application.curriculum.cpp.catalog.cpp_v311_expected_concepts import CHAPTER_DEFAULTS

SLOT_OVERRIDES: dict[str, list[str]] = {
    "cs_001": ["program_entry", "import_dependency", "stdout_write"],
    "cs_002": ["typed_declaration", "stdout_write", "assignment"],
    "cs_003": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops"],
    "cs_004": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops"],
    "cs_005": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops"],
    "cs_006": ["typed_declaration", "stdout_write", "assignment"],
    "cs_007": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops"],
    "cs_008": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops"],
    "cs_009": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops"],
    "cs_010": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops"],
    "cs_011": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops"],
    "cs_012": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops"],
    "cs_013": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "string_sequence"],
    "cs_014": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "string_sequence"],
    "cs_015": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "string_sequence"],
    "cs_016": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "string_sequence"],
    "cs_017": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "string_sequence"],
    "cs_018": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "string_sequence"],
    "cs_019": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "string_sequence"],
    "cs_020": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "string_sequence"],
    "cs_021": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "string_sequence"],
    "cs_022": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "string_sequence"],
    "cs_023": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "string_sequence"],
    "cs_024": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "string_sequence"],
    "cs_025": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "conditional_expression", "string_sequence"],
    "cs_026": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "conditional_expression", "string_sequence"],
    "cs_027": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "conditional_expression", "string_sequence"],
    "cs_028": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "conditional_expression", "string_sequence"],
    "cs_029": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "conditional_expression", "string_sequence"],
    "cs_030": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "conditional_expression", "string_sequence"],
    "cs_031": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "conditional_expression", "string_sequence"],
    "cs_032": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "conditional_expression", "string_sequence"],
    "cs_033": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "conditional_expression", "indexed_sequence", "string_sequence"],
    "cs_034": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "conditional_expression", "string_sequence"],
    "cs_035": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "conditional_expression", "string_sequence"],
    "cs_036": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "conditional_expression", "string_sequence"],
    "cs_037": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "conditional_expression", "string_sequence"],
    "cs_038": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "conditional_expression", "indexed_sequence", "string_sequence"],
    "cs_039": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "simple_branch", "conditional_expression", "string_sequence"],
    "cs_040": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "multi_branch", "switch_selection", "string_sequence", "lambda"],
    "cs_041": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "multi_branch", "switch_selection", "string_sequence", "lambda"],
    "cs_042": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "multi_branch", "switch_selection", "string_sequence", "lambda"],
    "cs_043": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "simple_branch", "conditional_expression", "string_sequence"],
    "cs_044": ["switch", "break", "break", "break", "break"],
    "cs_045": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "multi_branch", "switch_selection", "string_sequence", "lambda"],
    "cs_046": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "simple_branch", "conditional_expression", "string_sequence"],
    "cs_047": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "simple_branch", "conditional_expression", "string_sequence"],
    "cs_048": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "simple_branch", "conditional_expression", "string_sequence"],
    "cs_049": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "multi_branch", "switch_selection", "string_sequence", "lambda"],
    "cs_050": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "multi_branch", "switch_selection", "string_sequence", "lambda"],
    "cs_051": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "string_sequence"],
    "cs_052": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "string_sequence"],
    "cs_053": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "string_sequence"],
    "cs_054": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "string_sequence"],
    "cs_055": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "string_sequence"],
    "cs_056": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "string_sequence"],
    "cs_057": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "string_sequence"],
    "cs_058": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "string_sequence"],
    "cs_059": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "string_sequence"],
    "cs_060": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "string_sequence"],
    "cs_061": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "string_sequence"],
    "cs_062": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "string_sequence"],
    "cs_063": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "pre_condition_loop", "string_sequence"],
    "cs_064": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "pre_condition_loop", "string_sequence"],
    "cs_065": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "string_sequence"],
    "cs_066": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "string_sequence"],
    "cs_067": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "string_sequence"],
    "cs_068": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "string_sequence"],
    "cs_069": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "string_sequence"],
    "cs_070": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "string_sequence"],
    "cs_071": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "string_sequence"],
    "cs_072": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "string_sequence"],
    "cs_073": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "string_sequence"],
    "cs_074": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "string_sequence"],
    "cs_075": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "string_sequence"],
    "cs_076": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "string_sequence"],
    "cs_077": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "string_sequence"],
    "cs_078": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "string_sequence"],
    "cs_079": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "indexed_sequence", "collection_iteration", "string_sequence", "key_value_map"],
    "cs_080": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "indexed_sequence", "collection_iteration", "string_sequence", "key_value_map"],
    "cs_081": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "indexed_sequence", "collection_iteration", "string_sequence", "key_value_map"],
    "cs_082": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "indexed_sequence", "collection_iteration", "string_sequence", "key_value_map"],
    "cs_083": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "indexed_sequence", "collection_iteration", "string_sequence", "key_value_map"],
    "cs_084": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "indexed_sequence", "collection_iteration", "string_sequence", "key_value_map"],
    "cs_085": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "indexed_sequence", "collection_iteration", "string_sequence", "key_value_map"],
    "cs_086": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "indexed_sequence", "collection_iteration", "string_sequence", "key_value_map"],
    "cs_087": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "indexed_sequence", "collection_iteration", "string_sequence", "key_value_map"],
    "cs_088": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "indexed_sequence", "collection_iteration", "string_sequence", "key_value_map"],
    "cs_089": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "indexed_sequence", "collection_iteration", "string_sequence", "key_value_map"],
    "cs_090": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "indexed_sequence", "collection_iteration", "string_sequence", "key_value_map"],
    "cs_091": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "indexed_sequence", "collection_iteration", "string_sequence", "key_value_map"],
    "cs_092": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "indexed_sequence", "collection_iteration", "string_sequence", "key_value_map"],
    "cs_093": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "indexed_sequence", "collection_iteration", "string_sequence", "key_value_map"],
    "cs_094": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "indexed_sequence", "collection_iteration", "string_sequence", "key_value_map"],
    "cs_095": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "indexed_sequence", "collection_iteration", "dynamic_array", "string_sequence"],
    "cs_096": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "indexed_sequence", "collection_iteration", "dynamic_array", "string_sequence"],
    "cs_097": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "indexed_sequence", "collection_iteration", "dynamic_array", "string_sequence"],
    "cs_098": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "indexed_sequence", "collection_iteration", "dynamic_array", "string_sequence"],
    "cs_099": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "indexed_sequence", "collection_iteration", "dynamic_array", "string_sequence"],
    "cs_100": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "indexed_sequence", "collection_iteration", "dynamic_array", "string_sequence"],
    "cs_101": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "indexed_sequence", "collection_iteration", "dynamic_array", "string_sequence"],
    "cs_102": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "indexed_sequence", "collection_iteration", "dynamic_array", "string_sequence"],
    "cs_103": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "indexed_sequence", "collection_iteration", "dynamic_array", "string_sequence"],
    "cs_104": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "indexed_sequence", "collection_iteration", "dynamic_array", "string_sequence"],
    "cs_105": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "indexed_sequence", "collection_iteration", "dynamic_array", "string_sequence"],
    "cs_106": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "indexed_sequence", "collection_iteration", "dynamic_array", "string_sequence"],
    "cs_107": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "indexed_sequence", "collection_iteration", "dynamic_array", "string_sequence"],
    "cs_108": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "indexed_sequence", "collection_iteration", "dynamic_array", "string_sequence"],
    "cs_109": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "collection_iteration", "string_sequence"],
    "cs_110": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "collection_iteration", "string_sequence"],
    "cs_111": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "collection_iteration", "string_sequence"],
    "cs_112": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "collection_iteration", "string_sequence"],
    "cs_113": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "collection_iteration", "string_sequence"],
    "cs_114": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "collection_iteration", "string_sequence"],
    "cs_115": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "collection_iteration", "string_sequence"],
    "cs_116": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "collection_iteration", "string_sequence"],
    "cs_117": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "collection_iteration", "string_sequence"],
    "cs_118": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "collection_iteration", "string_sequence"],
    "cs_119": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "collection_iteration", "string_sequence"],
    "cs_120": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "collection_iteration", "string_sequence"],
    "cs_121": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "collection_iteration", "string_sequence"],
    "cs_122": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "collection_iteration", "string_sequence"],
    "cs_123": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "string_sequence", "function_definition", "return_flow", "parameter_passing", "recursion"],
    "cs_124": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "string_sequence", "function_definition", "return_flow", "parameter_passing", "recursion"],
    "cs_125": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "string_sequence", "function_definition", "return_flow", "parameter_passing", "recursion"],
    "cs_126": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "string_sequence", "function_definition", "return_flow", "parameter_passing", "recursion"],
    "cs_127": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "string_sequence", "function_definition", "return_flow", "parameter_passing", "recursion"],
    "cs_128": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "string_sequence", "function_definition", "return_flow", "parameter_passing", "recursion"],
    "cs_129": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "string_sequence", "function_definition", "return_flow", "parameter_passing", "recursion"],
    "cs_130": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "string_sequence", "function_definition", "return_flow", "parameter_passing", "recursion"],
    "cs_131": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "string_sequence", "function_definition", "return_flow", "parameter_passing", "recursion"],
    "cs_132": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "string_sequence", "function_definition", "return_flow", "parameter_passing", "recursion"],
    "cs_133": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "string_sequence", "function_definition", "return_flow", "parameter_passing", "recursion"],
    "cs_134": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "string_sequence", "function_definition", "return_flow", "parameter_passing", "recursion"],
    "cs_135": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "string_sequence", "function_definition", "return_flow", "parameter_passing", "recursion"],
    "cs_136": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "string_sequence", "function_definition", "return_flow", "parameter_passing", "recursion"],
    "cs_137": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "string_sequence", "function_definition", "return_flow", "parameter_passing", "recursion"],
    "cs_138": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "string_sequence", "function_definition", "return_flow", "parameter_passing", "recursion"],
    "cs_139": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "string_sequence", "function_definition", "return_flow", "parameter_passing", "recursion"],
    "cs_140": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "string_sequence", "function_definition", "return_flow", "parameter_passing", "recursion"],
    "cs_141": ["typed_declaration", "stdout_write", "arithmetic_ops", "conditional_expression", "function_definition", "return_flow", "parameter_passing", "recursion"],
    "cs_142": ["typed_declaration", "stdout_write", "arithmetic_ops", "conditional_expression", "function_definition", "return_flow", "parameter_passing", "recursion"],
    "cs_143": ["typed_declaration", "stdout_write", "arithmetic_ops", "conditional_expression", "function_definition", "return_flow", "parameter_passing", "recursion"],
    "cs_144": ["typed_declaration", "stdout_write", "arithmetic_ops", "conditional_expression", "function_definition", "return_flow", "parameter_passing", "recursion"],
    "cs_145": ["typed_declaration", "stdout_write", "arithmetic_ops", "conditional_expression", "function_definition", "return_flow", "parameter_passing", "recursion"],
    "cs_146": ["typed_declaration", "stdout_write", "arithmetic_ops", "conditional_expression", "function_definition", "return_flow", "parameter_passing", "recursion"],
    "cs_147": ["typed_declaration", "stdout_write", "arithmetic_ops", "conditional_expression", "function_definition", "return_flow", "parameter_passing", "recursion"],
    "cs_148": ["typed_declaration", "stdout_write", "arithmetic_ops", "conditional_expression", "function_definition", "return_flow", "parameter_passing", "recursion"],
    "cs_149": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "dynamic_array", "filter_select", "lambda"],
    "cs_150": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "dynamic_array", "filter_select", "lambda"],
    "cs_151": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "dynamic_array", "filter_select", "lambda"],
    "cs_152": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "dynamic_array", "filter_select", "lambda"],
    "cs_153": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "dynamic_array", "filter_select", "lambda"],
    "cs_154": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "dynamic_array", "filter_select", "lambda"],
    "cs_155": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "dynamic_array", "filter_select", "lambda"],
    "cs_156": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "dynamic_array", "filter_select", "lambda"],
    "cs_157": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "dynamic_array", "filter_select", "lambda"],
    "cs_158": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "dynamic_array", "filter_select", "lambda"],
    "cs_159": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "dynamic_array", "filter_select", "lambda"],
    "cs_160": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "dynamic_array", "filter_select", "lambda"],
    "cs_161": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "dynamic_array", "filter_select", "lambda"],
    "cs_162": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "dynamic_array", "filter_select", "lambda"],
    "cs_163": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "dynamic_array", "filter_select", "lambda"],
    "cs_164": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "dynamic_array", "filter_select", "lambda"],
    "cs_165": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "dynamic_array", "filter_select", "lambda"],
    "cs_166": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "dynamic_array", "filter_select", "lambda"],
    "cs_167": ["typed_declaration", "stdout_write", "assignment", "indexed_sequence", "dynamic_array", "string_sequence"],
    "cs_168": ["typed_declaration", "stdout_write", "assignment", "indexed_sequence", "dynamic_array", "string_sequence"],
    "cs_169": ["typed_declaration", "stdout_write", "assignment", "indexed_sequence", "dynamic_array", "string_sequence"],
    "cs_170": ["typed_declaration", "stdout_write", "assignment", "indexed_sequence", "dynamic_array", "string_sequence"],
    "cs_171": ["typed_declaration", "stdout_write", "assignment", "indexed_sequence", "dynamic_array", "string_sequence"],
    "cs_172": ["typed_declaration", "stdout_write", "assignment", "indexed_sequence", "dynamic_array", "string_sequence"],
    "cs_173": ["typed_declaration", "stdout_write", "assignment", "indexed_sequence", "dynamic_array", "string_sequence"],
    "cs_174": ["typed_declaration", "stdout_write", "assignment", "indexed_sequence", "dynamic_array", "string_sequence"],
    "cs_175": ["typed_declaration", "stdout_write", "assignment", "indexed_sequence", "dynamic_array", "string_sequence"],
    "cs_176": ["typed_declaration", "stdout_write", "assignment", "indexed_sequence", "dynamic_array", "string_sequence"],
    "cs_177": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "dynamic_array", "filter_select", "lambda"],
    "cs_178": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "dynamic_array", "filter_select", "lambda"],
    "cs_179": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "dynamic_array", "filter_select", "lambda"],
    "cs_180": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "dynamic_array", "filter_select", "lambda"],
    "cs_181": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "conditional_expression", "indexed_sequence", "collection_iteration", "string_sequence", "key_value_map"],
    "cs_182": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "conditional_expression", "indexed_sequence", "collection_iteration", "string_sequence", "key_value_map"],
    "cs_183": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "conditional_expression", "indexed_sequence", "collection_iteration", "string_sequence", "key_value_map"],
    "cs_184": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "conditional_expression", "indexed_sequence", "collection_iteration", "string_sequence", "key_value_map"],
    "cs_185": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "dynamic_array", "filter_select", "lambda"],
    "cs_186": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "dynamic_array", "filter_select", "lambda"],
    "cs_187": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "dynamic_array", "filter_select", "lambda"],
    "cs_188": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "conditional_expression", "indexed_sequence", "collection_iteration", "string_sequence", "key_value_map"],
    "cs_189": ["typed_declaration", "stdout_write", "assignment", "string_sequence", "file_read", "file_write"],
    "cs_190": ["typed_declaration", "stdout_write", "assignment", "string_sequence", "file_read", "file_write"],
    "cs_191": ["typed_declaration", "stdout_write", "assignment", "string_sequence", "file_read", "file_write"],
    "cs_192": ["typed_declaration", "stdout_write", "assignment", "string_sequence", "file_read", "file_write"],
    "cs_193": ["typed_declaration", "stdout_write", "assignment", "string_sequence", "file_read", "file_write"],
    "cs_194": ["typed_declaration", "stdout_write", "assignment", "string_sequence", "file_read", "file_write"],
    "cs_195": ["typed_declaration", "stdout_write", "assignment", "string_sequence", "file_read", "file_write"],
    "cs_196": ["typed_declaration", "stdout_write", "assignment", "string_sequence", "file_read", "file_write"],
    "cs_197": ["typed_declaration", "stdout_write", "assignment", "string_sequence", "file_read", "file_write"],
    "cs_198": ["typed_declaration", "stdout_write", "assignment", "string_sequence", "file_read", "file_write"],
    "cs_199": ["import_dependency", "module_namespace", "typed_declaration", "stdout_write", "arithmetic_ops", "function_definition", "parameter_passing", "recursion", "lambda", "class_type"],
    "cs_200": ["import_dependency", "module_namespace", "typed_declaration", "stdout_write", "arithmetic_ops", "function_definition", "parameter_passing", "recursion", "lambda", "class_type"],
    "cs_201": ["import_dependency", "module_namespace", "typed_declaration", "stdout_write", "arithmetic_ops", "function_definition", "parameter_passing", "recursion", "lambda", "class_type"],
    "cs_202": ["import_dependency", "module_namespace", "typed_declaration", "stdout_write", "arithmetic_ops", "function_definition", "parameter_passing", "recursion", "lambda", "class_type"],
    "cs_203": ["import_dependency", "module_namespace", "typed_declaration", "stdout_write", "arithmetic_ops", "function_definition", "parameter_passing", "recursion", "lambda", "class_type"],
    "cs_204": ["import_dependency", "module_namespace", "typed_declaration", "stdout_write", "arithmetic_ops", "function_definition", "parameter_passing", "recursion", "lambda", "class_type"],
    "cs_205": ["import_dependency", "module_namespace", "typed_declaration", "stdout_write", "arithmetic_ops", "function_definition", "parameter_passing", "recursion", "lambda", "class_type"],
    "cs_206": ["import_dependency", "module_namespace", "typed_declaration", "stdout_write", "arithmetic_ops", "function_definition", "parameter_passing", "recursion", "lambda", "class_type"],
    "cs_207": ["typed_declaration", "stdout_write", "assignment", "stack_queue"],
    "cs_208": ["typed_declaration", "stdout_write", "assignment", "stack_queue"],
    "cs_209": ["typed_declaration", "stdout_write", "assignment", "stack_queue"],
    "cs_210": ["typed_declaration", "stdout_write", "assignment", "stack_queue"],
    "cs_211": ["typed_declaration", "stdout_write", "assignment", "linked_node", "class_type"],
    "cs_212": ["typed_declaration", "stdout_write", "assignment", "linked_node", "class_type"],
    "cs_213": ["typed_declaration", "stdout_write", "assignment", "linked_node", "class_type"],
    "cs_214": ["typed_declaration", "stdout_write", "assignment", "linked_node", "class_type"],
    "cs_215": ["typed_declaration", "stdout_write", "assignment", "linked_node", "class_type"],
    "cs_216": ["typed_declaration", "stdout_write", "assignment", "linked_node", "class_type"],
    "cs_217": ["typed_declaration", "stdout_write", "assignment", "indexed_sequence", "dynamic_array", "graph_edges"],
    "cs_218": ["typed_declaration", "stdout_write", "assignment", "indexed_sequence", "dynamic_array", "graph_edges"],
    "cs_219": ["typed_declaration", "stdout_write", "assignment", "indexed_sequence", "dynamic_array", "graph_edges"],
    "cs_220": ["typed_declaration", "stdout_write", "assignment", "indexed_sequence", "dynamic_array", "graph_edges"],
    "cs_221": ["typed_declaration", "stdout_write", "assignment", "indexed_sequence", "dynamic_array", "graph_edges"],
    "cs_222": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "dynamic_array", "filter_select", "lambda"],
    "cs_223": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "dynamic_array", "filter_select", "lambda"],
    "cs_224": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "dynamic_array", "filter_select", "lambda"],
    "cs_225": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "dynamic_array", "filter_select", "lambda"],
    "cs_226": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "dynamic_array", "filter_select", "lambda"],
    "cs_227": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "dynamic_array", "filter_select", "lambda"],
    "cs_228": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "dynamic_array", "filter_select", "lambda"],
    "cs_229": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "dynamic_array", "filter_select", "lambda"],
    "cs_230": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "dynamic_array", "filter_select", "lambda"],
    "cs_231": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "dynamic_array", "filter_select", "lambda"],
    "cs_232": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "dynamic_array", "filter_select", "lambda"],
    "cs_233": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "dynamic_array", "filter_select", "lambda"],
    "cs_234": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "dynamic_array", "filter_select", "lambda"],
    "cs_235": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "dynamic_array", "filter_select", "lambda"],
    "cs_236": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "indexed_sequence", "dynamic_array", "filter_select", "lambda"],
    "cs_237": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "string_sequence", "function_definition", "parameter_passing", "recursion", "lambda", "class_type"],
    "cs_238": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "string_sequence", "function_definition", "parameter_passing", "recursion", "lambda", "class_type"],
    "cs_239": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "string_sequence", "function_definition", "parameter_passing", "recursion", "lambda", "class_type"],
    "cs_240": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "string_sequence", "function_definition", "parameter_passing", "recursion", "lambda", "class_type"],
    "cs_241": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "string_sequence", "function_definition", "parameter_passing", "recursion", "lambda", "class_type"],
    "cs_242": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "string_sequence", "function_definition", "parameter_passing", "recursion", "lambda", "class_type"],
    "cs_243": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "string_sequence", "function_definition", "parameter_passing", "recursion", "lambda", "class_type"],
    "cs_244": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "string_sequence", "function_definition", "parameter_passing", "recursion", "lambda", "class_type"],
    "cs_245": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "string_sequence", "function_definition", "parameter_passing", "recursion", "lambda", "class_type"],
    "cs_246": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "string_sequence", "function_definition", "parameter_passing", "recursion", "lambda", "class_type"],
    "cs_247": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "string_sequence", "function_definition", "parameter_passing", "recursion", "lambda", "class_type"],
    "cs_248": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "string_sequence", "function_definition", "parameter_passing", "recursion", "lambda", "class_type"],
    "cs_249": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "string_sequence", "function_definition", "parameter_passing", "recursion", "lambda", "class_type"],
    "cs_250": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "string_sequence", "function_definition", "parameter_passing", "recursion", "lambda", "class_type"],
    "cs_251": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "string_sequence", "function_definition", "parameter_passing", "recursion", "lambda", "class_type"],
    "cs_252": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "string_sequence", "function_definition", "parameter_passing", "recursion", "lambda", "class_type"],
    "cs_253": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "string_sequence", "function_definition", "parameter_passing", "recursion", "lambda", "class_type"],
    "cs_254": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "string_sequence", "function_definition", "parameter_passing", "recursion", "lambda", "class_type"],
    "cs_255": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "string_sequence", "function_definition", "parameter_passing", "recursion", "lambda", "class_type"],
    "cs_256": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "string_sequence", "function_definition", "parameter_passing", "recursion", "lambda", "class_type"],
    "cs_257": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "string_sequence", "function_definition", "parameter_passing", "recursion", "lambda", "class_type"],
    "cs_258": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "string_sequence", "function_definition", "parameter_passing", "recursion", "lambda", "class_type"],
    "cs_259": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "string_sequence", "function_definition", "parameter_passing", "recursion", "lambda", "class_type"],
    "cs_260": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "string_sequence", "function_definition", "parameter_passing", "recursion", "lambda", "class_type"],
    "cs_261": ["typed_declaration", "stdout_write", "assignment", "function_definition", "parameter_passing", "recursion", "lambda", "class_type", "inheritance_hierarchy"],
    "cs_262": ["typed_declaration", "stdout_write", "assignment", "function_definition", "parameter_passing", "recursion", "lambda", "class_type", "inheritance_hierarchy"],
    "cs_263": ["typed_declaration", "stdout_write", "assignment", "function_definition", "parameter_passing", "recursion", "lambda", "class_type", "inheritance_hierarchy"],
    "cs_264": ["typed_declaration", "stdout_write", "assignment", "function_definition", "parameter_passing", "recursion", "lambda", "class_type", "inheritance_hierarchy"],
    "cs_265": ["typed_declaration", "stdout_write", "assignment", "function_definition", "parameter_passing", "recursion", "lambda", "class_type", "inheritance_hierarchy"],
    "cs_266": ["typed_declaration", "stdout_write", "assignment", "function_definition", "parameter_passing", "recursion", "lambda", "class_type", "inheritance_hierarchy"],
    "cs_267": ["typed_declaration", "stdout_write", "assignment", "function_definition", "parameter_passing", "recursion", "lambda", "class_type", "inheritance_hierarchy"],
    "cs_268": ["typed_declaration", "stdout_write", "assignment", "function_definition", "parameter_passing", "recursion", "lambda", "class_type", "inheritance_hierarchy"],
    "cs_269": ["typed_declaration", "stdout_write", "assignment", "function_definition", "parameter_passing", "recursion", "lambda", "class_type", "inheritance_hierarchy"],
    "cs_270": ["typed_declaration", "stdout_write", "assignment", "function_definition", "parameter_passing", "recursion", "lambda", "class_type", "inheritance_hierarchy"],
}


def expected_concept_ids_for_row(
    slot_id: str,
    chapter_key: str,
    *,
    _features: str = "",
) -> list[str]:
    override = SLOT_OVERRIDES.get(slot_id)
    if override:
        return list(override)
    return list(CHAPTER_DEFAULTS.get(chapter_key, ["program_entry"]))


__all__ = ["expected_concept_ids_for_row", "CHAPTER_DEFAULTS", "SLOT_OVERRIDES"]
