"""Expected concept overrides for Python v4 tasks."""
from __future__ import annotations

SLOT_EXPECTED_CONCEPT_OVERRIDES: dict[str, list[str]] = {
    "py_001": ["program_entry", "typed_declaration", "assignment", "arithmetic_ops", "stdout_write"],
    "py_002": ["program_entry", "typed_declaration", "assignment", "arithmetic_ops", "stdout_write"],
    "py_003": ["program_entry", "typed_declaration", "assignment", "arithmetic_ops", "stdout_write"],
    "py_004": ["program_entry", "typed_declaration", "assignment", "arithmetic_ops", "stdout_write"],
    "py_005": ["program_entry", "typed_declaration", "assignment", "arithmetic_ops", "stdout_write"],
    "py_006": ["program_entry", "typed_declaration", "assignment", "arithmetic_ops", "stdout_write"],
    "py_007": ["program_entry", "typed_declaration", "assignment", "arithmetic_ops", "stdout_write"],
    "py_008": ["program_entry", "typed_declaration", "assignment", "arithmetic_ops", "stdout_write"],
    "py_009": ["program_entry", "typed_declaration", "assignment", "arithmetic_ops", "stdout_write"],
    "py_010": ["program_entry", "typed_declaration", "assignment", "arithmetic_ops", "stdout_write"],
    "py_011": ["program_entry", "typed_declaration", "assignment", "arithmetic_ops", "stdout_write"],
    "py_012": ["program_entry", "typed_declaration", "assignment", "arithmetic_ops", "stdout_write"],
    "py_013": ["typed_declaration", "stdin_read", "assignment", "arithmetic_ops", "stdout_write"],
    "py_014": ["typed_declaration", "stdin_read", "assignment", "arithmetic_ops", "stdout_write"],
    "py_015": ["typed_declaration", "stdin_read", "assignment", "arithmetic_ops", "stdout_write"],
    "py_016": ["typed_declaration", "stdin_read", "assignment", "arithmetic_ops", "stdout_write"],
    "py_017": ["typed_declaration", "stdin_read", "assignment", "arithmetic_ops", "stdout_write"],
    "py_018": ["typed_declaration", "stdin_read", "assignment", "arithmetic_ops", "stdout_write"],
    "py_019": ["typed_declaration", "stdin_read", "assignment", "arithmetic_ops", "stdout_write"],
    "py_020": ["typed_declaration", "stdin_read", "assignment", "arithmetic_ops", "stdout_write"],
    "py_021": ["typed_declaration", "stdin_read", "assignment", "arithmetic_ops", "stdout_write"],
    "py_022": ["typed_declaration", "stdin_read", "assignment", "arithmetic_ops", "stdout_write"],
    "py_023": ["typed_declaration", "stdin_read", "assignment", "arithmetic_ops", "stdout_write"],
    "py_024": ["typed_declaration", "stdin_read", "assignment", "arithmetic_ops", "stdout_write"],
    "py_025": ["typed_declaration", "stdin_read", "simple_branch", "assignment", "stdout_write"],
    "py_026": ["typed_declaration", "stdin_read", "simple_branch", "assignment", "stdout_write"],
    "py_027": ["typed_declaration", "stdin_read", "simple_branch", "assignment", "stdout_write"],
    "py_028": ["typed_declaration", "stdin_read", "simple_branch", "assignment", "stdout_write"],
    "py_029": ["typed_declaration", "stdin_read", "simple_branch", "assignment", "stdout_write"],
    "py_030": ["typed_declaration", "stdin_read", "simple_branch", "assignment", "stdout_write"],
    "py_031": ["typed_declaration", "stdin_read", "simple_branch", "assignment", "stdout_write"],
    "py_032": ["typed_declaration", "stdin_read", "simple_branch", "assignment", "stdout_write"],
    "py_033": ["typed_declaration", "stdin_read", "simple_branch", "assignment", "stdout_write"],
    "py_034": ["typed_declaration", "stdin_read", "simple_branch", "assignment", "stdout_write"],
    "py_035": ["typed_declaration", "stdin_read", "simple_branch", "assignment", "stdout_write"],
    "py_036": ["typed_declaration", "stdin_read", "simple_branch", "assignment", "stdout_write"],
    "py_037": ["typed_declaration", "stdin_read", "simple_branch", "assignment", "stdout_write"],
    "py_038": ["typed_declaration", "stdin_read", "simple_branch", "assignment", "stdout_write"],
    "py_039": ["typed_declaration", "stdin_read", "simple_branch", "assignment", "stdout_write"],
    "py_040": ["typed_declaration", "stdin_read", "simple_branch", "assignment", "stdout_write"],
    "py_041": ["typed_declaration", "stdin_read", "simple_branch", "assignment", "stdout_write"],
    "py_042": ["typed_declaration", "stdin_read", "simple_branch", "assignment", "stdout_write"],
    "py_043": ["typed_declaration", "stdin_read", "simple_branch", "assignment", "stdout_write"],
    "py_044": ["typed_declaration", "stdin_read", "simple_branch", "assignment", "stdout_write"],
    "py_045": ["typed_declaration", "stdin_read", "simple_branch", "assignment", "stdout_write"],
    "py_046": ["typed_declaration", "stdin_read", "simple_branch", "assignment", "stdout_write"],
    "py_047": ["typed_declaration", "stdin_read", "simple_branch", "assignment", "stdout_write"],
    "py_048": ["typed_declaration", "stdin_read", "simple_branch", "assignment", "stdout_write"],
    "py_049": ["typed_declaration", "stdin_read", "simple_branch", "assignment", "stdout_write"],
    "py_050": ["typed_declaration", "stdin_read", "simple_branch", "assignment", "stdout_write"],
    "py_051": ["typed_declaration", "stdin_read", "counted_loop", "pre_condition_loop", "assignment", "stdout_write"],
    "py_052": ["typed_declaration", "stdin_read", "counted_loop", "pre_condition_loop", "assignment", "stdout_write"],
    "py_053": ["typed_declaration", "stdin_read", "counted_loop", "pre_condition_loop", "assignment", "stdout_write"],
    "py_054": ["typed_declaration", "stdin_read", "counted_loop", "pre_condition_loop", "assignment", "stdout_write"],
    "py_055": ["typed_declaration", "stdin_read", "counted_loop", "pre_condition_loop", "assignment", "stdout_write"],
    "py_056": ["typed_declaration", "stdin_read", "counted_loop", "pre_condition_loop", "assignment", "stdout_write"],
    "py_057": ["typed_declaration", "stdin_read", "counted_loop", "pre_condition_loop", "assignment", "stdout_write"],
    "py_058": ["typed_declaration", "stdin_read", "counted_loop", "pre_condition_loop", "assignment", "stdout_write"],
    "py_059": ["typed_declaration", "stdin_read", "counted_loop", "pre_condition_loop", "assignment", "stdout_write"],
    "py_060": ["typed_declaration", "stdin_read", "counted_loop", "pre_condition_loop", "assignment", "stdout_write"],
    "py_061": ["typed_declaration", "stdin_read", "counted_loop", "pre_condition_loop", "assignment", "stdout_write"],
    "py_062": ["typed_declaration", "stdin_read", "counted_loop", "pre_condition_loop", "assignment", "stdout_write"],
    "py_063": ["typed_declaration", "stdin_read", "counted_loop", "pre_condition_loop", "assignment", "stdout_write"],
    "py_064": ["typed_declaration", "stdin_read", "counted_loop", "pre_condition_loop", "assignment", "stdout_write"],
    "py_065": ["typed_declaration", "stdin_read", "counted_loop", "pre_condition_loop", "assignment", "stdout_write"],
    "py_066": ["typed_declaration", "stdin_read", "counted_loop", "pre_condition_loop", "assignment", "stdout_write"],
    "py_067": ["nested_iteration", "loop_control", "counted_loop", "stdout_write"],
    "py_068": ["nested_iteration", "loop_control", "counted_loop", "stdout_write"],
    "py_069": ["nested_iteration", "loop_control", "counted_loop", "stdout_write"],
    "py_070": ["nested_iteration", "loop_control", "counted_loop", "stdout_write"],
    "py_071": ["nested_iteration", "loop_control", "counted_loop", "stdout_write"],
    "py_072": ["nested_iteration", "loop_control", "counted_loop", "stdout_write"],
    "py_073": ["nested_iteration", "loop_control", "counted_loop", "stdout_write"],
    "py_074": ["nested_iteration", "loop_control", "counted_loop", "stdout_write"],
    "py_075": ["nested_iteration", "loop_control", "counted_loop", "stdout_write"],
    "py_076": ["nested_iteration", "loop_control", "counted_loop", "stdout_write"],
    "py_077": ["nested_iteration", "loop_control", "counted_loop", "stdout_write"],
    "py_078": ["nested_iteration", "loop_control", "counted_loop", "stdout_write"],
    "py_079": ["indexed_sequence", "collection_iteration", "counted_loop", "stdout_write"],
    "py_080": ["indexed_sequence", "collection_iteration", "counted_loop", "stdout_write"],
    "py_081": ["indexed_sequence", "collection_iteration", "counted_loop", "stdout_write"],
    "py_082": ["indexed_sequence", "collection_iteration", "counted_loop", "stdout_write"],
    "py_083": ["indexed_sequence", "collection_iteration", "counted_loop", "stdout_write"],
    "py_084": ["indexed_sequence", "collection_iteration", "counted_loop", "stdout_write"],
    "py_085": ["indexed_sequence", "collection_iteration", "counted_loop", "stdout_write"],
    "py_086": ["indexed_sequence", "collection_iteration", "counted_loop", "stdout_write"],
    "py_087": ["indexed_sequence", "collection_iteration", "counted_loop", "stdout_write"],
    "py_088": ["indexed_sequence", "collection_iteration", "counted_loop", "stdout_write"],
    "py_089": ["indexed_sequence", "collection_iteration", "counted_loop", "stdout_write"],
    "py_090": ["indexed_sequence", "collection_iteration", "counted_loop", "stdout_write"],
    "py_091": ["indexed_sequence", "collection_iteration", "counted_loop", "stdout_write"],
    "py_092": ["indexed_sequence", "collection_iteration", "counted_loop", "stdout_write"],
    "py_093": ["indexed_sequence", "collection_iteration", "counted_loop", "stdout_write"],
    "py_094": ["indexed_sequence", "collection_iteration", "counted_loop", "stdout_write"],
    "py_095": ["dynamic_array", "collection_iteration", "stdout_write"],
    "py_096": ["dynamic_array", "collection_iteration", "stdout_write"],
    "py_097": ["dynamic_array", "collection_iteration", "stdout_write"],
    "py_098": ["dynamic_array", "collection_iteration", "stdout_write"],
    "py_099": ["dynamic_array", "collection_iteration", "stdout_write"],
    "py_100": ["dynamic_array", "collection_iteration", "stdout_write"],
    "py_101": ["dynamic_array", "collection_iteration", "stdout_write"],
    "py_102": ["dynamic_array", "collection_iteration", "stdout_write"],
    "py_103": ["dynamic_array", "collection_iteration", "stdout_write"],
    "py_104": ["dynamic_array", "collection_iteration", "stdout_write"],
    "py_105": ["dynamic_array", "collection_iteration", "stdout_write"],
    "py_106": ["dynamic_array", "collection_iteration", "stdout_write"],
    "py_107": ["dynamic_array", "collection_iteration", "stdout_write"],
    "py_108": ["dynamic_array", "collection_iteration", "stdout_write"],
    "py_109": ["string_sequence", "collection_iteration", "simple_branch", "stdout_write"],
    "py_110": ["string_sequence", "collection_iteration", "simple_branch", "stdout_write"],
    "py_111": ["string_sequence", "collection_iteration", "simple_branch", "stdout_write"],
    "py_112": ["string_sequence", "collection_iteration", "simple_branch", "stdout_write"],
    "py_113": ["string_sequence", "collection_iteration", "simple_branch", "stdout_write"],
    "py_114": ["string_sequence", "collection_iteration", "simple_branch", "stdout_write"],
    "py_115": ["string_sequence", "collection_iteration", "simple_branch", "stdout_write"],
    "py_116": ["string_sequence", "collection_iteration", "simple_branch", "stdout_write"],
    "py_117": ["string_sequence", "collection_iteration", "simple_branch", "stdout_write"],
    "py_118": ["string_sequence", "collection_iteration", "simple_branch", "stdout_write"],
    "py_119": ["string_sequence", "collection_iteration", "simple_branch", "stdout_write"],
    "py_120": ["string_sequence", "collection_iteration", "simple_branch", "stdout_write"],
    "py_121": ["string_sequence", "collection_iteration", "simple_branch", "stdout_write"],
    "py_122": ["string_sequence", "collection_iteration", "simple_branch", "stdout_write"],
    "py_123": ["function_definition", "function_invocation", "return_flow"],
    "py_124": ["function_definition", "function_invocation", "return_flow"],
    "py_125": ["function_definition", "function_invocation", "return_flow"],
    "py_126": ["function_definition", "function_invocation", "return_flow"],
    "py_127": ["function_definition", "function_invocation", "return_flow"],
    "py_128": ["function_definition", "function_invocation", "return_flow"],
    "py_129": ["function_definition", "function_invocation", "return_flow"],
    "py_130": ["function_definition", "function_invocation", "return_flow"],
    "py_131": ["function_definition", "function_invocation", "return_flow"],
    "py_132": ["function_definition", "function_invocation", "return_flow"],
    "py_133": ["function_definition", "function_invocation", "return_flow"],
    "py_134": ["function_definition", "function_invocation", "return_flow"],
    "py_135": ["function_definition", "function_invocation", "return_flow"],
    "py_136": ["function_definition", "function_invocation", "return_flow"],
    "py_137": ["function_definition", "function_invocation", "return_flow"],
    "py_138": ["function_definition", "function_invocation", "return_flow"],
    "py_139": ["function_definition", "function_invocation", "return_flow"],
    "py_140": ["function_definition", "function_invocation", "return_flow"],
    "py_141": ["function_definition", "recursion", "simple_branch", "return_flow"],
    "py_142": ["function_definition", "recursion", "simple_branch", "return_flow"],
    "py_143": ["function_definition", "recursion", "simple_branch", "return_flow"],
    "py_144": ["function_definition", "recursion", "simple_branch", "return_flow"],
    "py_145": ["function_definition", "recursion", "simple_branch", "return_flow"],
    "py_146": ["function_definition", "recursion", "simple_branch", "return_flow"],
    "py_147": ["function_definition", "recursion", "simple_branch", "return_flow"],
    "py_148": ["function_definition", "recursion", "simple_branch", "return_flow"],
    "py_149": ["search_find", "filter_select", "fold_aggregate", "collection_iteration"],
    "py_150": ["search_find", "filter_select", "fold_aggregate", "collection_iteration"],
    "py_151": ["search_find", "filter_select", "fold_aggregate", "collection_iteration"],
    "py_152": ["search_find", "filter_select", "fold_aggregate", "collection_iteration"],
    "py_153": ["search_find", "filter_select", "fold_aggregate", "collection_iteration"],
    "py_154": ["search_find", "filter_select", "fold_aggregate", "collection_iteration"],
    "py_155": ["search_find", "filter_select", "fold_aggregate", "collection_iteration"],
    "py_156": ["search_find", "filter_select", "fold_aggregate", "collection_iteration"],
    "py_157": ["search_find", "filter_select", "fold_aggregate", "collection_iteration"],
    "py_158": ["search_find", "filter_select", "fold_aggregate", "collection_iteration"],
    "py_159": ["search_find", "filter_select", "fold_aggregate", "collection_iteration"],
    "py_160": ["search_find", "filter_select", "fold_aggregate", "collection_iteration"],
    "py_161": ["search_find", "filter_select", "fold_aggregate", "collection_iteration"],
    "py_162": ["search_find", "filter_select", "fold_aggregate", "collection_iteration"],
    "py_163": ["search_find", "filter_select", "fold_aggregate", "collection_iteration"],
    "py_164": ["search_find", "filter_select", "fold_aggregate", "collection_iteration"],
    "py_165": ["search_find", "filter_select", "fold_aggregate", "collection_iteration"],
    "py_166": ["search_find", "filter_select", "fold_aggregate", "collection_iteration"],
    "py_167": ["sort_order", "collection_iteration"],
    "py_168": ["sort_order", "collection_iteration"],
    "py_169": ["sort_order", "collection_iteration"],
    "py_170": ["sort_order", "collection_iteration"],
    "py_171": ["sort_order", "collection_iteration"],
    "py_172": ["sort_order", "collection_iteration"],
    "py_173": ["sort_order", "collection_iteration"],
    "py_174": ["sort_order", "collection_iteration"],
    "py_175": ["sort_order", "collection_iteration"],
    "py_176": ["sort_order", "collection_iteration"],
    "py_177": ["key_value_map", "search_find"],
    "py_178": ["key_value_map", "search_find"],
    "py_179": ["key_value_map", "search_find"],
    "py_180": ["key_value_map", "search_find"],
    "py_181": ["key_value_map", "search_find"],
    "py_182": ["key_value_map", "search_find"],
    "py_183": ["key_value_map", "search_find"],
    "py_184": ["key_value_map", "search_find"],
    "py_185": ["key_value_map", "search_find"],
    "py_186": ["key_value_map", "search_find"],
    "py_187": ["key_value_map", "search_find"],
    "py_188": ["key_value_map", "search_find"],
    "py_189": ["file_read", "file_write", "collection_iteration"],
    "py_190": ["file_read", "file_write", "collection_iteration"],
    "py_191": ["file_read", "file_write", "collection_iteration"],
    "py_192": ["file_read", "file_write", "collection_iteration"],
    "py_193": ["file_read", "file_write", "collection_iteration"],
    "py_194": ["file_read", "file_write", "collection_iteration"],
    "py_195": ["file_read", "file_write", "collection_iteration"],
    "py_196": ["file_read", "file_write", "collection_iteration"],
    "py_197": ["file_read", "file_write", "collection_iteration"],
    "py_198": ["file_read", "file_write", "collection_iteration"],
    "py_199": ["import_dependency", "module_namespace", "symbol_visibility"],
    "py_200": ["import_dependency", "module_namespace", "symbol_visibility"],
    "py_201": ["import_dependency", "module_namespace", "symbol_visibility"],
    "py_202": ["import_dependency", "module_namespace", "symbol_visibility"],
    "py_203": ["import_dependency", "module_namespace", "symbol_visibility"],
    "py_204": ["import_dependency", "module_namespace", "symbol_visibility"],
    "py_205": ["import_dependency", "module_namespace", "symbol_visibility"],
    "py_206": ["import_dependency", "module_namespace", "symbol_visibility"],
    "py_207": ["stack_queue", "linked_node", "tree_hierarchy", "graph_edges"],
    "py_208": ["stack_queue", "linked_node", "tree_hierarchy", "graph_edges"],
    "py_209": ["stack_queue", "linked_node", "tree_hierarchy", "graph_edges"],
    "py_210": ["stack_queue", "linked_node", "tree_hierarchy", "graph_edges"],
    "py_211": ["stack_queue", "linked_node", "tree_hierarchy", "graph_edges"],
    "py_212": ["stack_queue", "linked_node", "tree_hierarchy", "graph_edges"],
    "py_213": ["stack_queue", "linked_node", "tree_hierarchy", "graph_edges"],
    "py_214": ["stack_queue", "linked_node", "tree_hierarchy", "graph_edges"],
    "py_215": ["stack_queue", "linked_node", "tree_hierarchy", "graph_edges"],
    "py_216": ["stack_queue", "linked_node", "tree_hierarchy", "graph_edges"],
    "py_217": ["stack_queue", "linked_node", "tree_hierarchy", "graph_edges"],
    "py_218": ["stack_queue", "linked_node", "tree_hierarchy", "graph_edges"],
    "py_219": ["stack_queue", "linked_node", "tree_hierarchy", "graph_edges"],
    "py_220": ["stack_queue", "linked_node", "tree_hierarchy", "graph_edges"],
    "py_221": ["stack_queue", "linked_node", "tree_hierarchy", "graph_edges"],
    "py_222": ["filter_select", "fold_aggregate", "comprehension", "lambda"],
    "py_223": ["filter_select", "fold_aggregate", "comprehension", "lambda"],
    "py_224": ["filter_select", "fold_aggregate", "comprehension", "lambda"],
    "py_225": ["filter_select", "fold_aggregate", "comprehension", "lambda"],
    "py_226": ["filter_select", "fold_aggregate", "comprehension", "lambda"],
    "py_227": ["filter_select", "fold_aggregate", "comprehension", "lambda"],
    "py_228": ["filter_select", "fold_aggregate", "comprehension", "lambda"],
    "py_229": ["filter_select", "fold_aggregate", "comprehension", "lambda"],
    "py_230": ["filter_select", "fold_aggregate", "comprehension", "lambda"],
    "py_231": ["filter_select", "fold_aggregate", "comprehension", "lambda"],
    "py_232": ["filter_select", "fold_aggregate", "comprehension", "lambda"],
    "py_233": ["filter_select", "fold_aggregate", "comprehension", "lambda"],
    "py_234": ["filter_select", "fold_aggregate", "comprehension", "lambda"],
    "py_235": ["filter_select", "fold_aggregate", "comprehension", "lambda"],
    "py_236": ["filter_select", "fold_aggregate", "comprehension", "lambda"],
    "py_237": ["class_type", "object_instance", "method_dispatch"],
    "py_238": ["class_type", "object_instance", "method_dispatch"],
    "py_239": ["class_type", "object_instance", "method_dispatch"],
    "py_240": ["class_type", "object_instance", "method_dispatch"],
    "py_241": ["class_type", "object_instance", "method_dispatch"],
    "py_242": ["class_type", "object_instance", "method_dispatch"],
    "py_243": ["class_type", "object_instance", "method_dispatch"],
    "py_244": ["class_type", "object_instance", "method_dispatch"],
    "py_245": ["class_type", "object_instance", "method_dispatch"],
    "py_246": ["class_type", "object_instance", "method_dispatch"],
    "py_247": ["class_type", "object_instance", "method_dispatch"],
    "py_248": ["class_type", "object_instance", "method_dispatch"],
    "py_249": ["class_type", "object_instance", "method_dispatch"],
    "py_250": ["class_type", "object_instance", "method_dispatch"],
    "py_251": ["class_type", "object_instance", "method_dispatch"],
    "py_252": ["class_type", "object_instance", "method_dispatch"],
    "py_253": ["class_type", "object_instance", "method_dispatch"],
    "py_254": ["class_type", "object_instance", "method_dispatch"],
    "py_255": ["class_type", "object_instance", "method_dispatch"],
    "py_256": ["class_type", "object_instance", "method_dispatch"],
    "py_257": ["class_type", "object_instance", "method_dispatch"],
    "py_258": ["class_type", "object_instance", "method_dispatch"],
    "py_259": ["class_type", "object_instance", "method_dispatch"],
    "py_260": ["class_type", "object_instance", "method_dispatch"],
    "py_261": ["class_type", "object_instance", "method_dispatch", "inheritance_hierarchy"],
    "py_262": ["class_type", "object_instance", "method_dispatch", "inheritance_hierarchy"],
    "py_263": ["class_type", "object_instance", "method_dispatch", "inheritance_hierarchy"],
    "py_264": ["class_type", "object_instance", "method_dispatch", "inheritance_hierarchy"],
    "py_265": ["class_type", "object_instance", "method_dispatch", "inheritance_hierarchy"],
    "py_266": ["class_type", "object_instance", "method_dispatch", "inheritance_hierarchy"],
    "py_267": ["class_type", "object_instance", "method_dispatch", "inheritance_hierarchy"],
    "py_268": ["class_type", "object_instance", "method_dispatch", "inheritance_hierarchy"],
    "py_269": ["class_type", "object_instance", "method_dispatch", "inheritance_hierarchy"],
    "py_270": ["class_type", "object_instance", "method_dispatch", "inheritance_hierarchy"],
}
