"""Expected pedagogical concepts for Python Course v1 tasks."""

from __future__ import annotations

from application.curriculum.python.catalog.python_v311_capstone_catalog import capstone_expected_concepts

CHAPTER_DEFAULT_TC: dict[str, str] = {
    "program_entry": "program_entry",
    "typed_variables": "typed_declaration",
    "io": "stdin_read",
    "expressions": "arithmetic_ops",
    "conditions": "simple_branch",
    "loops": "counted_loop",
    "functions": "function_definition",
    "parameters": "parameter_passing",
    "lists": "indexed_sequence",
    "comprehensions": "indexed_sequence",
    "dynamic_lists": "dynamic_array",
    "strings": "string_sequence",
    "mappings": "key_value_map",
    "files": "file_read",
    "modules": "import_dependency",
    "recursion": "recursion",
    "oop": "class_type",
    "exceptions": "simple_branch",
    "pro_python": "function_definition",
    "advanced_python": "function_definition",
    "typing_diagnostics": "typed_declaration",
    "python_pitfalls": "assignment",
    "python_diagnostics": "typed_declaration",
    "capstones": "program_entry",
}

from application.curriculum.python.catalog.python_v12_delta_content import V12_EXPECTED_CONCEPT_OVERRIDES

SLOT_OVERRIDES: dict[str, list[str]] = {}
SLOT_OVERRIDES.update(V12_EXPECTED_CONCEPT_OVERRIDES)
SLOT_OVERRIDES.update(dict(capstone_expected_concepts()))


def expected_concept_ids_for_row(
    *,
    slot_id: str,
    chapter_key: str,
    python_features: str,
    task_format: str,
) -> list[str]:
    del task_format
    from application.curriculum.content.algo_syntax_task_extra import (
        algo_expected_concepts,
        is_algo_syntax_slot,
    )

    if is_algo_syntax_slot(slot_id):
        concepts = algo_expected_concepts(slot_id, "python")
        if concepts:
            return concepts
        parsed = [part.strip() for part in python_features.split(";") if part.strip()]
        if parsed:
            return parsed

    if slot_id in SLOT_OVERRIDES:
        return list(SLOT_OVERRIDES[slot_id])
    tc = CHAPTER_DEFAULT_TC.get(chapter_key, "assignment")
    concepts = [tc]
    features = python_features.lower()
    if "import" in features and "import_dependency" not in concepts:
        concepts.append("import_dependency")
    if "class" in features and "class_type" not in concepts:
        concepts.append("class_type")
    if "recursion" in features and "recursion" not in concepts:
        concepts.append("recursion")
    return concepts


# v4 chapter defaults (new chapters)
_V4_CHAPTER_DEFAULTS: dict[str, str] = {
    "conditions_multi": "multi_branch",
    "loops_adv":        "loop_control",
    "algorithms":       "search_find",
    "sorting":          "sort_order",
    "data_structures":  "stack_queue",
    "functional":       "filter_select",
    "oop_state":        "object_instance",
    "oop_inherit":      "inheritance_hierarchy",
}
CHAPTER_DEFAULT_TC.update(_V4_CHAPTER_DEFAULTS)


# ── v4 task overrides (270 tasks) ────────────────────────────────────────────────
_V4_SLOT_OVERRIDES: dict[str, list[str]] = {

    "py_001": ["stdout_write"],
    "py_002": ["stdout_write", "assignment"],
    "py_003": ["stdout_write", "assignment", "arithmetic_ops"],
    "py_004": ["stdout_write", "assignment", "arithmetic_ops"],
    "py_005": ["stdout_write", "assignment", "arithmetic_ops"],
    "py_006": ["stdout_write", "assignment"],
    "py_007": ["stdout_write", "assignment", "arithmetic_ops"],
    "py_008": ["stdout_write", "assignment", "arithmetic_ops"],
    "py_009": ["stdout_write", "assignment", "arithmetic_ops"],
    "py_010": ["stdout_write", "assignment", "arithmetic_ops"],
    "py_011": ["stdout_write", "assignment", "arithmetic_ops"],
    "py_012": ["stdout_write", "assignment", "arithmetic_ops"],
    "py_013": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops"],
    "py_014": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops"],
    "py_015": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "method_dispatch"],
    "py_016": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "method_dispatch"],
    "py_017": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops"],
    "py_018": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "method_dispatch"],
    "py_019": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops"],
    "py_020": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "method_dispatch"],
    "py_021": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops"],
    "py_022": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops"],
    "py_023": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "method_dispatch"],
    "py_024": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "method_dispatch"],
    "py_025": ["stdin_read", "stdout_write", "assignment", "simple_branch", "conditional_expression"],
    "py_026": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "conditional_expression"],
    "py_027": ["stdin_read", "stdout_write", "assignment", "simple_branch", "conditional_expression"],
    "py_028": ["stdin_read", "stdout_write", "assignment", "simple_branch", "conditional_expression"],
    "py_029": ["stdin_read", "stdout_write", "assignment", "simple_branch", "conditional_expression"],
    "py_030": ["stdin_read", "stdout_write", "assignment", "simple_branch", "conditional_expression"],
    "py_031": ["stdin_read", "stdout_write", "assignment", "simple_branch", "conditional_expression"],
    "py_032": ["stdin_read", "stdout_write", "assignment", "simple_branch", "conditional_expression"],
    "py_033": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "conditional_expression", "method_dispatch"],
    "py_034": ["stdin_read", "stdout_write", "assignment", "simple_branch", "conditional_expression"],
    "py_035": ["stdin_read", "stdout_write", "assignment", "simple_branch", "conditional_expression"],
    "py_036": ["stdin_read", "stdout_write", "assignment", "simple_branch", "conditional_expression"],
    "py_037": ["stdin_read", "stdout_write", "assignment", "simple_branch", "conditional_expression"],
    "py_038": ["stdin_read", "stdout_write", "assignment", "simple_branch", "conditional_expression", "method_dispatch"],
    "py_039": ["stdin_read", "stdout_write", "assignment", "simple_branch", "conditional_expression", "multi_branch"],
    "py_040": ["stdin_read", "stdout_write", "assignment", "method_dispatch"],
    "py_041": ["stdin_read", "stdout_write", "assignment", "method_dispatch"],
    "py_042": ["stdin_read", "stdout_write", "assignment", "method_dispatch"],
    "py_043": ["stdin_read", "stdout_write", "assignment", "simple_branch", "conditional_expression", "multi_branch"],
    "py_044": ["a", "input"],
    "py_045": ["stdin_read", "stdout_write", "assignment", "method_dispatch"],
    "py_046": ["stdin_read", "stdout_write", "assignment", "simple_branch", "conditional_expression", "multi_branch"],
    "py_047": ["stdin_read", "stdout_write", "assignment", "simple_branch", "conditional_expression", "multi_branch"],
    "py_048": ["stdin_read", "stdout_write", "assignment", "simple_branch", "conditional_expression", "multi_branch"],
    "py_049": ["stdin_read", "stdout_write", "assignment", "method_dispatch"],
    "py_050": ["stdin_read", "stdout_write", "assignment", "method_dispatch"],
    "py_051": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "collection_iteration"],
    "py_052": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "collection_iteration"],
    "py_053": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "collection_iteration"],
    "py_054": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "collection_iteration"],
    "py_055": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "collection_iteration"],
    "py_056": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "collection_iteration"],
    "py_057": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "collection_iteration"],
    "py_058": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "collection_iteration"],
    "py_059": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "collection_iteration"],
    "py_060": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "collection_iteration"],
    "py_061": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "collection_iteration"],
    "py_062": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "collection_iteration"],
    "py_063": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "pre_condition_loop"],
    "py_064": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "pre_condition_loop"],
    "py_065": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "collection_iteration"],
    "py_066": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "collection_iteration"],
    "py_067": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "collection_iteration"],
    "py_068": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "collection_iteration"],
    "py_069": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "collection_iteration"],
    "py_070": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "collection_iteration"],
    "py_071": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "collection_iteration"],
    "py_072": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "collection_iteration"],
    "py_073": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "collection_iteration"],
    "py_074": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "collection_iteration"],
    "py_075": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "collection_iteration"],
    "py_076": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "collection_iteration"],
    "py_077": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "collection_iteration"],
    "py_078": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "collection_iteration"],
    "py_079": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "comprehension"],
    "py_080": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "comprehension"],
    "py_081": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "comprehension"],
    "py_082": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "comprehension"],
    "py_083": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "comprehension"],
    "py_084": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "comprehension"],
    "py_085": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "comprehension"],
    "py_086": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "comprehension"],
    "py_087": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "comprehension"],
    "py_088": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "comprehension"],
    "py_089": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "comprehension"],
    "py_090": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "comprehension"],
    "py_091": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "comprehension"],
    "py_092": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "comprehension"],
    "py_093": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "comprehension"],
    "py_094": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "comprehension"],
    "py_095": ["stdin_read", "stdout_write", "assignment", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "dynamic_array"],
    "py_096": ["stdin_read", "stdout_write", "assignment", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "dynamic_array"],
    "py_097": ["stdin_read", "stdout_write", "assignment", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "dynamic_array"],
    "py_098": ["stdin_read", "stdout_write", "assignment", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "dynamic_array"],
    "py_099": ["stdin_read", "stdout_write", "assignment", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "dynamic_array"],
    "py_100": ["stdin_read", "stdout_write", "assignment", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "dynamic_array"],
    "py_101": ["stdin_read", "stdout_write", "assignment", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "dynamic_array"],
    "py_102": ["stdin_read", "stdout_write", "assignment", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "dynamic_array"],
    "py_103": ["stdin_read", "stdout_write", "assignment", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "dynamic_array"],
    "py_104": ["stdin_read", "stdout_write", "assignment", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "dynamic_array"],
    "py_105": ["stdin_read", "stdout_write", "assignment", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "dynamic_array"],
    "py_106": ["stdin_read", "stdout_write", "assignment", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "dynamic_array"],
    "py_107": ["stdin_read", "stdout_write", "assignment", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "dynamic_array"],
    "py_108": ["stdin_read", "stdout_write", "assignment", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "dynamic_array"],
    "py_109": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "collection_iteration"],
    "py_110": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "collection_iteration"],
    "py_111": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "collection_iteration"],
    "py_112": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "collection_iteration"],
    "py_113": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "collection_iteration"],
    "py_114": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "collection_iteration"],
    "py_115": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "collection_iteration"],
    "py_116": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "collection_iteration"],
    "py_117": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "collection_iteration"],
    "py_118": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "collection_iteration"],
    "py_119": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "collection_iteration"],
    "py_120": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "collection_iteration"],
    "py_121": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "collection_iteration"],
    "py_122": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "collection_iteration"],
    "py_123": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "function_definition", "return_flow", "parameter_passing", "recursion"],
    "py_124": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "function_definition", "return_flow", "parameter_passing", "recursion"],
    "py_125": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "function_definition", "return_flow", "parameter_passing", "recursion"],
    "py_126": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "function_definition", "return_flow", "parameter_passing", "recursion"],
    "py_127": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "function_definition", "return_flow", "parameter_passing", "recursion"],
    "py_128": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "function_definition", "return_flow", "parameter_passing", "recursion"],
    "py_129": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "function_definition", "return_flow", "parameter_passing", "recursion"],
    "py_130": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "function_definition", "return_flow", "parameter_passing", "recursion"],
    "py_131": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "function_definition", "return_flow", "parameter_passing", "recursion"],
    "py_132": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "function_definition", "return_flow", "parameter_passing", "recursion"],
    "py_133": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "function_definition", "return_flow", "parameter_passing", "recursion"],
    "py_134": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "function_definition", "return_flow", "parameter_passing", "recursion"],
    "py_135": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "function_definition", "return_flow", "parameter_passing", "recursion"],
    "py_136": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "function_definition", "return_flow", "parameter_passing", "recursion"],
    "py_137": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "function_definition", "return_flow", "parameter_passing", "recursion"],
    "py_138": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "function_definition", "return_flow", "parameter_passing", "recursion"],
    "py_139": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "function_definition", "return_flow", "parameter_passing", "recursion"],
    "py_140": ["stdin_read", "stdout_write", "assignment", "arithmetic_ops", "function_definition", "return_flow", "parameter_passing", "recursion"],
    "py_141": ["stdout_write", "arithmetic_ops", "simple_branch", "function_definition", "return_flow", "parameter_passing", "recursion"],
    "py_142": ["stdout_write", "arithmetic_ops", "simple_branch", "function_definition", "return_flow", "parameter_passing", "recursion"],
    "py_143": ["stdout_write", "arithmetic_ops", "simple_branch", "function_definition", "return_flow", "parameter_passing", "recursion"],
    "py_144": ["stdout_write", "arithmetic_ops", "simple_branch", "function_definition", "return_flow", "parameter_passing", "recursion"],
    "py_145": ["stdout_write", "arithmetic_ops", "simple_branch", "function_definition", "return_flow", "parameter_passing", "recursion"],
    "py_146": ["stdout_write", "arithmetic_ops", "simple_branch", "function_definition", "return_flow", "parameter_passing", "recursion"],
    "py_147": ["stdout_write", "arithmetic_ops", "simple_branch", "function_definition", "return_flow", "parameter_passing", "recursion"],
    "py_148": ["stdout_write", "arithmetic_ops", "simple_branch", "function_definition", "return_flow", "parameter_passing", "recursion"],
    "py_149": ["stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "indexed_sequence", "collection_iteration", "fold_aggregate"],
    "py_150": ["stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "indexed_sequence", "collection_iteration", "fold_aggregate"],
    "py_151": ["stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "indexed_sequence", "collection_iteration", "fold_aggregate"],
    "py_152": ["stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "indexed_sequence", "collection_iteration", "fold_aggregate"],
    "py_153": ["stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "indexed_sequence", "collection_iteration", "fold_aggregate"],
    "py_154": ["stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "indexed_sequence", "collection_iteration", "fold_aggregate"],
    "py_155": ["stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "indexed_sequence", "collection_iteration", "fold_aggregate"],
    "py_156": ["stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "indexed_sequence", "collection_iteration", "fold_aggregate"],
    "py_157": ["stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "indexed_sequence", "collection_iteration", "fold_aggregate"],
    "py_158": ["stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "indexed_sequence", "collection_iteration", "fold_aggregate"],
    "py_159": ["stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "indexed_sequence", "collection_iteration", "fold_aggregate"],
    "py_160": ["stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "indexed_sequence", "collection_iteration", "fold_aggregate"],
    "py_161": ["stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "indexed_sequence", "collection_iteration", "fold_aggregate"],
    "py_162": ["stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "indexed_sequence", "collection_iteration", "fold_aggregate"],
    "py_163": ["stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "indexed_sequence", "collection_iteration", "fold_aggregate"],
    "py_164": ["stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "indexed_sequence", "collection_iteration", "fold_aggregate"],
    "py_165": ["stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "indexed_sequence", "collection_iteration", "fold_aggregate"],
    "py_166": ["stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "indexed_sequence", "collection_iteration", "fold_aggregate"],
    "py_167": ["stdout_write", "assignment", "indexed_sequence", "sort_order"],
    "py_168": ["stdout_write", "assignment", "indexed_sequence", "sort_order"],
    "py_169": ["stdout_write", "assignment", "indexed_sequence", "sort_order"],
    "py_170": ["stdout_write", "assignment", "indexed_sequence", "sort_order"],
    "py_171": ["stdout_write", "assignment", "indexed_sequence", "sort_order"],
    "py_172": ["stdout_write", "assignment", "indexed_sequence", "sort_order"],
    "py_173": ["stdout_write", "assignment", "indexed_sequence", "sort_order"],
    "py_174": ["stdout_write", "assignment", "indexed_sequence", "sort_order"],
    "py_175": ["stdout_write", "assignment", "indexed_sequence", "sort_order"],
    "py_176": ["stdout_write", "assignment", "indexed_sequence", "sort_order"],
    "py_177": ["stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "indexed_sequence", "collection_iteration", "fold_aggregate"],
    "py_178": ["stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "indexed_sequence", "collection_iteration", "fold_aggregate"],
    "py_179": ["stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "indexed_sequence", "collection_iteration", "fold_aggregate"],
    "py_180": ["stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "indexed_sequence", "collection_iteration", "fold_aggregate"],
    "py_181": ["stdin_read", "stdout_write", "assignment", "method_dispatch"],
    "py_182": ["stdin_read", "stdout_write", "assignment", "method_dispatch"],
    "py_183": ["stdin_read", "stdout_write", "assignment", "method_dispatch"],
    "py_184": ["stdin_read", "stdout_write", "assignment", "method_dispatch"],
    "py_185": ["stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "indexed_sequence", "collection_iteration", "fold_aggregate"],
    "py_186": ["stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "indexed_sequence", "collection_iteration", "fold_aggregate"],
    "py_187": ["stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "indexed_sequence", "collection_iteration", "fold_aggregate"],
    "py_188": ["stdin_read", "stdout_write", "assignment", "method_dispatch"],
    "py_189": ["stdout_write", "assignment", "arithmetic_ops", "counted_loop", "collection_iteration", "file_read"],
    "py_190": ["stdout_write", "assignment", "arithmetic_ops", "counted_loop", "collection_iteration", "file_read"],
    "py_191": ["stdout_write", "assignment", "arithmetic_ops", "counted_loop", "collection_iteration", "file_read"],
    "py_192": ["stdout_write", "assignment", "arithmetic_ops", "counted_loop", "collection_iteration", "file_read"],
    "py_193": ["stdout_write", "assignment", "arithmetic_ops", "counted_loop", "collection_iteration", "file_read"],
    "py_194": ["stdout_write", "assignment", "arithmetic_ops", "counted_loop", "collection_iteration", "file_read"],
    "py_195": ["stdout_write", "assignment", "arithmetic_ops", "counted_loop", "collection_iteration", "file_read"],
    "py_196": ["stdout_write", "assignment", "arithmetic_ops", "counted_loop", "collection_iteration", "file_read"],
    "py_197": ["stdout_write", "assignment", "arithmetic_ops", "counted_loop", "collection_iteration", "file_read"],
    "py_198": ["stdout_write", "assignment", "arithmetic_ops", "counted_loop", "collection_iteration", "file_read"],
    "py_199": ["import_dependency", "stdout_write", "arithmetic_ops", "function_definition", "return_flow", "parameter_passing", "recursion"],
    "py_200": ["import_dependency", "stdout_write", "arithmetic_ops", "function_definition", "return_flow", "parameter_passing", "recursion"],
    "py_201": ["import_dependency", "stdout_write", "arithmetic_ops", "function_definition", "return_flow", "parameter_passing", "recursion"],
    "py_202": ["import_dependency", "stdout_write", "arithmetic_ops", "function_definition", "return_flow", "parameter_passing", "recursion"],
    "py_203": ["import_dependency", "stdout_write", "arithmetic_ops", "function_definition", "return_flow", "parameter_passing", "recursion"],
    "py_204": ["import_dependency", "stdout_write", "arithmetic_ops", "function_definition", "return_flow", "parameter_passing", "recursion"],
    "py_205": ["import_dependency", "stdout_write", "arithmetic_ops", "function_definition", "return_flow", "parameter_passing", "recursion"],
    "py_206": ["import_dependency", "stdout_write", "arithmetic_ops", "function_definition", "return_flow", "parameter_passing", "recursion"],
    "py_207": ["stdout_write", "assignment", "indexed_sequence", "dynamic_array", "stack_queue"],
    "py_208": ["stdout_write", "assignment", "indexed_sequence", "dynamic_array", "stack_queue"],
    "py_209": ["stdout_write", "assignment", "indexed_sequence", "dynamic_array", "stack_queue"],
    "py_210": ["stdout_write", "assignment", "indexed_sequence", "dynamic_array", "stack_queue"],
    "py_211": ["stdout_write", "assignment", "function_definition", "parameter_passing", "linked_node", "class_type"],
    "py_212": ["stdout_write", "assignment", "function_definition", "parameter_passing", "linked_node", "class_type"],
    "py_213": ["stdout_write", "assignment", "function_definition", "parameter_passing", "linked_node", "class_type"],
    "py_214": ["stdout_write", "assignment", "function_definition", "parameter_passing", "linked_node", "class_type"],
    "py_215": ["stdout_write", "assignment", "function_definition", "parameter_passing", "linked_node", "class_type"],
    "py_216": ["stdout_write", "assignment", "function_definition", "parameter_passing", "linked_node", "class_type"],
    "py_217": ["stdout_write", "assignment", "indexed_sequence", "graph_edges"],
    "py_218": ["stdout_write", "assignment", "indexed_sequence", "graph_edges"],
    "py_219": ["stdout_write", "assignment", "indexed_sequence", "graph_edges"],
    "py_220": ["stdout_write", "assignment", "indexed_sequence", "graph_edges"],
    "py_221": ["stdout_write", "assignment", "indexed_sequence", "graph_edges"],
    "py_222": ["stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "indexed_sequence", "collection_iteration", "fold_aggregate"],
    "py_223": ["stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "indexed_sequence", "collection_iteration", "fold_aggregate"],
    "py_224": ["stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "indexed_sequence", "collection_iteration", "fold_aggregate"],
    "py_225": ["stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "indexed_sequence", "collection_iteration", "fold_aggregate"],
    "py_226": ["stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "indexed_sequence", "collection_iteration", "fold_aggregate"],
    "py_227": ["stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "indexed_sequence", "collection_iteration", "fold_aggregate"],
    "py_228": ["stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "indexed_sequence", "collection_iteration", "fold_aggregate"],
    "py_229": ["stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "indexed_sequence", "collection_iteration", "fold_aggregate"],
    "py_230": ["stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "indexed_sequence", "collection_iteration", "fold_aggregate"],
    "py_231": ["stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "indexed_sequence", "collection_iteration", "fold_aggregate"],
    "py_232": ["stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "indexed_sequence", "collection_iteration", "fold_aggregate"],
    "py_233": ["stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "indexed_sequence", "collection_iteration", "fold_aggregate"],
    "py_234": ["stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "indexed_sequence", "collection_iteration", "fold_aggregate"],
    "py_235": ["stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "indexed_sequence", "collection_iteration", "fold_aggregate"],
    "py_236": ["stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "indexed_sequence", "collection_iteration", "fold_aggregate"],
    "py_237": ["stdout_write", "assignment", "arithmetic_ops", "function_definition", "return_flow", "parameter_passing", "recursion", "class_type", "method_dispatch"],
    "py_238": ["stdout_write", "assignment", "arithmetic_ops", "function_definition", "return_flow", "parameter_passing", "recursion", "class_type", "method_dispatch"],
    "py_239": ["stdout_write", "assignment", "arithmetic_ops", "function_definition", "return_flow", "parameter_passing", "recursion", "class_type", "method_dispatch"],
    "py_240": ["stdout_write", "assignment", "arithmetic_ops", "function_definition", "return_flow", "parameter_passing", "recursion", "class_type", "method_dispatch"],
    "py_241": ["stdout_write", "assignment", "arithmetic_ops", "function_definition", "return_flow", "parameter_passing", "recursion", "class_type", "method_dispatch"],
    "py_242": ["stdout_write", "assignment", "arithmetic_ops", "function_definition", "return_flow", "parameter_passing", "recursion", "class_type", "method_dispatch"],
    "py_243": ["stdout_write", "assignment", "arithmetic_ops", "function_definition", "return_flow", "parameter_passing", "recursion", "class_type", "method_dispatch"],
    "py_244": ["stdout_write", "assignment", "arithmetic_ops", "function_definition", "return_flow", "parameter_passing", "recursion", "class_type", "method_dispatch"],
    "py_245": ["stdout_write", "assignment", "arithmetic_ops", "function_definition", "return_flow", "parameter_passing", "recursion", "class_type", "method_dispatch"],
    "py_246": ["stdout_write", "assignment", "arithmetic_ops", "function_definition", "return_flow", "parameter_passing", "recursion", "class_type", "method_dispatch"],
    "py_247": ["stdout_write", "assignment", "arithmetic_ops", "function_definition", "return_flow", "parameter_passing", "recursion", "class_type", "method_dispatch"],
    "py_248": ["stdout_write", "assignment", "arithmetic_ops", "function_definition", "return_flow", "parameter_passing", "recursion", "class_type", "method_dispatch"],
    "py_249": ["stdout_write", "assignment", "arithmetic_ops", "function_definition", "return_flow", "parameter_passing", "recursion", "class_type", "method_dispatch"],
    "py_250": ["stdout_write", "assignment", "arithmetic_ops", "function_definition", "return_flow", "parameter_passing", "recursion", "class_type", "method_dispatch"],
    "py_251": ["stdout_write", "assignment", "arithmetic_ops", "function_definition", "return_flow", "parameter_passing", "recursion", "class_type", "method_dispatch"],
    "py_252": ["stdout_write", "assignment", "arithmetic_ops", "function_definition", "return_flow", "parameter_passing", "recursion", "class_type", "method_dispatch"],
    "py_253": ["stdout_write", "assignment", "arithmetic_ops", "function_definition", "return_flow", "parameter_passing", "recursion", "class_type", "method_dispatch"],
    "py_254": ["stdout_write", "assignment", "arithmetic_ops", "function_definition", "return_flow", "parameter_passing", "recursion", "class_type", "method_dispatch"],
    "py_255": ["stdout_write", "assignment", "arithmetic_ops", "function_definition", "return_flow", "parameter_passing", "recursion", "class_type", "method_dispatch"],
    "py_256": ["stdout_write", "assignment", "arithmetic_ops", "function_definition", "return_flow", "parameter_passing", "recursion", "class_type", "method_dispatch"],
    "py_257": ["stdout_write", "assignment", "arithmetic_ops", "function_definition", "return_flow", "parameter_passing", "recursion", "class_type", "method_dispatch"],
    "py_258": ["stdout_write", "assignment", "arithmetic_ops", "function_definition", "return_flow", "parameter_passing", "recursion", "class_type", "method_dispatch"],
    "py_259": ["stdout_write", "assignment", "arithmetic_ops", "function_definition", "return_flow", "parameter_passing", "recursion", "class_type", "method_dispatch"],
    "py_260": ["stdout_write", "assignment", "arithmetic_ops", "function_definition", "return_flow", "parameter_passing", "recursion", "class_type", "method_dispatch"],
    "py_261": ["stdout_write", "assignment", "counted_loop", "indexed_sequence", "collection_iteration", "function_definition", "return_flow", "parameter_passing", "recursion", "class_type", "method_dispatch"],
    "py_262": ["stdout_write", "assignment", "counted_loop", "indexed_sequence", "collection_iteration", "function_definition", "return_flow", "parameter_passing", "recursion", "class_type", "method_dispatch"],
    "py_263": ["stdout_write", "assignment", "counted_loop", "indexed_sequence", "collection_iteration", "function_definition", "return_flow", "parameter_passing", "recursion", "class_type", "method_dispatch"],
    "py_264": ["stdout_write", "assignment", "counted_loop", "indexed_sequence", "collection_iteration", "function_definition", "return_flow", "parameter_passing", "recursion", "class_type", "method_dispatch"],
    "py_265": ["stdout_write", "assignment", "counted_loop", "indexed_sequence", "collection_iteration", "function_definition", "return_flow", "parameter_passing", "recursion", "class_type", "method_dispatch"],
    "py_266": ["stdout_write", "assignment", "counted_loop", "indexed_sequence", "collection_iteration", "function_definition", "return_flow", "parameter_passing", "recursion", "class_type", "method_dispatch"],
    "py_267": ["stdout_write", "assignment", "counted_loop", "indexed_sequence", "collection_iteration", "function_definition", "return_flow", "parameter_passing", "recursion", "class_type", "method_dispatch"],
    "py_268": ["stdout_write", "assignment", "counted_loop", "indexed_sequence", "collection_iteration", "function_definition", "return_flow", "parameter_passing", "recursion", "class_type", "method_dispatch"],
    "py_269": ["stdout_write", "assignment", "counted_loop", "indexed_sequence", "collection_iteration", "function_definition", "return_flow", "parameter_passing", "recursion", "class_type", "method_dispatch"],
    "py_270": ["stdout_write", "assignment", "counted_loop", "indexed_sequence", "collection_iteration", "function_definition", "return_flow", "parameter_passing", "recursion", "class_type", "method_dispatch"],

}
SLOT_OVERRIDES.update(_V4_SLOT_OVERRIDES)
