"""Per-task × per-language expected technical concepts — chapter 2 branches."""

from __future__ import annotations

AUTHORING_LANGS: tuple[str, ...] = ("pascal", "python", "cpp", "csharp", "java")

_BASE_IMPORT: tuple[str, ...] = (
    "program_entry",
    "import_dependency",
    "typed_declaration",
    "assignment",
    "stdin_read",
    "stdout_write",
)

CH2_EXPECTED_CONCEPTS: dict[str, dict[str, list[str]]] = {
    "task_009": {
        "pascal": [
            "program_entry",
            "typed_declaration",
            "assignment",
            "stdin_read",
            "stdout_write",
            "simple_branch",
        ],
        "python": [
            "program_entry",
            "assignment",
            "stdin_read",
            "stdout_write",
            "simple_branch",
        ],
        "cpp": [
            "program_entry",
            "import_dependency",
            "typed_declaration",
            "assignment",
            "stdin_read",
            "stdout_write",
            "simple_branch",
        ],
        "csharp": [
            "program_entry",
            "import_dependency",
            "typed_declaration",
            "assignment",
            "stdin_read",
            "stdout_write",
            "simple_branch",
        ],
        "java": [
            "program_entry",
            "import_dependency",
            "typed_declaration",
            "assignment",
            "stdin_read",
            "stdout_write",
            "simple_branch",
        ],
    },
    "task_010": {
        "pascal": [
            "program_entry",
            "typed_declaration",
            "stdin_read",
            "stdout_write",
            "multi_branch",
        ],
        "python": [
            "program_entry",
            "assignment",
            "stdin_read",
            "stdout_write",
            "multi_branch",
        ],
        "cpp": [
            "program_entry",
            "import_dependency",
            "typed_declaration",
            "stdin_read",
            "stdout_write",
            "multi_branch",
        ],
        "csharp": [
            "program_entry",
            "import_dependency",
            "typed_declaration",
            "stdin_read",
            "stdout_write",
            "multi_branch",
        ],
        "java": [
            "program_entry",
            "import_dependency",
            "typed_declaration",
            "stdin_read",
            "stdout_write",
            "multi_branch",
        ],
    },
    "task_011": {
        "pascal": [
            "program_entry",
            "typed_declaration",
            "stdin_read",
            "stdout_write",
            "multi_branch",
        ],
        "python": [
            "program_entry",
            "assignment",
            "stdin_read",
            "stdout_write",
            "multi_branch",
        ],
        "cpp": [
            "program_entry",
            "import_dependency",
            "typed_declaration",
            "stdin_read",
            "stdout_write",
            "multi_branch",
        ],
        "csharp": [
            "program_entry",
            "import_dependency",
            "typed_declaration",
            "stdin_read",
            "stdout_write",
            "multi_branch",
        ],
        "java": [
            "program_entry",
            "import_dependency",
            "typed_declaration",
            "stdin_read",
            "stdout_write",
            "multi_branch",
        ],
    },
    "task_012": {
        "pascal": [
            "program_entry",
            "typed_declaration",
            "stdin_read",
            "stdout_write",
            "multi_branch",
            "arithmetic_ops",
        ],
        "python": [
            "program_entry",
            "assignment",
            "stdin_read",
            "stdout_write",
            "multi_branch",
            "arithmetic_ops",
        ],
        "cpp": [
            "program_entry",
            "import_dependency",
            "typed_declaration",
            "assignment",
            "stdin_read",
            "stdout_write",
            "multi_branch",
            "arithmetic_ops",
        ],
        "csharp": [
            "program_entry",
            "import_dependency",
            "typed_declaration",
            "assignment",
            "stdin_read",
            "stdout_write",
            "multi_branch",
            "arithmetic_ops",
        ],
        "java": [
            "program_entry",
            "import_dependency",
            "typed_declaration",
            "assignment",
            "stdin_read",
            "stdout_write",
            "multi_branch",
            "arithmetic_ops",
        ],
    },
    "task_013": {
        "pascal": [
            "program_entry",
            "typed_declaration",
            "stdin_read",
            "stdout_write",
            "multi_branch",
        ],
        "python": [
            "program_entry",
            "assignment",
            "stdin_read",
            "stdout_write",
            "multi_branch",
        ],
        "cpp": [
            "program_entry",
            "import_dependency",
            "typed_declaration",
            "stdin_read",
            "stdout_write",
            "multi_branch",
        ],
        "csharp": [
            "program_entry",
            "import_dependency",
            "typed_declaration",
            "stdin_read",
            "stdout_write",
            "multi_branch",
        ],
        "java": [
            "program_entry",
            "import_dependency",
            "typed_declaration",
            "stdin_read",
            "stdout_write",
            "multi_branch",
        ],
    },
    "task_014": {
        "pascal": [
            "program_entry",
            "typed_declaration",
            "stdin_read",
            "stdout_write",
            "switch_selection",
        ],
        "python": [
            "program_entry",
            "assignment",
            "stdin_read",
            "stdout_write",
            "multi_branch",
        ],
        "cpp": [
            "program_entry",
            "import_dependency",
            "typed_declaration",
            "stdin_read",
            "stdout_write",
            "switch_selection",
        ],
        "csharp": [
            "program_entry",
            "import_dependency",
            "typed_declaration",
            "stdin_read",
            "stdout_write",
            "switch_selection",
        ],
        "java": [
            "program_entry",
            "import_dependency",
            "typed_declaration",
            "stdin_read",
            "stdout_write",
            "switch_selection",
        ],
    },
    "task_015": {
        "pascal": [
            "program_entry",
            "typed_declaration",
            "stdin_read",
            "stdout_write",
            "multi_branch",
            "arithmetic_ops",
        ],
        "python": [
            "program_entry",
            "assignment",
            "stdin_read",
            "stdout_write",
            "multi_branch",
            "arithmetic_ops",
        ],
        "cpp": [
            "program_entry",
            "import_dependency",
            "typed_declaration",
            "assignment",
            "stdin_read",
            "stdout_write",
            "multi_branch",
            "arithmetic_ops",
        ],
        "csharp": [
            "program_entry",
            "import_dependency",
            "typed_declaration",
            "assignment",
            "stdin_read",
            "stdout_write",
            "multi_branch",
            "arithmetic_ops",
        ],
        "java": [
            "program_entry",
            "import_dependency",
            "typed_declaration",
            "assignment",
            "stdin_read",
            "stdout_write",
            "multi_branch",
            "arithmetic_ops",
        ],
    },
    "task_016": {
        "pascal": [
            "program_entry",
            "typed_declaration",
            "stdin_read",
            "stdout_write",
            "multi_branch",
            "arithmetic_ops",
        ],
        "python": [
            "program_entry",
            "assignment",
            "stdin_read",
            "stdout_write",
            "multi_branch",
            "arithmetic_ops",
        ],
        "cpp": [
            "program_entry",
            "import_dependency",
            "typed_declaration",
            "stdin_read",
            "stdout_write",
            "multi_branch",
            "arithmetic_ops",
        ],
        "csharp": [
            "program_entry",
            "import_dependency",
            "typed_declaration",
            "stdin_read",
            "stdout_write",
            "multi_branch",
            "arithmetic_ops",
        ],
        "java": [
            "program_entry",
            "import_dependency",
            "typed_declaration",
            "stdin_read",
            "stdout_write",
            "multi_branch",
            "arithmetic_ops",
        ],
    },
}


def chapter2_expected_concepts_for_pattern(pattern_key: str | None) -> dict[str, list[str]]:
    key = str(pattern_key or "").strip()
    raw = CH2_EXPECTED_CONCEPTS.get(key) or {}
    return {lang: list(ids) for lang, ids in raw.items() if ids}
