"""Expected concept ids for C++ Course v1 tasks."""

from __future__ import annotations

CHAPTER_DEFAULTS: dict[str, list[str]] = {
    "cpp_entry": ["program_entry"],
    "cpp_types": ["typed_declaration", "assignment"],
    "cpp_io": ["stdin_read", "stdout_write"],
    "cpp_expr": ["arithmetic_ops"],
    "cpp_cond": ["simple_branch", "multi_branch"],
    "cpp_loops": ["counted_loop", "pre_condition_loop"],
    "cpp_functions": ["function_definition", "return_flow"],
    "cpp_params": ["parameter_passing", "pass_by_reference"],
    "cpp_arrays": ["indexed_sequence", "zero_based_index"],
    "cpp_vector": ["dynamic_array", "push_back"],
    "cpp_string": ["string_sequence", "string_ops"],
    "cpp_pointers": ["reference_semantics", "dynamic_allocation"],
    "cpp_files": ["file_read", "file_write"],
    "cpp_headers": ["import_dependency", "module_namespace"],
    "cpp_recursion": ["recursion"],
    "cpp_oop": ["class_type", "inheritance_hierarchy"],
    "cpp_pitfalls": ["assignment", "pitfalls"],
    "cpp_diagnostics": ["typed_declaration", "diagnostics"],
    "cpp_preprocessor": ["preprocessor_directives"],
    "cpp_templates": ["templates"],
    "cpp_enums": ["enum_class"],
    "cpp_stl_associative": ["stl_containers", "key_value_map"],
    "cpp_stl_algorithms": ["stl_algorithms"],
    "cpp_move": ["move_semantics"],
    "cpp_exceptions": ["exceptions"],
    "cpp_capstones": ["program_entry"],
}

SLOT_OVERRIDES: dict[str, list[str]] = {
    "cpk_02": ["program_entry"],
    "cpt_02": ["assignment"],
    "cpt_14": ["typed_declaration"],
    "cpt_15": ["typed_declaration"],
    "cpi_10": ["stdin_read"],
    "cpe_10": ["arithmetic_ops"],
    "cpe_11": ["arithmetic_ops", "stdout_write"],
    "cpc_05": ["switch_selection"],
    "cpc_08": ["switch_selection"],
    "cpc_10": ["switch_selection"],
    "cpc_15": ["switch_selection"],
    "cpl_06": ["post_condition_loop"],
    "cpl_07": ["post_condition_loop"],
    "cpl_08": ["post_condition_loop"],
    "cpl_15": ["counted_loop"],
    "cpfn_05": ["function_definition"],
    "cpfn_15": ["function_definition"],
    "cpp_02": ["pass_by_reference"],
    "cpp_06": ["pass_by_reference"],
    "cpp_07": ["pass_by_reference"],
    "cpp_15": ["parameter_passing", "pass_by_reference"],
    "cpp_16": ["pass_by_reference"],
    "cpp_17": ["pass_by_reference"],
    "cpa_03": ["zero_based_index"],
    "cpa_09": ["indexed_sequence"],
    "cpa_15": ["indexed_sequence"],
    "cpa_16": ["pointers"],
    "cpd_15": ["push_back"],
    "cpd_16": ["dynamic_array"],
    "cps_03": ["string_ops", "zero_based_index"],
    "cps_15": ["string_sequence"],
    "cps_16": ["string_ops"],
    "cppt_08": ["references", "pointers"],
    "cppt_09": ["pointers", "references"],
    "cppt_10": ["unique_ptr", "raii"],
    "cppt_11": ["raii", "unique_ptr"],
    "cppt_13": ["unique_ptr", "raii"],
    "cppt_14": ["unique_ptr", "move_semantics"],
    "cppt_15": ["unique_ptr", "raii"],
    "cppt_16": ["unique_ptr", "pointers"],
    "cpo_05": ["inheritance_hierarchy"],
    "cpo_06": ["inheritance_hierarchy"],
    "cpo_15": ["inheritance_hierarchy"],
    "cpo_18": ["inheritance_hierarchy"],
}

from application.curriculum.cpp.catalog.cpp_v311_capstone_catalog import capstone_expected_concepts

SLOT_OVERRIDES.update(dict(capstone_expected_concepts()))


def expected_concept_ids_for_row(
    slot_id: str,
    chapter_key: str,
    *,
    _features: str = "",
) -> list[str]:
    override = SLOT_OVERRIDES.get(slot_id)
    if override:
        return list(override)
    return list(CHAPTER_DEFAULTS.get(chapter_key, ["program_entry"]))


# v4 chapter defaults (new chapters for unified catalog)
_V4_CHAPTER_DEFAULTS: dict[str, list[str]] = {
    "program_skeleton": ["program_entry", "stdout_write"],
    "conditions_multi": ["multi_branch", "switch_selection"],
    "loops_adv":        ["loop_control", "nested_iteration"],
    "algorithms":       ["search_find", "filter_select", "fold_aggregate"],
    "sorting":          ["sort_order"],
    "data_structures":  ["stack_queue", "linked_node"],
    "functional":       ["filter_select", "fold_aggregate"],
    "oop_state":        ["object_instance", "method_dispatch"],
    "oop_inherit":      ["inheritance_hierarchy", "method_dispatch"],
}
CHAPTER_DEFAULTS.update(_V4_CHAPTER_DEFAULTS)


# ── v4 task overrides (270 tasks) ────────────────────────────────────────────────
_V4_SLOT_OVERRIDES: dict[str, list[str]] = {

    "cpp_001": ["program_entry", "import_dependency", "stdout_write"],
    "cpp_002": ["typed_declaration", "stdout_write", "assignment"],
    "cpp_003": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops"],
    "cpp_004": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops"],
    "cpp_005": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops"],
    "cpp_006": ["typed_declaration", "stdout_write", "assignment"],
    "cpp_007": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops"],
    "cpp_008": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops"],
    "cpp_009": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops"],
    "cpp_010": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops"],
    "cpp_011": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops"],
    "cpp_012": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops"],
    "cpp_013": ["typed_declaration", "stdin_read", "stdout_write", "arithmetic_ops"],
    "cpp_014": ["typed_declaration", "stdin_read", "stdout_write", "string_sequence"],
    "cpp_015": ["typed_declaration", "stdin_read", "stdout_write", "arithmetic_ops"],
    "cpp_016": ["typed_declaration", "stdin_read", "stdout_write", "arithmetic_ops"],
    "cpp_017": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops"],
    "cpp_018": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops"],
    "cpp_019": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops"],
    "cpp_020": ["typed_declaration", "stdin_read", "stdout_write", "arithmetic_ops"],
    "cpp_021": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops"],
    "cpp_022": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "string_sequence", "function_invocation"],
    "cpp_023": ["typed_declaration", "stdin_read", "stdout_write", "arithmetic_ops"],
    "cpp_024": ["typed_declaration", "stdin_read", "stdout_write", "arithmetic_ops"],
    "cpp_025": ["typed_declaration", "stdin_read", "stdout_write", "conditional_expression"],
    "cpp_026": ["typed_declaration", "stdin_read", "stdout_write", "arithmetic_ops", "conditional_expression"],
    "cpp_027": ["typed_declaration", "stdin_read", "stdout_write", "conditional_expression"],
    "cpp_028": ["typed_declaration", "stdin_read", "stdout_write", "conditional_expression"],
    "cpp_029": ["typed_declaration", "stdin_read", "stdout_write", "conditional_expression"],
    "cpp_030": ["typed_declaration", "stdin_read", "stdout_write", "conditional_expression"],
    "cpp_031": ["typed_declaration", "stdin_read", "stdout_write", "conditional_expression", "string_sequence"],
    "cpp_032": ["typed_declaration", "stdin_read", "stdout_write", "conditional_expression"],
    "cpp_033": ["typed_declaration", "stdin_read", "stdout_write", "arithmetic_ops", "simple_branch", "conditional_expression", "function_invocation"],
    "cpp_034": ["typed_declaration", "stdin_read", "stdout_write", "conditional_expression"],
    "cpp_035": ["typed_declaration", "stdin_read", "stdout_write", "conditional_expression"],
    "cpp_036": ["typed_declaration", "stdin_read", "stdout_write", "conditional_expression"],
    "cpp_037": ["typed_declaration", "stdin_read", "stdout_write", "conditional_expression"],
    "cpp_038": ["typed_declaration", "stdin_read", "stdout_write", "conditional_expression"],
    "cpp_039": ["typed_declaration", "stdin_read", "stdout_write", "simple_branch", "conditional_expression", "function_invocation"],
    "cpp_040": ["typed_declaration", "stdin_read", "stdout_write", "multi_branch", "switch_selection", "loop_control", "function_invocation"],
    "cpp_041": ["typed_declaration", "stdin_read", "stdout_write", "multi_branch", "switch_selection", "loop_control", "function_invocation"],
    "cpp_042": ["typed_declaration", "stdin_read", "stdout_write", "multi_branch", "switch_selection", "loop_control", "function_invocation"],
    "cpp_043": ["typed_declaration", "stdin_read", "stdout_write", "simple_branch", "conditional_expression", "function_invocation"],
    "cpp_044": ["b", "switch", "break", "break", "break"],
    "cpp_045": ["typed_declaration", "stdin_read", "stdout_write", "multi_branch", "switch_selection", "loop_control", "function_invocation"],
    "cpp_046": ["typed_declaration", "stdin_read", "stdout_write", "simple_branch", "conditional_expression", "function_invocation"],
    "cpp_047": ["typed_declaration", "stdin_read", "stdout_write", "simple_branch", "conditional_expression", "function_invocation"],
    "cpp_048": ["typed_declaration", "stdin_read", "stdout_write", "simple_branch", "conditional_expression", "function_invocation"],
    "cpp_049": ["typed_declaration", "stdin_read", "stdout_write", "multi_branch", "switch_selection", "loop_control", "function_invocation"],
    "cpp_050": ["typed_declaration", "stdin_read", "stdout_write", "multi_branch", "switch_selection", "loop_control", "function_invocation"],
    "cpp_051": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "function_invocation"],
    "cpp_052": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "function_invocation"],
    "cpp_053": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "function_invocation"],
    "cpp_054": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "function_invocation"],
    "cpp_055": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "function_invocation"],
    "cpp_056": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "function_invocation"],
    "cpp_057": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "function_invocation"],
    "cpp_058": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "function_invocation"],
    "cpp_059": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "function_invocation"],
    "cpp_060": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "function_invocation"],
    "cpp_061": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "function_invocation"],
    "cpp_062": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "function_invocation"],
    "cpp_063": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "pre_condition_loop", "function_invocation"],
    "cpp_064": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "pre_condition_loop", "function_invocation"],
    "cpp_065": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "function_invocation"],
    "cpp_066": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "function_invocation"],
    "cpp_067": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "function_invocation"],
    "cpp_068": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "function_invocation"],
    "cpp_069": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "function_invocation"],
    "cpp_070": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "function_invocation"],
    "cpp_071": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "function_invocation"],
    "cpp_072": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "function_invocation"],
    "cpp_073": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "function_invocation"],
    "cpp_074": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "function_invocation"],
    "cpp_075": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "function_invocation"],
    "cpp_076": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "function_invocation"],
    "cpp_077": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "function_invocation"],
    "cpp_078": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "function_invocation"],
    "cpp_079": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "dynamic_array", "function_invocation"],
    "cpp_080": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "dynamic_array", "function_invocation"],
    "cpp_081": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "dynamic_array", "function_invocation"],
    "cpp_082": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "dynamic_array", "function_invocation"],
    "cpp_083": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "dynamic_array", "function_invocation"],
    "cpp_084": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "dynamic_array", "function_invocation"],
    "cpp_085": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "dynamic_array", "function_invocation"],
    "cpp_086": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "dynamic_array", "function_invocation"],
    "cpp_087": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "dynamic_array", "function_invocation"],
    "cpp_088": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "dynamic_array", "function_invocation"],
    "cpp_089": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "dynamic_array", "function_invocation"],
    "cpp_090": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "dynamic_array", "function_invocation"],
    "cpp_091": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "dynamic_array", "function_invocation"],
    "cpp_092": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "dynamic_array", "function_invocation"],
    "cpp_093": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "dynamic_array", "function_invocation"],
    "cpp_094": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "dynamic_array", "function_invocation"],
    "cpp_095": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "dynamic_array", "function_invocation"],
    "cpp_096": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "dynamic_array", "function_invocation"],
    "cpp_097": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "dynamic_array", "function_invocation"],
    "cpp_098": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "dynamic_array", "function_invocation"],
    "cpp_099": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "dynamic_array", "function_invocation"],
    "cpp_100": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "dynamic_array", "function_invocation"],
    "cpp_101": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "dynamic_array", "function_invocation"],
    "cpp_102": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "dynamic_array", "function_invocation"],
    "cpp_103": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "dynamic_array", "function_invocation"],
    "cpp_104": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "dynamic_array", "function_invocation"],
    "cpp_105": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "dynamic_array", "function_invocation"],
    "cpp_106": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "dynamic_array", "function_invocation"],
    "cpp_107": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "dynamic_array", "function_invocation"],
    "cpp_108": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "counted_loop", "nested_iteration", "indexed_sequence", "collection_iteration", "dynamic_array", "function_invocation"],
    "cpp_109": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "collection_iteration", "string_sequence", "function_invocation"],
    "cpp_110": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "collection_iteration", "string_sequence", "function_invocation"],
    "cpp_111": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "collection_iteration", "string_sequence", "function_invocation"],
    "cpp_112": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "collection_iteration", "string_sequence", "function_invocation"],
    "cpp_113": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "collection_iteration", "string_sequence", "function_invocation"],
    "cpp_114": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "collection_iteration", "string_sequence", "function_invocation"],
    "cpp_115": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "collection_iteration", "string_sequence", "function_invocation"],
    "cpp_116": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "collection_iteration", "string_sequence", "function_invocation"],
    "cpp_117": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "collection_iteration", "string_sequence", "function_invocation"],
    "cpp_118": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "collection_iteration", "string_sequence", "function_invocation"],
    "cpp_119": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "collection_iteration", "string_sequence", "function_invocation"],
    "cpp_120": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "collection_iteration", "string_sequence", "function_invocation"],
    "cpp_121": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "collection_iteration", "string_sequence", "function_invocation"],
    "cpp_122": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "collection_iteration", "string_sequence", "function_invocation"],
    "cpp_123": ["typed_declaration", "stdin_read", "stdout_write", "arithmetic_ops", "function_definition", "function_invocation", "return_flow", "parameter_passing", "recursion"],
    "cpp_124": ["typed_declaration", "stdin_read", "stdout_write", "arithmetic_ops", "function_definition", "function_invocation", "return_flow", "parameter_passing", "recursion"],
    "cpp_125": ["typed_declaration", "stdin_read", "stdout_write", "arithmetic_ops", "function_definition", "function_invocation", "return_flow", "parameter_passing", "recursion"],
    "cpp_126": ["typed_declaration", "stdin_read", "stdout_write", "arithmetic_ops", "function_definition", "function_invocation", "return_flow", "parameter_passing", "recursion"],
    "cpp_127": ["typed_declaration", "stdin_read", "stdout_write", "arithmetic_ops", "function_definition", "function_invocation", "return_flow", "parameter_passing", "recursion"],
    "cpp_128": ["typed_declaration", "stdin_read", "stdout_write", "arithmetic_ops", "function_definition", "function_invocation", "return_flow", "parameter_passing", "recursion"],
    "cpp_129": ["typed_declaration", "stdin_read", "stdout_write", "arithmetic_ops", "function_definition", "function_invocation", "return_flow", "parameter_passing", "recursion"],
    "cpp_130": ["typed_declaration", "stdin_read", "stdout_write", "arithmetic_ops", "function_definition", "function_invocation", "return_flow", "parameter_passing", "recursion"],
    "cpp_131": ["typed_declaration", "stdin_read", "stdout_write", "arithmetic_ops", "function_definition", "function_invocation", "return_flow", "parameter_passing", "recursion"],
    "cpp_132": ["typed_declaration", "stdin_read", "stdout_write", "arithmetic_ops", "function_definition", "function_invocation", "return_flow", "parameter_passing", "recursion"],
    "cpp_133": ["typed_declaration", "stdin_read", "stdout_write", "arithmetic_ops", "function_definition", "function_invocation", "return_flow", "parameter_passing", "recursion"],
    "cpp_134": ["typed_declaration", "stdin_read", "stdout_write", "arithmetic_ops", "function_definition", "function_invocation", "return_flow", "parameter_passing", "recursion"],
    "cpp_135": ["typed_declaration", "stdin_read", "stdout_write", "arithmetic_ops", "function_definition", "function_invocation", "return_flow", "parameter_passing", "recursion"],
    "cpp_136": ["typed_declaration", "stdin_read", "stdout_write", "arithmetic_ops", "function_definition", "function_invocation", "return_flow", "parameter_passing", "recursion"],
    "cpp_137": ["typed_declaration", "stdin_read", "stdout_write", "arithmetic_ops", "function_definition", "function_invocation", "return_flow", "parameter_passing", "recursion"],
    "cpp_138": ["typed_declaration", "stdin_read", "stdout_write", "arithmetic_ops", "function_definition", "function_invocation", "return_flow", "parameter_passing", "recursion"],
    "cpp_139": ["typed_declaration", "stdin_read", "stdout_write", "arithmetic_ops", "function_definition", "function_invocation", "return_flow", "parameter_passing", "recursion"],
    "cpp_140": ["typed_declaration", "stdin_read", "stdout_write", "arithmetic_ops", "function_definition", "function_invocation", "return_flow", "parameter_passing", "recursion"],
    "cpp_141": ["typed_declaration", "stdout_write", "arithmetic_ops", "conditional_expression", "function_definition", "function_invocation", "return_flow", "parameter_passing", "recursion"],
    "cpp_142": ["typed_declaration", "stdout_write", "arithmetic_ops", "conditional_expression", "function_definition", "function_invocation", "return_flow", "parameter_passing", "recursion"],
    "cpp_143": ["typed_declaration", "stdout_write", "arithmetic_ops", "conditional_expression", "function_definition", "function_invocation", "return_flow", "parameter_passing", "recursion"],
    "cpp_144": ["typed_declaration", "stdout_write", "arithmetic_ops", "conditional_expression", "function_definition", "function_invocation", "return_flow", "parameter_passing", "recursion"],
    "cpp_145": ["typed_declaration", "stdout_write", "arithmetic_ops", "conditional_expression", "function_definition", "function_invocation", "return_flow", "parameter_passing", "recursion"],
    "cpp_146": ["typed_declaration", "stdout_write", "arithmetic_ops", "conditional_expression", "function_definition", "function_invocation", "return_flow", "parameter_passing", "recursion"],
    "cpp_147": ["typed_declaration", "stdout_write", "arithmetic_ops", "conditional_expression", "function_definition", "function_invocation", "return_flow", "parameter_passing", "recursion"],
    "cpp_148": ["typed_declaration", "stdout_write", "arithmetic_ops", "conditional_expression", "function_definition", "function_invocation", "return_flow", "parameter_passing", "recursion"],
    "cpp_149": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "indexed_sequence", "collection_iteration", "dynamic_array", "function_invocation"],
    "cpp_150": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "indexed_sequence", "collection_iteration", "dynamic_array", "function_invocation"],
    "cpp_151": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "indexed_sequence", "collection_iteration", "dynamic_array", "function_invocation"],
    "cpp_152": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "indexed_sequence", "collection_iteration", "dynamic_array", "function_invocation"],
    "cpp_153": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "indexed_sequence", "collection_iteration", "dynamic_array", "function_invocation"],
    "cpp_154": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "indexed_sequence", "collection_iteration", "dynamic_array", "function_invocation"],
    "cpp_155": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "indexed_sequence", "collection_iteration", "dynamic_array", "function_invocation"],
    "cpp_156": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "indexed_sequence", "collection_iteration", "dynamic_array", "function_invocation"],
    "cpp_157": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "indexed_sequence", "collection_iteration", "dynamic_array", "function_invocation"],
    "cpp_158": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "indexed_sequence", "collection_iteration", "dynamic_array", "function_invocation"],
    "cpp_159": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "indexed_sequence", "collection_iteration", "dynamic_array", "function_invocation"],
    "cpp_160": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "indexed_sequence", "collection_iteration", "dynamic_array", "function_invocation"],
    "cpp_161": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "indexed_sequence", "collection_iteration", "dynamic_array", "function_invocation"],
    "cpp_162": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "indexed_sequence", "collection_iteration", "dynamic_array", "function_invocation"],
    "cpp_163": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "indexed_sequence", "collection_iteration", "dynamic_array", "function_invocation"],
    "cpp_164": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "indexed_sequence", "collection_iteration", "dynamic_array", "function_invocation"],
    "cpp_165": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "indexed_sequence", "collection_iteration", "dynamic_array", "function_invocation"],
    "cpp_166": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "indexed_sequence", "collection_iteration", "dynamic_array", "function_invocation"],
    "cpp_167": ["typed_declaration", "stdout_write", "assignment", "counted_loop", "indexed_sequence", "collection_iteration", "dynamic_array", "function_invocation", "sort_order", "method_dispatch"],
    "cpp_168": ["typed_declaration", "stdout_write", "assignment", "counted_loop", "indexed_sequence", "collection_iteration", "dynamic_array", "function_invocation", "sort_order", "method_dispatch"],
    "cpp_169": ["typed_declaration", "stdout_write", "assignment", "counted_loop", "indexed_sequence", "collection_iteration", "dynamic_array", "function_invocation", "sort_order", "method_dispatch"],
    "cpp_170": ["typed_declaration", "stdout_write", "assignment", "counted_loop", "indexed_sequence", "collection_iteration", "dynamic_array", "function_invocation", "sort_order", "method_dispatch"],
    "cpp_171": ["typed_declaration", "stdout_write", "assignment", "counted_loop", "indexed_sequence", "collection_iteration", "dynamic_array", "function_invocation", "sort_order", "method_dispatch"],
    "cpp_172": ["typed_declaration", "stdout_write", "assignment", "counted_loop", "indexed_sequence", "collection_iteration", "dynamic_array", "function_invocation", "sort_order", "method_dispatch"],
    "cpp_173": ["typed_declaration", "stdout_write", "assignment", "counted_loop", "indexed_sequence", "collection_iteration", "dynamic_array", "function_invocation", "sort_order", "method_dispatch"],
    "cpp_174": ["typed_declaration", "stdout_write", "assignment", "counted_loop", "indexed_sequence", "collection_iteration", "dynamic_array", "function_invocation", "sort_order", "method_dispatch"],
    "cpp_175": ["typed_declaration", "stdout_write", "assignment", "counted_loop", "indexed_sequence", "collection_iteration", "dynamic_array", "function_invocation", "sort_order", "method_dispatch"],
    "cpp_176": ["typed_declaration", "stdout_write", "assignment", "counted_loop", "indexed_sequence", "collection_iteration", "dynamic_array", "function_invocation", "sort_order", "method_dispatch"],
    "cpp_177": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "indexed_sequence", "collection_iteration", "dynamic_array", "function_invocation"],
    "cpp_178": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "indexed_sequence", "collection_iteration", "dynamic_array", "function_invocation"],
    "cpp_179": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "indexed_sequence", "collection_iteration", "dynamic_array", "function_invocation"],
    "cpp_180": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "indexed_sequence", "collection_iteration", "dynamic_array", "function_invocation"],
    "cpp_181": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "indexed_sequence"],
    "cpp_182": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "indexed_sequence"],
    "cpp_183": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "indexed_sequence"],
    "cpp_184": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "indexed_sequence"],
    "cpp_185": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "indexed_sequence", "collection_iteration", "dynamic_array", "function_invocation"],
    "cpp_186": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "indexed_sequence", "collection_iteration", "dynamic_array", "function_invocation"],
    "cpp_187": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "indexed_sequence", "collection_iteration", "dynamic_array", "function_invocation"],
    "cpp_188": ["typed_declaration", "stdin_read", "stdout_write", "assignment", "indexed_sequence"],
    "cpp_189": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "pre_condition_loop", "string_sequence", "file_read"],
    "cpp_190": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "pre_condition_loop", "string_sequence", "file_read"],
    "cpp_191": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "pre_condition_loop", "string_sequence", "file_read"],
    "cpp_192": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "pre_condition_loop", "string_sequence", "file_read"],
    "cpp_193": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "pre_condition_loop", "string_sequence", "file_read"],
    "cpp_194": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "pre_condition_loop", "string_sequence", "file_read"],
    "cpp_195": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "pre_condition_loop", "string_sequence", "file_read"],
    "cpp_196": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "pre_condition_loop", "string_sequence", "file_read"],
    "cpp_197": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "pre_condition_loop", "string_sequence", "file_read"],
    "cpp_198": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "pre_condition_loop", "string_sequence", "file_read"],
    "cpp_199": ["typed_declaration", "stdout_write", "arithmetic_ops", "function_definition", "return_flow", "parameter_passing", "recursion"],
    "cpp_200": ["typed_declaration", "stdout_write", "arithmetic_ops", "function_definition", "return_flow", "parameter_passing", "recursion"],
    "cpp_201": ["typed_declaration", "stdout_write", "arithmetic_ops", "function_definition", "return_flow", "parameter_passing", "recursion"],
    "cpp_202": ["typed_declaration", "stdout_write", "arithmetic_ops", "function_definition", "return_flow", "parameter_passing", "recursion"],
    "cpp_203": ["typed_declaration", "stdout_write", "arithmetic_ops", "function_definition", "return_flow", "parameter_passing", "recursion"],
    "cpp_204": ["typed_declaration", "stdout_write", "arithmetic_ops", "function_definition", "return_flow", "parameter_passing", "recursion"],
    "cpp_205": ["typed_declaration", "stdout_write", "arithmetic_ops", "function_definition", "return_flow", "parameter_passing", "recursion"],
    "cpp_206": ["typed_declaration", "stdout_write", "arithmetic_ops", "function_definition", "return_flow", "parameter_passing", "recursion"],
    "cpp_207": ["typed_declaration", "stdout_write", "function_invocation", "stack_queue", "method_dispatch"],
    "cpp_208": ["typed_declaration", "stdout_write", "function_invocation", "stack_queue", "method_dispatch"],
    "cpp_209": ["typed_declaration", "stdout_write", "function_invocation", "stack_queue", "method_dispatch"],
    "cpp_210": ["typed_declaration", "stdout_write", "function_invocation", "stack_queue", "method_dispatch"],
    "cpp_211": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "linked_node", "lambda"],
    "cpp_212": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "linked_node", "lambda"],
    "cpp_213": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "linked_node", "lambda"],
    "cpp_214": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "linked_node", "lambda"],
    "cpp_215": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "linked_node", "lambda"],
    "cpp_216": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "linked_node", "lambda"],
    "cpp_217": ["typed_declaration", "stdout_write", "assignment", "indexed_sequence", "dynamic_array", "graph_edges"],
    "cpp_218": ["typed_declaration", "stdout_write", "assignment", "indexed_sequence", "dynamic_array", "graph_edges"],
    "cpp_219": ["typed_declaration", "stdout_write", "assignment", "indexed_sequence", "dynamic_array", "graph_edges"],
    "cpp_220": ["typed_declaration", "stdout_write", "assignment", "indexed_sequence", "dynamic_array", "graph_edges"],
    "cpp_221": ["typed_declaration", "stdout_write", "assignment", "indexed_sequence", "dynamic_array", "graph_edges"],
    "cpp_222": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "indexed_sequence", "collection_iteration", "dynamic_array", "function_invocation"],
    "cpp_223": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "indexed_sequence", "collection_iteration", "dynamic_array", "function_invocation"],
    "cpp_224": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "indexed_sequence", "collection_iteration", "dynamic_array", "function_invocation"],
    "cpp_225": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "indexed_sequence", "collection_iteration", "dynamic_array", "function_invocation"],
    "cpp_226": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "indexed_sequence", "collection_iteration", "dynamic_array", "function_invocation"],
    "cpp_227": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "indexed_sequence", "collection_iteration", "dynamic_array", "function_invocation"],
    "cpp_228": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "indexed_sequence", "collection_iteration", "dynamic_array", "function_invocation"],
    "cpp_229": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "indexed_sequence", "collection_iteration", "dynamic_array", "function_invocation"],
    "cpp_230": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "indexed_sequence", "collection_iteration", "dynamic_array", "function_invocation"],
    "cpp_231": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "indexed_sequence", "collection_iteration", "dynamic_array", "function_invocation"],
    "cpp_232": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "indexed_sequence", "collection_iteration", "dynamic_array", "function_invocation"],
    "cpp_233": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "indexed_sequence", "collection_iteration", "dynamic_array", "function_invocation"],
    "cpp_234": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "indexed_sequence", "collection_iteration", "dynamic_array", "function_invocation"],
    "cpp_235": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "indexed_sequence", "collection_iteration", "dynamic_array", "function_invocation"],
    "cpp_236": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "simple_branch", "counted_loop", "indexed_sequence", "collection_iteration", "dynamic_array", "function_invocation"],
    "cpp_237": ["typed_declaration", "stdout_write", "arithmetic_ops", "string_sequence", "function_definition", "function_invocation", "return_flow", "parameter_passing", "recursion", "class_type", "method_dispatch"],
    "cpp_238": ["typed_declaration", "stdout_write", "arithmetic_ops", "string_sequence", "function_definition", "function_invocation", "return_flow", "parameter_passing", "recursion", "class_type", "method_dispatch"],
    "cpp_239": ["typed_declaration", "stdout_write", "arithmetic_ops", "string_sequence", "function_definition", "function_invocation", "return_flow", "parameter_passing", "recursion", "class_type", "method_dispatch"],
    "cpp_240": ["typed_declaration", "stdout_write", "arithmetic_ops", "string_sequence", "function_definition", "function_invocation", "return_flow", "parameter_passing", "recursion", "class_type", "method_dispatch"],
    "cpp_241": ["typed_declaration", "stdout_write", "arithmetic_ops", "string_sequence", "function_definition", "function_invocation", "return_flow", "parameter_passing", "recursion", "class_type", "method_dispatch"],
    "cpp_242": ["typed_declaration", "stdout_write", "arithmetic_ops", "string_sequence", "function_definition", "function_invocation", "return_flow", "parameter_passing", "recursion", "class_type", "method_dispatch"],
    "cpp_243": ["typed_declaration", "stdout_write", "arithmetic_ops", "string_sequence", "function_definition", "function_invocation", "return_flow", "parameter_passing", "recursion", "class_type", "method_dispatch"],
    "cpp_244": ["typed_declaration", "stdout_write", "arithmetic_ops", "string_sequence", "function_definition", "function_invocation", "return_flow", "parameter_passing", "recursion", "class_type", "method_dispatch"],
    "cpp_245": ["typed_declaration", "stdout_write", "arithmetic_ops", "string_sequence", "function_definition", "function_invocation", "return_flow", "parameter_passing", "recursion", "class_type", "method_dispatch"],
    "cpp_246": ["typed_declaration", "stdout_write", "arithmetic_ops", "string_sequence", "function_definition", "function_invocation", "return_flow", "parameter_passing", "recursion", "class_type", "method_dispatch"],
    "cpp_247": ["typed_declaration", "stdout_write", "arithmetic_ops", "string_sequence", "function_definition", "function_invocation", "return_flow", "parameter_passing", "recursion", "class_type", "method_dispatch"],
    "cpp_248": ["typed_declaration", "stdout_write", "arithmetic_ops", "string_sequence", "function_definition", "function_invocation", "return_flow", "parameter_passing", "recursion", "class_type", "method_dispatch"],
    "cpp_249": ["typed_declaration", "stdout_write", "arithmetic_ops", "string_sequence", "function_definition", "function_invocation", "return_flow", "parameter_passing", "recursion", "class_type", "method_dispatch"],
    "cpp_250": ["typed_declaration", "stdout_write", "arithmetic_ops", "string_sequence", "function_definition", "function_invocation", "return_flow", "parameter_passing", "recursion", "class_type", "method_dispatch"],
    "cpp_251": ["typed_declaration", "stdout_write", "arithmetic_ops", "string_sequence", "function_definition", "function_invocation", "return_flow", "parameter_passing", "recursion", "class_type", "method_dispatch"],
    "cpp_252": ["typed_declaration", "stdout_write", "arithmetic_ops", "string_sequence", "function_definition", "function_invocation", "return_flow", "parameter_passing", "recursion", "class_type", "method_dispatch"],
    "cpp_253": ["typed_declaration", "stdout_write", "arithmetic_ops", "string_sequence", "function_definition", "function_invocation", "return_flow", "parameter_passing", "recursion", "class_type", "method_dispatch"],
    "cpp_254": ["typed_declaration", "stdout_write", "arithmetic_ops", "string_sequence", "function_definition", "function_invocation", "return_flow", "parameter_passing", "recursion", "class_type", "method_dispatch"],
    "cpp_255": ["typed_declaration", "stdout_write", "arithmetic_ops", "string_sequence", "function_definition", "function_invocation", "return_flow", "parameter_passing", "recursion", "class_type", "method_dispatch"],
    "cpp_256": ["typed_declaration", "stdout_write", "arithmetic_ops", "string_sequence", "function_definition", "function_invocation", "return_flow", "parameter_passing", "recursion", "class_type", "method_dispatch"],
    "cpp_257": ["typed_declaration", "stdout_write", "arithmetic_ops", "string_sequence", "function_definition", "function_invocation", "return_flow", "parameter_passing", "recursion", "class_type", "method_dispatch"],
    "cpp_258": ["typed_declaration", "stdout_write", "arithmetic_ops", "string_sequence", "function_definition", "function_invocation", "return_flow", "parameter_passing", "recursion", "class_type", "method_dispatch"],
    "cpp_259": ["typed_declaration", "stdout_write", "arithmetic_ops", "string_sequence", "function_definition", "function_invocation", "return_flow", "parameter_passing", "recursion", "class_type", "method_dispatch"],
    "cpp_260": ["typed_declaration", "stdout_write", "arithmetic_ops", "string_sequence", "function_definition", "function_invocation", "return_flow", "parameter_passing", "recursion", "class_type", "method_dispatch"],
    "cpp_261": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "function_definition", "function_invocation", "return_flow", "recursion", "lambda", "class_type", "inheritance_hierarchy"],
    "cpp_262": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "function_definition", "function_invocation", "return_flow", "recursion", "lambda", "class_type", "inheritance_hierarchy"],
    "cpp_263": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "function_definition", "function_invocation", "return_flow", "recursion", "lambda", "class_type", "inheritance_hierarchy"],
    "cpp_264": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "function_definition", "function_invocation", "return_flow", "recursion", "lambda", "class_type", "inheritance_hierarchy"],
    "cpp_265": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "function_definition", "function_invocation", "return_flow", "recursion", "lambda", "class_type", "inheritance_hierarchy"],
    "cpp_266": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "function_definition", "function_invocation", "return_flow", "recursion", "lambda", "class_type", "inheritance_hierarchy"],
    "cpp_267": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "function_definition", "function_invocation", "return_flow", "recursion", "lambda", "class_type", "inheritance_hierarchy"],
    "cpp_268": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "function_definition", "function_invocation", "return_flow", "recursion", "lambda", "class_type", "inheritance_hierarchy"],
    "cpp_269": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "function_definition", "function_invocation", "return_flow", "recursion", "lambda", "class_type", "inheritance_hierarchy"],
    "cpp_270": ["typed_declaration", "stdout_write", "assignment", "arithmetic_ops", "function_definition", "function_invocation", "return_flow", "recursion", "lambda", "class_type", "inheritance_hierarchy"],

}
SLOT_OVERRIDES.update(_V4_SLOT_OVERRIDES)
