"""Expected concept overrides for C++ v4 tasks."""
from __future__ import annotations

SLOT_EXPECTED_CONCEPT_OVERRIDES: dict[str, list[str]] = {
    "cpp_001": ["program_entry", "typed_declaration", "assignment", "arithmetic_ops", "stdout_write"],
    "cpp_002": ["program_entry", "typed_declaration", "assignment", "arithmetic_ops", "stdout_write"],
    "cpp_003": ["program_entry", "typed_declaration", "assignment", "arithmetic_ops", "stdout_write"],
    "cpp_004": ["program_entry", "typed_declaration", "assignment", "arithmetic_ops", "stdout_write"],
    "cpp_005": ["program_entry", "typed_declaration", "assignment", "arithmetic_ops", "stdout_write"],
    "cpp_006": ["program_entry", "typed_declaration", "assignment", "arithmetic_ops", "stdout_write"],
    "cpp_007": ["program_entry", "typed_declaration", "assignment", "arithmetic_ops", "stdout_write"],
    "cpp_008": ["program_entry", "typed_declaration", "assignment", "arithmetic_ops", "stdout_write"],
    "cpp_009": ["program_entry", "typed_declaration", "assignment", "arithmetic_ops", "stdout_write"],
    "cpp_010": ["program_entry", "typed_declaration", "assignment", "arithmetic_ops", "stdout_write"],
    "cpp_011": ["program_entry", "typed_declaration", "assignment", "arithmetic_ops", "stdout_write"],
    "cpp_012": ["program_entry", "typed_declaration", "assignment", "arithmetic_ops", "stdout_write"],
    "cpp_013": ["typed_declaration", "stdin_read", "assignment", "arithmetic_ops", "stdout_write"],
    "cpp_014": ["typed_declaration", "stdin_read", "assignment", "arithmetic_ops", "stdout_write"],
    "cpp_015": ["typed_declaration", "stdin_read", "assignment", "arithmetic_ops", "stdout_write"],
    "cpp_016": ["typed_declaration", "stdin_read", "assignment", "arithmetic_ops", "stdout_write"],
    "cpp_017": ["typed_declaration", "stdin_read", "assignment", "arithmetic_ops", "stdout_write"],
    "cpp_018": ["typed_declaration", "stdin_read", "assignment", "arithmetic_ops", "stdout_write"],
    "cpp_019": ["typed_declaration", "stdin_read", "assignment", "arithmetic_ops", "stdout_write"],
    "cpp_020": ["typed_declaration", "stdin_read", "assignment", "arithmetic_ops", "stdout_write"],
    "cpp_021": ["typed_declaration", "stdin_read", "assignment", "arithmetic_ops", "stdout_write"],
    "cpp_022": ["typed_declaration", "stdin_read", "assignment", "arithmetic_ops", "stdout_write"],
    "cpp_023": ["typed_declaration", "stdin_read", "assignment", "arithmetic_ops", "stdout_write"],
    "cpp_024": ["typed_declaration", "stdin_read", "assignment", "arithmetic_ops", "stdout_write"],
    "cpp_025": ["typed_declaration", "stdin_read", "simple_branch", "assignment", "stdout_write"],
    "cpp_026": ["typed_declaration", "stdin_read", "simple_branch", "assignment", "stdout_write"],
    "cpp_027": ["typed_declaration", "stdin_read", "simple_branch", "assignment", "stdout_write"],
    "cpp_028": ["typed_declaration", "stdin_read", "simple_branch", "assignment", "stdout_write"],
    "cpp_029": ["typed_declaration", "stdin_read", "simple_branch", "assignment", "stdout_write"],
    "cpp_030": ["typed_declaration", "stdin_read", "simple_branch", "assignment", "stdout_write"],
    "cpp_031": ["typed_declaration", "stdin_read", "simple_branch", "assignment", "stdout_write"],
    "cpp_032": ["typed_declaration", "stdin_read", "simple_branch", "assignment", "stdout_write"],
    "cpp_033": ["typed_declaration", "stdin_read", "simple_branch", "assignment", "stdout_write"],
    "cpp_034": ["typed_declaration", "stdin_read", "simple_branch", "assignment", "stdout_write"],
    "cpp_035": ["typed_declaration", "stdin_read", "simple_branch", "assignment", "stdout_write"],
    "cpp_036": ["typed_declaration", "stdin_read", "simple_branch", "assignment", "stdout_write"],
    "cpp_037": ["typed_declaration", "stdin_read", "simple_branch", "assignment", "stdout_write"],
    "cpp_038": ["typed_declaration", "stdin_read", "simple_branch", "assignment", "stdout_write"],
    "cpp_039": ["typed_declaration", "stdin_read", "simple_branch", "assignment", "stdout_write"],
    "cpp_040": ["typed_declaration", "stdin_read", "simple_branch", "assignment", "stdout_write"],
    "cpp_041": ["typed_declaration", "stdin_read", "simple_branch", "assignment", "stdout_write"],
    "cpp_042": ["typed_declaration", "stdin_read", "simple_branch", "assignment", "stdout_write"],
    "cpp_043": ["typed_declaration", "stdin_read", "simple_branch", "assignment", "stdout_write"],
    "cpp_044": ["typed_declaration", "stdin_read", "simple_branch", "assignment", "stdout_write"],
    "cpp_045": ["typed_declaration", "stdin_read", "simple_branch", "assignment", "stdout_write"],
    "cpp_046": ["typed_declaration", "stdin_read", "simple_branch", "assignment", "stdout_write"],
    "cpp_047": ["typed_declaration", "stdin_read", "simple_branch", "assignment", "stdout_write"],
    "cpp_048": ["typed_declaration", "stdin_read", "simple_branch", "assignment", "stdout_write"],
    "cpp_049": ["typed_declaration", "stdin_read", "simple_branch", "assignment", "stdout_write"],
    "cpp_050": ["typed_declaration", "stdin_read", "simple_branch", "assignment", "stdout_write"],
    "cpp_051": ["typed_declaration", "stdin_read", "counted_loop", "pre_condition_loop", "assignment", "stdout_write"],
    "cpp_052": ["typed_declaration", "stdin_read", "counted_loop", "pre_condition_loop", "assignment", "stdout_write"],
    "cpp_053": ["typed_declaration", "stdin_read", "counted_loop", "pre_condition_loop", "assignment", "stdout_write"],
    "cpp_054": ["typed_declaration", "stdin_read", "counted_loop", "pre_condition_loop", "assignment", "stdout_write"],
    "cpp_055": ["typed_declaration", "stdin_read", "counted_loop", "pre_condition_loop", "assignment", "stdout_write"],
    "cpp_056": ["typed_declaration", "stdin_read", "counted_loop", "pre_condition_loop", "assignment", "stdout_write"],
    "cpp_057": ["typed_declaration", "stdin_read", "counted_loop", "pre_condition_loop", "assignment", "stdout_write"],
    "cpp_058": ["typed_declaration", "stdin_read", "counted_loop", "pre_condition_loop", "assignment", "stdout_write"],
    "cpp_059": ["typed_declaration", "stdin_read", "counted_loop", "pre_condition_loop", "assignment", "stdout_write"],
    "cpp_060": ["typed_declaration", "stdin_read", "counted_loop", "pre_condition_loop", "assignment", "stdout_write"],
    "cpp_061": ["typed_declaration", "stdin_read", "counted_loop", "pre_condition_loop", "assignment", "stdout_write"],
    "cpp_062": ["typed_declaration", "stdin_read", "counted_loop", "pre_condition_loop", "assignment", "stdout_write"],
    "cpp_063": ["typed_declaration", "stdin_read", "counted_loop", "pre_condition_loop", "assignment", "stdout_write"],
    "cpp_064": ["typed_declaration", "stdin_read", "counted_loop", "pre_condition_loop", "assignment", "stdout_write"],
    "cpp_065": ["typed_declaration", "stdin_read", "counted_loop", "pre_condition_loop", "assignment", "stdout_write"],
    "cpp_066": ["typed_declaration", "stdin_read", "counted_loop", "pre_condition_loop", "assignment", "stdout_write"],
    "cpp_067": ["nested_iteration", "loop_control", "counted_loop", "stdout_write"],
    "cpp_068": ["nested_iteration", "loop_control", "counted_loop", "stdout_write"],
    "cpp_069": ["nested_iteration", "loop_control", "counted_loop", "stdout_write"],
    "cpp_070": ["nested_iteration", "loop_control", "counted_loop", "stdout_write"],
    "cpp_071": ["nested_iteration", "loop_control", "counted_loop", "stdout_write"],
    "cpp_072": ["nested_iteration", "loop_control", "counted_loop", "stdout_write"],
    "cpp_073": ["nested_iteration", "loop_control", "counted_loop", "stdout_write"],
    "cpp_074": ["nested_iteration", "loop_control", "counted_loop", "stdout_write"],
    "cpp_075": ["nested_iteration", "loop_control", "counted_loop", "stdout_write"],
    "cpp_076": ["nested_iteration", "loop_control", "counted_loop", "stdout_write"],
    "cpp_077": ["nested_iteration", "loop_control", "counted_loop", "stdout_write"],
    "cpp_078": ["nested_iteration", "loop_control", "counted_loop", "stdout_write"],
    "cpp_079": ["indexed_sequence", "collection_iteration", "counted_loop", "stdout_write"],
    "cpp_080": ["indexed_sequence", "collection_iteration", "counted_loop", "stdout_write"],
    "cpp_081": ["indexed_sequence", "collection_iteration", "counted_loop", "stdout_write"],
    "cpp_082": ["indexed_sequence", "collection_iteration", "counted_loop", "stdout_write"],
    "cpp_083": ["indexed_sequence", "collection_iteration", "counted_loop", "stdout_write"],
    "cpp_084": ["indexed_sequence", "collection_iteration", "counted_loop", "stdout_write"],
    "cpp_085": ["indexed_sequence", "collection_iteration", "counted_loop", "stdout_write"],
    "cpp_086": ["indexed_sequence", "collection_iteration", "counted_loop", "stdout_write"],
    "cpp_087": ["indexed_sequence", "collection_iteration", "counted_loop", "stdout_write"],
    "cpp_088": ["indexed_sequence", "collection_iteration", "counted_loop", "stdout_write"],
    "cpp_089": ["indexed_sequence", "collection_iteration", "counted_loop", "stdout_write"],
    "cpp_090": ["indexed_sequence", "collection_iteration", "counted_loop", "stdout_write"],
    "cpp_091": ["indexed_sequence", "collection_iteration", "counted_loop", "stdout_write"],
    "cpp_092": ["indexed_sequence", "collection_iteration", "counted_loop", "stdout_write"],
    "cpp_093": ["indexed_sequence", "collection_iteration", "counted_loop", "stdout_write"],
    "cpp_094": ["indexed_sequence", "collection_iteration", "counted_loop", "stdout_write"],
    "cpp_095": ["dynamic_array", "collection_iteration", "stdout_write"],
    "cpp_096": ["dynamic_array", "collection_iteration", "stdout_write"],
    "cpp_097": ["dynamic_array", "collection_iteration", "stdout_write"],
    "cpp_098": ["dynamic_array", "collection_iteration", "stdout_write"],
    "cpp_099": ["dynamic_array", "collection_iteration", "stdout_write"],
    "cpp_100": ["dynamic_array", "collection_iteration", "stdout_write"],
    "cpp_101": ["dynamic_array", "collection_iteration", "stdout_write"],
    "cpp_102": ["dynamic_array", "collection_iteration", "stdout_write"],
    "cpp_103": ["dynamic_array", "collection_iteration", "stdout_write"],
    "cpp_104": ["dynamic_array", "collection_iteration", "stdout_write"],
    "cpp_105": ["dynamic_array", "collection_iteration", "stdout_write"],
    "cpp_106": ["dynamic_array", "collection_iteration", "stdout_write"],
    "cpp_107": ["dynamic_array", "collection_iteration", "stdout_write"],
    "cpp_108": ["dynamic_array", "collection_iteration", "stdout_write"],
    "cpp_109": ["string_sequence", "collection_iteration", "simple_branch", "stdout_write"],
    "cpp_110": ["string_sequence", "collection_iteration", "simple_branch", "stdout_write"],
    "cpp_111": ["string_sequence", "collection_iteration", "simple_branch", "stdout_write"],
    "cpp_112": ["string_sequence", "collection_iteration", "simple_branch", "stdout_write"],
    "cpp_113": ["string_sequence", "collection_iteration", "simple_branch", "stdout_write"],
    "cpp_114": ["string_sequence", "collection_iteration", "simple_branch", "stdout_write"],
    "cpp_115": ["string_sequence", "collection_iteration", "simple_branch", "stdout_write"],
    "cpp_116": ["string_sequence", "collection_iteration", "simple_branch", "stdout_write"],
    "cpp_117": ["string_sequence", "collection_iteration", "simple_branch", "stdout_write"],
    "cpp_118": ["string_sequence", "collection_iteration", "simple_branch", "stdout_write"],
    "cpp_119": ["string_sequence", "collection_iteration", "simple_branch", "stdout_write"],
    "cpp_120": ["string_sequence", "collection_iteration", "simple_branch", "stdout_write"],
    "cpp_121": ["string_sequence", "collection_iteration", "simple_branch", "stdout_write"],
    "cpp_122": ["string_sequence", "collection_iteration", "simple_branch", "stdout_write"],
    "cpp_123": ["function_definition", "function_invocation", "return_flow"],
    "cpp_124": ["function_definition", "function_invocation", "return_flow"],
    "cpp_125": ["function_definition", "function_invocation", "return_flow"],
    "cpp_126": ["function_definition", "function_invocation", "return_flow"],
    "cpp_127": ["function_definition", "function_invocation", "return_flow"],
    "cpp_128": ["function_definition", "function_invocation", "return_flow"],
    "cpp_129": ["function_definition", "function_invocation", "return_flow"],
    "cpp_130": ["function_definition", "function_invocation", "return_flow"],
    "cpp_131": ["function_definition", "function_invocation", "return_flow"],
    "cpp_132": ["function_definition", "function_invocation", "return_flow"],
    "cpp_133": ["function_definition", "function_invocation", "return_flow"],
    "cpp_134": ["function_definition", "function_invocation", "return_flow"],
    "cpp_135": ["function_definition", "function_invocation", "return_flow"],
    "cpp_136": ["function_definition", "function_invocation", "return_flow"],
    "cpp_137": ["function_definition", "function_invocation", "return_flow"],
    "cpp_138": ["function_definition", "function_invocation", "return_flow"],
    "cpp_139": ["function_definition", "function_invocation", "return_flow"],
    "cpp_140": ["function_definition", "function_invocation", "return_flow"],
    "cpp_141": ["function_definition", "recursion", "simple_branch", "return_flow"],
    "cpp_142": ["function_definition", "recursion", "simple_branch", "return_flow"],
    "cpp_143": ["function_definition", "recursion", "simple_branch", "return_flow"],
    "cpp_144": ["function_definition", "recursion", "simple_branch", "return_flow"],
    "cpp_145": ["function_definition", "recursion", "simple_branch", "return_flow"],
    "cpp_146": ["function_definition", "recursion", "simple_branch", "return_flow"],
    "cpp_147": ["function_definition", "recursion", "simple_branch", "return_flow"],
    "cpp_148": ["function_definition", "recursion", "simple_branch", "return_flow"],
    "cpp_149": ["search_find", "filter_select", "fold_aggregate", "collection_iteration"],
    "cpp_150": ["search_find", "filter_select", "fold_aggregate", "collection_iteration"],
    "cpp_151": ["search_find", "filter_select", "fold_aggregate", "collection_iteration"],
    "cpp_152": ["search_find", "filter_select", "fold_aggregate", "collection_iteration"],
    "cpp_153": ["search_find", "filter_select", "fold_aggregate", "collection_iteration"],
    "cpp_154": ["search_find", "filter_select", "fold_aggregate", "collection_iteration"],
    "cpp_155": ["search_find", "filter_select", "fold_aggregate", "collection_iteration"],
    "cpp_156": ["search_find", "filter_select", "fold_aggregate", "collection_iteration"],
    "cpp_157": ["search_find", "filter_select", "fold_aggregate", "collection_iteration"],
    "cpp_158": ["search_find", "filter_select", "fold_aggregate", "collection_iteration"],
    "cpp_159": ["search_find", "filter_select", "fold_aggregate", "collection_iteration"],
    "cpp_160": ["search_find", "filter_select", "fold_aggregate", "collection_iteration"],
    "cpp_161": ["search_find", "filter_select", "fold_aggregate", "collection_iteration"],
    "cpp_162": ["search_find", "filter_select", "fold_aggregate", "collection_iteration"],
    "cpp_163": ["search_find", "filter_select", "fold_aggregate", "collection_iteration"],
    "cpp_164": ["search_find", "filter_select", "fold_aggregate", "collection_iteration"],
    "cpp_165": ["search_find", "filter_select", "fold_aggregate", "collection_iteration"],
    "cpp_166": ["search_find", "filter_select", "fold_aggregate", "collection_iteration"],
    "cpp_167": ["sort_order", "collection_iteration"],
    "cpp_168": ["sort_order", "collection_iteration"],
    "cpp_169": ["sort_order", "collection_iteration"],
    "cpp_170": ["sort_order", "collection_iteration"],
    "cpp_171": ["sort_order", "collection_iteration"],
    "cpp_172": ["sort_order", "collection_iteration"],
    "cpp_173": ["sort_order", "collection_iteration"],
    "cpp_174": ["sort_order", "collection_iteration"],
    "cpp_175": ["sort_order", "collection_iteration"],
    "cpp_176": ["sort_order", "collection_iteration"],
    "cpp_177": ["key_value_map", "search_find"],
    "cpp_178": ["key_value_map", "search_find"],
    "cpp_179": ["key_value_map", "search_find"],
    "cpp_180": ["key_value_map", "search_find"],
    "cpp_181": ["key_value_map", "search_find"],
    "cpp_182": ["key_value_map", "search_find"],
    "cpp_183": ["key_value_map", "search_find"],
    "cpp_184": ["key_value_map", "search_find"],
    "cpp_185": ["key_value_map", "search_find"],
    "cpp_186": ["key_value_map", "search_find"],
    "cpp_187": ["key_value_map", "search_find"],
    "cpp_188": ["key_value_map", "search_find"],
    "cpp_189": ["file_read", "file_write", "collection_iteration"],
    "cpp_190": ["file_read", "file_write", "collection_iteration"],
    "cpp_191": ["file_read", "file_write", "collection_iteration"],
    "cpp_192": ["file_read", "file_write", "collection_iteration"],
    "cpp_193": ["file_read", "file_write", "collection_iteration"],
    "cpp_194": ["file_read", "file_write", "collection_iteration"],
    "cpp_195": ["file_read", "file_write", "collection_iteration"],
    "cpp_196": ["file_read", "file_write", "collection_iteration"],
    "cpp_197": ["file_read", "file_write", "collection_iteration"],
    "cpp_198": ["file_read", "file_write", "collection_iteration"],
    "cpp_199": ["import_dependency", "module_namespace", "symbol_visibility"],
    "cpp_200": ["import_dependency", "module_namespace", "symbol_visibility"],
    "cpp_201": ["import_dependency", "module_namespace", "symbol_visibility"],
    "cpp_202": ["import_dependency", "module_namespace", "symbol_visibility"],
    "cpp_203": ["import_dependency", "module_namespace", "symbol_visibility"],
    "cpp_204": ["import_dependency", "module_namespace", "symbol_visibility"],
    "cpp_205": ["import_dependency", "module_namespace", "symbol_visibility"],
    "cpp_206": ["import_dependency", "module_namespace", "symbol_visibility"],
    "cpp_207": ["stack_queue", "linked_node", "tree_hierarchy", "graph_edges"],
    "cpp_208": ["stack_queue", "linked_node", "tree_hierarchy", "graph_edges"],
    "cpp_209": ["stack_queue", "linked_node", "tree_hierarchy", "graph_edges"],
    "cpp_210": ["stack_queue", "linked_node", "tree_hierarchy", "graph_edges"],
    "cpp_211": ["stack_queue", "linked_node", "tree_hierarchy", "graph_edges"],
    "cpp_212": ["stack_queue", "linked_node", "tree_hierarchy", "graph_edges"],
    "cpp_213": ["stack_queue", "linked_node", "tree_hierarchy", "graph_edges"],
    "cpp_214": ["stack_queue", "linked_node", "tree_hierarchy", "graph_edges"],
    "cpp_215": ["stack_queue", "linked_node", "tree_hierarchy", "graph_edges"],
    "cpp_216": ["stack_queue", "linked_node", "tree_hierarchy", "graph_edges"],
    "cpp_217": ["stack_queue", "linked_node", "tree_hierarchy", "graph_edges"],
    "cpp_218": ["stack_queue", "linked_node", "tree_hierarchy", "graph_edges"],
    "cpp_219": ["stack_queue", "linked_node", "tree_hierarchy", "graph_edges"],
    "cpp_220": ["stack_queue", "linked_node", "tree_hierarchy", "graph_edges"],
    "cpp_221": ["stack_queue", "linked_node", "tree_hierarchy", "graph_edges"],
    "cpp_222": ["filter_select", "fold_aggregate", "lambda"],
    "cpp_223": ["filter_select", "fold_aggregate", "lambda"],
    "cpp_224": ["filter_select", "fold_aggregate", "lambda"],
    "cpp_225": ["filter_select", "fold_aggregate", "lambda"],
    "cpp_226": ["filter_select", "fold_aggregate", "lambda"],
    "cpp_227": ["filter_select", "fold_aggregate", "lambda"],
    "cpp_228": ["filter_select", "fold_aggregate", "lambda"],
    "cpp_229": ["filter_select", "fold_aggregate", "lambda"],
    "cpp_230": ["filter_select", "fold_aggregate", "lambda"],
    "cpp_231": ["filter_select", "fold_aggregate", "lambda"],
    "cpp_232": ["filter_select", "fold_aggregate", "lambda"],
    "cpp_233": ["filter_select", "fold_aggregate", "lambda"],
    "cpp_234": ["filter_select", "fold_aggregate", "lambda"],
    "cpp_235": ["filter_select", "fold_aggregate", "lambda"],
    "cpp_236": ["filter_select", "fold_aggregate", "lambda"],
    "cpp_237": ["class_type", "object_instance", "method_dispatch"],
    "cpp_238": ["class_type", "object_instance", "method_dispatch"],
    "cpp_239": ["class_type", "object_instance", "method_dispatch"],
    "cpp_240": ["class_type", "object_instance", "method_dispatch"],
    "cpp_241": ["class_type", "object_instance", "method_dispatch"],
    "cpp_242": ["class_type", "object_instance", "method_dispatch"],
    "cpp_243": ["class_type", "object_instance", "method_dispatch"],
    "cpp_244": ["class_type", "object_instance", "method_dispatch"],
    "cpp_245": ["class_type", "object_instance", "method_dispatch"],
    "cpp_246": ["class_type", "object_instance", "method_dispatch"],
    "cpp_247": ["class_type", "object_instance", "method_dispatch"],
    "cpp_248": ["class_type", "object_instance", "method_dispatch"],
    "cpp_249": ["class_type", "object_instance", "method_dispatch"],
    "cpp_250": ["class_type", "object_instance", "method_dispatch"],
    "cpp_251": ["class_type", "object_instance", "method_dispatch"],
    "cpp_252": ["class_type", "object_instance", "method_dispatch"],
    "cpp_253": ["class_type", "object_instance", "method_dispatch"],
    "cpp_254": ["class_type", "object_instance", "method_dispatch"],
    "cpp_255": ["class_type", "object_instance", "method_dispatch"],
    "cpp_256": ["class_type", "object_instance", "method_dispatch"],
    "cpp_257": ["class_type", "object_instance", "method_dispatch"],
    "cpp_258": ["class_type", "object_instance", "method_dispatch"],
    "cpp_259": ["class_type", "object_instance", "method_dispatch"],
    "cpp_260": ["class_type", "object_instance", "method_dispatch"],
    "cpp_261": ["class_type", "object_instance", "method_dispatch", "inheritance_hierarchy"],
    "cpp_262": ["class_type", "object_instance", "method_dispatch", "inheritance_hierarchy"],
    "cpp_263": ["class_type", "object_instance", "method_dispatch", "inheritance_hierarchy"],
    "cpp_264": ["class_type", "object_instance", "method_dispatch", "inheritance_hierarchy"],
    "cpp_265": ["class_type", "object_instance", "method_dispatch", "inheritance_hierarchy"],
    "cpp_266": ["class_type", "object_instance", "method_dispatch", "inheritance_hierarchy"],
    "cpp_267": ["class_type", "object_instance", "method_dispatch", "inheritance_hierarchy"],
    "cpp_268": ["class_type", "object_instance", "method_dispatch", "inheritance_hierarchy"],
    "cpp_269": ["class_type", "object_instance", "method_dispatch", "inheritance_hierarchy"],
    "cpp_270": ["class_type", "object_instance", "method_dispatch", "inheritance_hierarchy"],
}
