"""Expected concept overrides for Pascal v4 tasks."""
from __future__ import annotations

SLOT_EXPECTED_CONCEPT_OVERRIDES: dict[str, list[str]] = {
    "pas_001": ["program_entry", "typed_declaration", "assignment", "arithmetic_ops", "stdout_write"],
    "pas_002": ["program_entry", "typed_declaration", "assignment", "arithmetic_ops", "stdout_write"],
    "pas_003": ["program_entry", "typed_declaration", "assignment", "arithmetic_ops", "stdout_write"],
    "pas_004": ["program_entry", "typed_declaration", "assignment", "arithmetic_ops", "stdout_write"],
    "pas_005": ["program_entry", "typed_declaration", "assignment", "arithmetic_ops", "stdout_write"],
    "pas_006": ["program_entry", "typed_declaration", "assignment", "arithmetic_ops", "stdout_write"],
    "pas_007": ["program_entry", "typed_declaration", "assignment", "arithmetic_ops", "stdout_write"],
    "pas_008": ["program_entry", "typed_declaration", "assignment", "arithmetic_ops", "stdout_write"],
    "pas_009": ["program_entry", "typed_declaration", "assignment", "arithmetic_ops", "stdout_write"],
    "pas_010": ["program_entry", "typed_declaration", "assignment", "arithmetic_ops", "stdout_write"],
    "pas_011": ["program_entry", "typed_declaration", "assignment", "arithmetic_ops", "stdout_write"],
    "pas_012": ["program_entry", "typed_declaration", "assignment", "arithmetic_ops", "stdout_write"],
    "pas_013": ["typed_declaration", "stdin_read", "assignment", "arithmetic_ops", "stdout_write"],
    "pas_014": ["typed_declaration", "stdin_read", "assignment", "arithmetic_ops", "stdout_write"],
    "pas_015": ["typed_declaration", "stdin_read", "assignment", "arithmetic_ops", "stdout_write"],
    "pas_016": ["typed_declaration", "stdin_read", "assignment", "arithmetic_ops", "stdout_write"],
    "pas_017": ["typed_declaration", "stdin_read", "assignment", "arithmetic_ops", "stdout_write"],
    "pas_018": ["typed_declaration", "stdin_read", "assignment", "arithmetic_ops", "stdout_write"],
    "pas_019": ["typed_declaration", "stdin_read", "assignment", "arithmetic_ops", "stdout_write"],
    "pas_020": ["typed_declaration", "stdin_read", "assignment", "arithmetic_ops", "stdout_write"],
    "pas_021": ["typed_declaration", "stdin_read", "assignment", "arithmetic_ops", "stdout_write"],
    "pas_022": ["typed_declaration", "stdin_read", "assignment", "arithmetic_ops", "stdout_write"],
    "pas_023": ["typed_declaration", "stdin_read", "assignment", "arithmetic_ops", "stdout_write"],
    "pas_024": ["typed_declaration", "stdin_read", "assignment", "arithmetic_ops", "stdout_write"],
    "pas_025": ["typed_declaration", "stdin_read", "simple_branch", "assignment", "stdout_write"],
    "pas_026": ["typed_declaration", "stdin_read", "simple_branch", "assignment", "stdout_write"],
    "pas_027": ["typed_declaration", "stdin_read", "simple_branch", "assignment", "stdout_write"],
    "pas_028": ["typed_declaration", "stdin_read", "simple_branch", "assignment", "stdout_write"],
    "pas_029": ["typed_declaration", "stdin_read", "simple_branch", "assignment", "stdout_write"],
    "pas_030": ["typed_declaration", "stdin_read", "simple_branch", "assignment", "stdout_write"],
    "pas_031": ["typed_declaration", "stdin_read", "simple_branch", "assignment", "stdout_write"],
    "pas_032": ["typed_declaration", "stdin_read", "simple_branch", "assignment", "stdout_write"],
    "pas_033": ["typed_declaration", "stdin_read", "simple_branch", "assignment", "stdout_write"],
    "pas_034": ["typed_declaration", "stdin_read", "simple_branch", "assignment", "stdout_write"],
    "pas_035": ["typed_declaration", "stdin_read", "simple_branch", "assignment", "stdout_write"],
    "pas_036": ["typed_declaration", "stdin_read", "simple_branch", "assignment", "stdout_write"],
    "pas_037": ["typed_declaration", "stdin_read", "simple_branch", "assignment", "stdout_write"],
    "pas_038": ["typed_declaration", "stdin_read", "simple_branch", "assignment", "stdout_write"],
    "pas_039": ["typed_declaration", "stdin_read", "simple_branch", "assignment", "stdout_write"],
    "pas_040": ["typed_declaration", "stdin_read", "simple_branch", "assignment", "stdout_write"],
    "pas_041": ["typed_declaration", "stdin_read", "simple_branch", "assignment", "stdout_write"],
    "pas_042": ["typed_declaration", "stdin_read", "simple_branch", "assignment", "stdout_write"],
    "pas_043": ["typed_declaration", "stdin_read", "simple_branch", "assignment", "stdout_write"],
    "pas_044": ["typed_declaration", "stdin_read", "simple_branch", "assignment", "stdout_write"],
    "pas_045": ["typed_declaration", "stdin_read", "simple_branch", "assignment", "stdout_write"],
    "pas_046": ["typed_declaration", "stdin_read", "simple_branch", "assignment", "stdout_write"],
    "pas_047": ["typed_declaration", "stdin_read", "simple_branch", "assignment", "stdout_write"],
    "pas_048": ["typed_declaration", "stdin_read", "simple_branch", "assignment", "stdout_write"],
    "pas_049": ["typed_declaration", "stdin_read", "simple_branch", "assignment", "stdout_write"],
    "pas_050": ["typed_declaration", "stdin_read", "simple_branch", "assignment", "stdout_write"],
    "pas_051": ["typed_declaration", "stdin_read", "counted_loop", "pre_condition_loop", "assignment", "stdout_write"],
    "pas_052": ["typed_declaration", "stdin_read", "counted_loop", "pre_condition_loop", "assignment", "stdout_write"],
    "pas_053": ["typed_declaration", "stdin_read", "counted_loop", "pre_condition_loop", "assignment", "stdout_write"],
    "pas_054": ["typed_declaration", "stdin_read", "counted_loop", "pre_condition_loop", "assignment", "stdout_write"],
    "pas_055": ["typed_declaration", "stdin_read", "counted_loop", "pre_condition_loop", "assignment", "stdout_write"],
    "pas_056": ["typed_declaration", "stdin_read", "counted_loop", "pre_condition_loop", "assignment", "stdout_write"],
    "pas_057": ["typed_declaration", "stdin_read", "counted_loop", "pre_condition_loop", "assignment", "stdout_write"],
    "pas_058": ["typed_declaration", "stdin_read", "counted_loop", "pre_condition_loop", "assignment", "stdout_write"],
    "pas_059": ["typed_declaration", "stdin_read", "counted_loop", "pre_condition_loop", "assignment", "stdout_write"],
    "pas_060": ["typed_declaration", "stdin_read", "counted_loop", "pre_condition_loop", "assignment", "stdout_write"],
    "pas_061": ["typed_declaration", "stdin_read", "counted_loop", "pre_condition_loop", "assignment", "stdout_write"],
    "pas_062": ["typed_declaration", "stdin_read", "counted_loop", "pre_condition_loop", "assignment", "stdout_write"],
    "pas_063": ["typed_declaration", "stdin_read", "counted_loop", "pre_condition_loop", "assignment", "stdout_write"],
    "pas_064": ["typed_declaration", "stdin_read", "counted_loop", "pre_condition_loop", "assignment", "stdout_write"],
    "pas_065": ["typed_declaration", "stdin_read", "counted_loop", "pre_condition_loop", "assignment", "stdout_write"],
    "pas_066": ["typed_declaration", "stdin_read", "counted_loop", "pre_condition_loop", "assignment", "stdout_write"],
    "pas_067": ["nested_iteration", "loop_control", "counted_loop", "stdout_write"],
    "pas_068": ["nested_iteration", "loop_control", "counted_loop", "stdout_write"],
    "pas_069": ["nested_iteration", "loop_control", "counted_loop", "stdout_write"],
    "pas_070": ["nested_iteration", "loop_control", "counted_loop", "stdout_write"],
    "pas_071": ["nested_iteration", "loop_control", "counted_loop", "stdout_write"],
    "pas_072": ["nested_iteration", "loop_control", "counted_loop", "stdout_write"],
    "pas_073": ["nested_iteration", "loop_control", "counted_loop", "stdout_write"],
    "pas_074": ["nested_iteration", "loop_control", "counted_loop", "stdout_write"],
    "pas_075": ["nested_iteration", "loop_control", "counted_loop", "stdout_write"],
    "pas_076": ["nested_iteration", "loop_control", "counted_loop", "stdout_write"],
    "pas_077": ["nested_iteration", "loop_control", "counted_loop", "stdout_write"],
    "pas_078": ["nested_iteration", "loop_control", "counted_loop", "stdout_write"],
    "pas_079": ["indexed_sequence", "collection_iteration", "counted_loop", "stdout_write"],
    "pas_080": ["indexed_sequence", "collection_iteration", "counted_loop", "stdout_write"],
    "pas_081": ["indexed_sequence", "collection_iteration", "counted_loop", "stdout_write"],
    "pas_082": ["indexed_sequence", "collection_iteration", "counted_loop", "stdout_write"],
    "pas_083": ["indexed_sequence", "collection_iteration", "counted_loop", "stdout_write"],
    "pas_084": ["indexed_sequence", "collection_iteration", "counted_loop", "stdout_write"],
    "pas_085": ["indexed_sequence", "collection_iteration", "counted_loop", "stdout_write"],
    "pas_086": ["indexed_sequence", "collection_iteration", "counted_loop", "stdout_write"],
    "pas_087": ["indexed_sequence", "collection_iteration", "counted_loop", "stdout_write"],
    "pas_088": ["indexed_sequence", "collection_iteration", "counted_loop", "stdout_write"],
    "pas_089": ["indexed_sequence", "collection_iteration", "counted_loop", "stdout_write"],
    "pas_090": ["indexed_sequence", "collection_iteration", "counted_loop", "stdout_write"],
    "pas_091": ["indexed_sequence", "collection_iteration", "counted_loop", "stdout_write"],
    "pas_092": ["indexed_sequence", "collection_iteration", "counted_loop", "stdout_write"],
    "pas_093": ["indexed_sequence", "collection_iteration", "counted_loop", "stdout_write"],
    "pas_094": ["indexed_sequence", "collection_iteration", "counted_loop", "stdout_write"],
    "pas_095": ["dynamic_array", "collection_iteration", "stdout_write"],
    "pas_096": ["dynamic_array", "collection_iteration", "stdout_write"],
    "pas_097": ["dynamic_array", "collection_iteration", "stdout_write"],
    "pas_098": ["dynamic_array", "collection_iteration", "stdout_write"],
    "pas_099": ["dynamic_array", "collection_iteration", "stdout_write"],
    "pas_100": ["dynamic_array", "collection_iteration", "stdout_write"],
    "pas_101": ["dynamic_array", "collection_iteration", "stdout_write"],
    "pas_102": ["dynamic_array", "collection_iteration", "stdout_write"],
    "pas_103": ["dynamic_array", "collection_iteration", "stdout_write"],
    "pas_104": ["dynamic_array", "collection_iteration", "stdout_write"],
    "pas_105": ["dynamic_array", "collection_iteration", "stdout_write"],
    "pas_106": ["dynamic_array", "collection_iteration", "stdout_write"],
    "pas_107": ["dynamic_array", "collection_iteration", "stdout_write"],
    "pas_108": ["dynamic_array", "collection_iteration", "stdout_write"],
    "pas_109": ["string_sequence", "collection_iteration", "simple_branch", "stdout_write"],
    "pas_110": ["string_sequence", "collection_iteration", "simple_branch", "stdout_write"],
    "pas_111": ["string_sequence", "collection_iteration", "simple_branch", "stdout_write"],
    "pas_112": ["string_sequence", "collection_iteration", "simple_branch", "stdout_write"],
    "pas_113": ["string_sequence", "collection_iteration", "simple_branch", "stdout_write"],
    "pas_114": ["string_sequence", "collection_iteration", "simple_branch", "stdout_write"],
    "pas_115": ["string_sequence", "collection_iteration", "simple_branch", "stdout_write"],
    "pas_116": ["string_sequence", "collection_iteration", "simple_branch", "stdout_write"],
    "pas_117": ["string_sequence", "collection_iteration", "simple_branch", "stdout_write"],
    "pas_118": ["string_sequence", "collection_iteration", "simple_branch", "stdout_write"],
    "pas_119": ["string_sequence", "collection_iteration", "simple_branch", "stdout_write"],
    "pas_120": ["string_sequence", "collection_iteration", "simple_branch", "stdout_write"],
    "pas_121": ["string_sequence", "collection_iteration", "simple_branch", "stdout_write"],
    "pas_122": ["string_sequence", "collection_iteration", "simple_branch", "stdout_write"],
    "pas_123": ["function_definition", "function_invocation", "return_flow"],
    "pas_124": ["function_definition", "function_invocation", "return_flow"],
    "pas_125": ["function_definition", "function_invocation", "return_flow"],
    "pas_126": ["function_definition", "function_invocation", "return_flow"],
    "pas_127": ["function_definition", "function_invocation", "return_flow"],
    "pas_128": ["function_definition", "function_invocation", "return_flow"],
    "pas_129": ["function_definition", "function_invocation", "return_flow"],
    "pas_130": ["function_definition", "function_invocation", "return_flow"],
    "pas_131": ["function_definition", "function_invocation", "return_flow"],
    "pas_132": ["function_definition", "function_invocation", "return_flow"],
    "pas_133": ["function_definition", "function_invocation", "return_flow"],
    "pas_134": ["function_definition", "function_invocation", "return_flow"],
    "pas_135": ["function_definition", "function_invocation", "return_flow"],
    "pas_136": ["function_definition", "function_invocation", "return_flow"],
    "pas_137": ["function_definition", "function_invocation", "return_flow"],
    "pas_138": ["function_definition", "function_invocation", "return_flow"],
    "pas_139": ["function_definition", "function_invocation", "return_flow"],
    "pas_140": ["function_definition", "function_invocation", "return_flow"],
    "pas_141": ["function_definition", "recursion", "simple_branch", "return_flow"],
    "pas_142": ["function_definition", "recursion", "simple_branch", "return_flow"],
    "pas_143": ["function_definition", "recursion", "simple_branch", "return_flow"],
    "pas_144": ["function_definition", "recursion", "simple_branch", "return_flow"],
    "pas_145": ["function_definition", "recursion", "simple_branch", "return_flow"],
    "pas_146": ["function_definition", "recursion", "simple_branch", "return_flow"],
    "pas_147": ["function_definition", "recursion", "simple_branch", "return_flow"],
    "pas_148": ["function_definition", "recursion", "simple_branch", "return_flow"],
    "pas_149": ["search_find", "filter_select", "fold_aggregate", "collection_iteration"],
    "pas_150": ["search_find", "filter_select", "fold_aggregate", "collection_iteration"],
    "pas_151": ["search_find", "filter_select", "fold_aggregate", "collection_iteration"],
    "pas_152": ["search_find", "filter_select", "fold_aggregate", "collection_iteration"],
    "pas_153": ["search_find", "filter_select", "fold_aggregate", "collection_iteration"],
    "pas_154": ["search_find", "filter_select", "fold_aggregate", "collection_iteration"],
    "pas_155": ["search_find", "filter_select", "fold_aggregate", "collection_iteration"],
    "pas_156": ["search_find", "filter_select", "fold_aggregate", "collection_iteration"],
    "pas_157": ["search_find", "filter_select", "fold_aggregate", "collection_iteration"],
    "pas_158": ["search_find", "filter_select", "fold_aggregate", "collection_iteration"],
    "pas_159": ["search_find", "filter_select", "fold_aggregate", "collection_iteration"],
    "pas_160": ["search_find", "filter_select", "fold_aggregate", "collection_iteration"],
    "pas_161": ["search_find", "filter_select", "fold_aggregate", "collection_iteration"],
    "pas_162": ["search_find", "filter_select", "fold_aggregate", "collection_iteration"],
    "pas_163": ["search_find", "filter_select", "fold_aggregate", "collection_iteration"],
    "pas_164": ["search_find", "filter_select", "fold_aggregate", "collection_iteration"],
    "pas_165": ["search_find", "filter_select", "fold_aggregate", "collection_iteration"],
    "pas_166": ["search_find", "filter_select", "fold_aggregate", "collection_iteration"],
    "pas_167": ["sort_order", "collection_iteration"],
    "pas_168": ["sort_order", "collection_iteration"],
    "pas_169": ["sort_order", "collection_iteration"],
    "pas_170": ["sort_order", "collection_iteration"],
    "pas_171": ["sort_order", "collection_iteration"],
    "pas_172": ["sort_order", "collection_iteration"],
    "pas_173": ["sort_order", "collection_iteration"],
    "pas_174": ["sort_order", "collection_iteration"],
    "pas_175": ["sort_order", "collection_iteration"],
    "pas_176": ["sort_order", "collection_iteration"],
    "pas_177": ["key_value_map", "search_find", "indexed_sequence"],
    "pas_178": ["key_value_map", "search_find", "indexed_sequence"],
    "pas_179": ["key_value_map", "search_find", "indexed_sequence"],
    "pas_180": ["key_value_map", "search_find", "indexed_sequence"],
    "pas_181": ["key_value_map", "search_find", "indexed_sequence"],
    "pas_182": ["key_value_map", "search_find", "indexed_sequence"],
    "pas_183": ["key_value_map", "search_find", "indexed_sequence"],
    "pas_184": ["key_value_map", "search_find", "indexed_sequence"],
    "pas_185": ["key_value_map", "search_find", "indexed_sequence"],
    "pas_186": ["key_value_map", "search_find", "indexed_sequence"],
    "pas_187": ["key_value_map", "search_find", "indexed_sequence"],
    "pas_188": ["key_value_map", "search_find", "indexed_sequence"],
    "pas_189": ["file_read", "file_write", "collection_iteration"],
    "pas_190": ["file_read", "file_write", "collection_iteration"],
    "pas_191": ["file_read", "file_write", "collection_iteration"],
    "pas_192": ["file_read", "file_write", "collection_iteration"],
    "pas_193": ["file_read", "file_write", "collection_iteration"],
    "pas_194": ["file_read", "file_write", "collection_iteration"],
    "pas_195": ["file_read", "file_write", "collection_iteration"],
    "pas_196": ["file_read", "file_write", "collection_iteration"],
    "pas_197": ["file_read", "file_write", "collection_iteration"],
    "pas_198": ["file_read", "file_write", "collection_iteration"],
    "pas_199": ["import_dependency", "module_namespace", "symbol_visibility"],
    "pas_200": ["import_dependency", "module_namespace", "symbol_visibility"],
    "pas_201": ["import_dependency", "module_namespace", "symbol_visibility"],
    "pas_202": ["import_dependency", "module_namespace", "symbol_visibility"],
    "pas_203": ["import_dependency", "module_namespace", "symbol_visibility"],
    "pas_204": ["import_dependency", "module_namespace", "symbol_visibility"],
    "pas_205": ["import_dependency", "module_namespace", "symbol_visibility"],
    "pas_206": ["import_dependency", "module_namespace", "symbol_visibility"],
    "pas_207": ["stack_queue", "linked_node", "tree_hierarchy", "graph_edges"],
    "pas_208": ["stack_queue", "linked_node", "tree_hierarchy", "graph_edges"],
    "pas_209": ["stack_queue", "linked_node", "tree_hierarchy", "graph_edges"],
    "pas_210": ["stack_queue", "linked_node", "tree_hierarchy", "graph_edges"],
    "pas_211": ["stack_queue", "linked_node", "tree_hierarchy", "graph_edges"],
    "pas_212": ["stack_queue", "linked_node", "tree_hierarchy", "graph_edges"],
    "pas_213": ["stack_queue", "linked_node", "tree_hierarchy", "graph_edges"],
    "pas_214": ["stack_queue", "linked_node", "tree_hierarchy", "graph_edges"],
    "pas_215": ["stack_queue", "linked_node", "tree_hierarchy", "graph_edges"],
    "pas_216": ["stack_queue", "linked_node", "tree_hierarchy", "graph_edges"],
    "pas_217": ["stack_queue", "linked_node", "tree_hierarchy", "graph_edges"],
    "pas_218": ["stack_queue", "linked_node", "tree_hierarchy", "graph_edges"],
    "pas_219": ["stack_queue", "linked_node", "tree_hierarchy", "graph_edges"],
    "pas_220": ["stack_queue", "linked_node", "tree_hierarchy", "graph_edges"],
    "pas_221": ["stack_queue", "linked_node", "tree_hierarchy", "graph_edges"],
    "pas_222": ["filter_select", "fold_aggregate"],
    "pas_223": ["filter_select", "fold_aggregate"],
    "pas_224": ["filter_select", "fold_aggregate"],
    "pas_225": ["filter_select", "fold_aggregate"],
    "pas_226": ["filter_select", "fold_aggregate"],
    "pas_227": ["filter_select", "fold_aggregate"],
    "pas_228": ["filter_select", "fold_aggregate"],
    "pas_229": ["filter_select", "fold_aggregate"],
    "pas_230": ["filter_select", "fold_aggregate"],
    "pas_231": ["filter_select", "fold_aggregate"],
    "pas_232": ["filter_select", "fold_aggregate"],
    "pas_233": ["filter_select", "fold_aggregate"],
    "pas_234": ["filter_select", "fold_aggregate"],
    "pas_235": ["filter_select", "fold_aggregate"],
    "pas_236": ["filter_select", "fold_aggregate"],
    "pas_237": ["class_type", "object_instance", "method_dispatch"],
    "pas_238": ["class_type", "object_instance", "method_dispatch"],
    "pas_239": ["class_type", "object_instance", "method_dispatch"],
    "pas_240": ["class_type", "object_instance", "method_dispatch"],
    "pas_241": ["class_type", "object_instance", "method_dispatch"],
    "pas_242": ["class_type", "object_instance", "method_dispatch"],
    "pas_243": ["class_type", "object_instance", "method_dispatch"],
    "pas_244": ["class_type", "object_instance", "method_dispatch"],
    "pas_245": ["class_type", "object_instance", "method_dispatch"],
    "pas_246": ["class_type", "object_instance", "method_dispatch"],
    "pas_247": ["class_type", "object_instance", "method_dispatch"],
    "pas_248": ["class_type", "object_instance", "method_dispatch"],
    "pas_249": ["class_type", "object_instance", "method_dispatch"],
    "pas_250": ["class_type", "object_instance", "method_dispatch"],
    "pas_251": ["class_type", "object_instance", "method_dispatch"],
    "pas_252": ["class_type", "object_instance", "method_dispatch"],
    "pas_253": ["class_type", "object_instance", "method_dispatch"],
    "pas_254": ["class_type", "object_instance", "method_dispatch"],
    "pas_255": ["class_type", "object_instance", "method_dispatch"],
    "pas_256": ["class_type", "object_instance", "method_dispatch"],
    "pas_257": ["class_type", "object_instance", "method_dispatch"],
    "pas_258": ["class_type", "object_instance", "method_dispatch"],
    "pas_259": ["class_type", "object_instance", "method_dispatch"],
    "pas_260": ["class_type", "object_instance", "method_dispatch"],
    "pas_261": ["class_type", "object_instance", "method_dispatch", "inheritance_hierarchy"],
    "pas_262": ["class_type", "object_instance", "method_dispatch", "inheritance_hierarchy"],
    "pas_263": ["class_type", "object_instance", "method_dispatch", "inheritance_hierarchy"],
    "pas_264": ["class_type", "object_instance", "method_dispatch", "inheritance_hierarchy"],
    "pas_265": ["class_type", "object_instance", "method_dispatch", "inheritance_hierarchy"],
    "pas_266": ["class_type", "object_instance", "method_dispatch", "inheritance_hierarchy"],
    "pas_267": ["class_type", "object_instance", "method_dispatch", "inheritance_hierarchy"],
    "pas_268": ["class_type", "object_instance", "method_dispatch", "inheritance_hierarchy"],
    "pas_269": ["class_type", "object_instance", "method_dispatch", "inheritance_hierarchy"],
    "pas_270": ["class_type", "object_instance", "method_dispatch", "inheritance_hierarchy"],
}
